README.md
Noticed a couple little grammar issues in the README:
- "for buildings REST APIs" is incorrect grammar.
- 2nd half of 2nd sentence is grammatically confusing (unclear if it is saying "REST APIs that promotes" or "workflow... that promotes") Using "which" makes it clear that the workflow is what is promoting these best practices. (I believe that is what was originally intended?)
=> fixed grammar error in README

Scala-Integration.md
`restli-tools-scala` is moved into https://github.com/linkedin/sbt-restli (com.linkedin.sbt-restli:restli-tools-scala) as of pegasus 26.0.0
@karthikbalasub
=> Update scala integration docs

Asynchronous-Servers-and-Clients-in-Rest_li.md, Dynamic-Discovery.md, Rest_li-2.x-upgrade-instructions.md, Rest_li_Avro_conversions.md, Send-Rest_li-Request-Query-In-Request-Body_converted.md, Validation-in-Rest_li_converted.md, Writing-unit-tests-for-Rest_li-clients-and-servers.md, _data/user_guide_navigation.yml, compatibility_check.md, d2_quick_start.md, gradle.md, guide_restli_client.md, guide_restli_server.md, modeling.md, protocol.md, step_by_step.md
Closes #131 
Fixes all broken links picked up by a site crawler script.
Also fixes some line-ending issues which resulted in whole
files being altered. Also fixed a misspelled file name.
=> Fix all known broken links

Rest_li_Avro_conversions.md, gradle.md
Adding documentation for how to use the namespace override option in Avro translation, since apparently there's no documentation at all about this. Also updated the part that describes the command-line arguments to use in order to add the system properties for this as well as for the optional default option.
=> Add documentation for namespace override in Avro translation

_config.yml
Fixes bug from PR #137 
Misspelled "rouge" as "rogue"
=> Fix syntax highlighter configuration

How-to-use-projections-in-Java_converted.md
Junchuan pointed out that there were formatting issues on [this page](https://linkedin.github.io/rest.li/How-to-use-projections-in-Java). I went in and fixed the formatting. I also removed the empty whitespace at the end of some lines.
=> Fix formatting on the "How to Use Projections" page

_data/api_reference_navigation.yml, _data/urls.yml, _data/user_guide_navigation.yml, guide_restli_server.md, guide_service_errors_java.md, reference_service_errors.md
Not done yet, would just like some preliminary review.
Added:
- Page for detailing service errors in detail. So far just has ErrorResponse info.
- Page for describing how to set up service errors step-by-step.
- Added information for success responses.
- Added examples of IDLs with service error and success response info.
- Added data file containing base URL for GitHub repo for easy usage when making links.
=> WIP: Add documentation for service errors

protocol.md
Protocol incorrectly said X-RestLi-Method would be set to an uppercase string. It will actually be set to a lowercase string
=> Fix X-Restli-Method header documentation 

Attachment-Streaming_converted.md, Validation-in-Rest_li_converted.md, batch_finder_resource_method.md, guide_restli_server.md, pdl_syntax.md, step_by_step.md
Marks PDL code snippets as containing PDL. Also fixes various things in the PDL documentation (e.g. simplifying examples, adding new examples, fixing typos).
**Note:** Split this up from the other PR (#162) for clarity, though the highlighting changes won't actually show up until both are merged.
=> General PDL documentation cleanup

_data/user_guide_navigation.yml, pdl_migration.md, pdl_syntax.md
This page shows how to migrate from PDSC to PDL, as well as a comparison
showing notable differences between the two formats.
=> Add "Migrating from PDSC to PDL" page

data/src/main/java/com/linkedin/data/schema/SchemaToPdlEncoder.java, generator-test/src/test/java/com/linkedin/pegasus/generator/test/pdl/PdlEncoderTest.java, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/enums/EscapedSymbols.pdl, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/unions/WithAliases.pdl
Previously, the PDL encoder wasn't escaping reserved keywords
when used as union member aliases.
e.g.
``union[`record`: int, `namespace`: string]``
``enum{`record`, `namespace`}``
rather than
`union[record: int, namespace: string]`
`enum{record, namespace}`
=> Properly escape union member aliases in PDL

restli-client-testutils/src/main/java/com/linkedin/restli/client/testutils/MockCollectionResponseFactory.java, restli-client-testutils/src/test/java/com/linkedin/restli/client/testutils/test/TestMockCollectionResponseFactory.java
The current version of `MockCollectionResponseFactory` only allows mocking `elements` and `paging` data. The PR adds a small enhancement for mocking custom metadata.
=> Enhance MockCollectionResponseFactory to mock custom metadata

.travis.yml
Currently, feature branch PRs trigger two builds: one for the branch and one for the PR.
This attempts to remove that redundancy by only building on the master branch as well
as release tags.
=> Configure Travis to only build on master and tags

prepare-release
When the `prepare-release` script fails to push the locally created
release tag, it should delete the tag locally so as not to confuse
the developer.
=> Fix prepare-release script so that tag is deleted on failed push

data/src/main/antlr/com/linkedin/data/grammar/Pdl.g4, data/src/main/java/com/linkedin/data/schema/PdlBuilder.java, data/src/test/java/com/linkedin/data/schema/grammar/TestPdlSchemaParser.java, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/escaping/PropertyKeyEscaping.pdl, gradle.properties
Allow PDL parser and encoder to support property keys with special characters.
Also sort properties by key before encoding them to ensure ordering consistency.
=> Fix issues when encoding/parsing custom properties in PDL.

d2/src/main/java/com/linkedin/d2/balancer/Facilities.java, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerWithFacilitiesDelegator.java, d2/src/main/java/com/linkedin/d2/balancer/properties/PropertyKeys.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/util/ClusterInfoProvider.java, d2/src/main/java/com/linkedin/d2/balancer/util/DelegatingFacilities.java, d2/src/main/java/com/linkedin/d2/balancer/util/TogglingLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/zkfs/LastSeenLoadBalancerWithFacilities.java, d2/src/main/java/com/linkedin/d2/balancer/zkfs/ZKFSLoadBalancer.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerTest.java, d2/src/test/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancerTest.java
Add API to provide basic cluster information. Initially this will just give a way to find the number of instances in a D2 cluster, based on scheme (http/https) and partitionid.  This new API will be part of Facilities. I provided a default implementation in Facilities, so this change is backwards compatible. This feature will allow dark cluster dispatchers to shape traffic to a dark canary cluster.
I'm not able to consolidate the tests because several of those variables are modified in many of the tests in different ways.
=> ClusterInfoProvider API and implementation

pre-release-check, prepare-release
Necessary in case someone names their feature branch using the
release tag naming convention (e.g. `v*.*.*`). Also adds a check
to ensure that the target commit is an ancestor of master, and
cleans up the pre-release-check script a little bit.
=> Add check to prepare-release script to prevent branch conflicts

data/src/main/java/com/linkedin/data/schema/AbstractSchemaParser.java, data/src/main/java/com/linkedin/data/schema/grammar/PdlSchemaParser.java, data/src/test/java/com/linkedin/data/schema/annotation/TestSchemaAnnotationProcessor.java, data/src/test/java/com/linkedin/data/schema/resolver/TestDataSchemaResolver.java, data/src/test/resources/com/linkedin/data/schema/annotation/denormalizedsource/invalid/3_5_cyclic_from_include.pdl
Right now PDL parser wouldn't detect cyclic referencing for "includes" and "typeref"
This change will fix this issue so we have feature parity between PDL and PDSC on cyclic referencing detection.
=> Fix for PDL schema cyclic referencing detection in "includes" and "typeref" 

gradle.properties, r2-core/src/main/java/com/linkedin/r2/transport/http/client/AsyncPoolImpl.java, r2-core/src/main/java/com/linkedin/r2/transport/http/client/AsyncPoolStats.java, r2-core/src/main/java/com/linkedin/r2/transport/http/client/AsyncPoolStatsTracker.java, r2-core/src/main/java/com/linkedin/r2/transport/http/client/ExponentialBackOffRateLimiter.java, r2-core/src/main/java/com/linkedin/r2/transport/http/client/PoolStats.java, r2-core/src/main/java/com/linkedin/r2/transport/http/client/WaiterTimeoutException.java, r2-core/src/test/java/test/r2/transport/http/client/TestAsyncPool.java, r2-int-test/src/test/java/test/r2/integ/clientserver/TestHttpsEarlyHandshake.java, r2-netty/src/main/java/com/linkedin/r2/netty/client/http/HttpChannelInitializer.java, r2-netty/src/main/java/com/linkedin/r2/netty/client/http/HttpChannelPoolFactory.java, r2-netty/src/main/java/com/linkedin/r2/netty/client/http2/Http2ChannelInitializer.java, r2-netty/src/main/java/com/linkedin/r2/netty/client/http2/Http2ChannelPoolFactory.java, r2-netty/src/main/java/com/linkedin/r2/netty/handler/common/SessionResumptionSslHandler.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/HttpClientFactory.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/common/ChannelPoolLifecycle.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/common/ChannelPoolManagerFactoryImpl.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/rest/HttpNettyChannelPoolFactory.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/stream/http/HttpNettyStreamChannelPoolFactory.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/stream/http/RAPStreamClientPipelineInitializer.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/stream/http2/Http2AlpnHandler.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/stream/http2/Http2ClientPipelineInitializer.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/stream/http2/Http2NettyStreamChannelPoolFactory.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/HttpClientBuilder.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/stream/http2/TestEarlyUpgrade.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/stream/http2/TestHttp2AlpnHandler.java
When a object creation request to the pool is faster than the actual creation itself - the rate limiter queues all the incoming requests and creates the object without considering the fact that the checked out objects would come back to the pool.
This change is to make sure that the rate limiter task always check if there is a waiter in the queue or the pool is under the minimum level.
=> AsyncPool Improvements and Fixes

data-avro/src/main/java/com/linkedin/data/avro/DataTranslator.java, data-avro/src/test/java/com/linkedin/data/avro/TestDataTranslator.java
Due to introduction of PegasusToAvroDefaultFieldTranslationMode, some of the translation from (Pegasus required with default) to (Avro optional) or (Avro optional) to (Pegasus required with default) cannot be performed correctly.
This PR is for that fix. Also added test cases.
=> Fix data translator for translating Pegasus non-union field to Avro union and vise versa

src/pdl_schema.md
Update the example for typeref to remove the confusion about it being a cyclic reference.
=> Fix typo in typeref example

d2-schemas/src/main/pegasus/com/linkedin/d2/D2TransportClientProperties.pdsc, d2/src/main/java/com/linkedin/d2/balancer/config/TransportClientPropertiesConverter.java, d2/src/main/java/com/linkedin/d2/balancer/properties/PropertyKeys.java
Add Streaming Timeout to Transport Client Properties Converter so that these properties get serialized and deserialized properly.
=> Add Streaming Timeout to TransportClient Properties

data-avro/src/test/java/com/linkedin/data/avro/TestSchemaTranslator.java, data/src/main/java/com/linkedin/data/codec/AbstractJacksonDataCodec.java, data/src/main/java/com/linkedin/data/schema/JsonBuilder.java, data/src/main/java/com/linkedin/data/template/JacksonDataTemplateCodec.java
Currently when translating to Avro or Pegasus schema, nested properties wouldn't have deterministic and based on its implementation (DataMap type), the order is given from HashMap, which is indeterministic.
This change would affect [pegasus to avro] translation AND [avro to peagsus] translation when outputting string (only for properties encoding). It wouldn't affect memory representation.
wc-test:
https://crt.prod.linkedin.com/#/testing/executions/7037b41c-8501-4db9-9237-1f54c5964c68/execution
=> Enforce schema properties order in JsonBuilder so Pegasus schema and Avro schema properties would have deterministic order

gradle.properties, r2-core/src/main/java/com/linkedin/r2/transport/http/client/AsyncPoolImpl.java, r2-core/src/main/java/com/linkedin/r2/transport/http/client/ObjectCreationTimeoutException.java, r2-core/src/main/java/com/linkedin/r2/transport/http/client/TimeoutCallback.java, r2-core/src/test/java/test/r2/transport/http/client/TestAsyncPool.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/common/ChannelPoolLifecycle.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestHttpNettyClient.java
Introduce an object creation timeout to completely de-couple channel creation from channelPooll
Remove retry during failure
Fix ssl handshake timeout isssue
=> Introduce an object creation timeout to completely de-couple channel creation from channelPool

gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/ValidateSchemaAnnotationTask.java, gradle.properties
Current in ValidateSchemaAnnotationTask, we try to find annotation handler by searching a class with certain java annotation ("RestLiSchemaAnnotationHandler") inside the dependencies. Therefore we need to use "Class.forName(<className>)}" methods.
However there might be exception/errors raised during this period of time, such as java.lang.NoClassDefFoundError, java.lang.IllegalAccessError, java.lang.IllegalAccessError
This is mostly likely due to the fact the the user didn't config the grade dependencies properly. For those classes that failed to be instantiated, they will be ignored.
=> Change ValidateSchemaAnnotationTask to ignore exception or errors durng initializaing class by classLoader

gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/TranslateSchemasTask.java, gradle.properties
Use PathingJarUtil to prepare manifest-only JAR for invocations of TranslateSchemasTask
Avoids "error=7, Argument list too long" error
=> Use manifest-only JAR for TranslateSchemasTask

gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/ValidateSchemaAnnotationTask.java
In PR: https://github.com/linkedin/rest.li/pull/218
I made a change to ignore errors if the class failed to be instantiated during search for handlers.
The problem with this is that the handlers under the search, might also encounter failure in instantiation and we would accidentally skip any validation to be done by this handler.
This PR is to add an exception when we fail to see all configured handlers initialized and found. By doing this, we can ensure that all configured handlers need to be found before we run validation, otherwise the user will see error message.
=> Raise exception in ValidateSchemaAnnotationTask if any handler configured not found.

local-release, pre-release-check, prepare-release
Publishes Maven artifacts to `~/local-repo`
How to use: `./local-release`
Tested that internal projects can build against these locally released artifacts, and they can.
=> Add local-release script

build.gradle, gradle.properties
To avoid security vulnerabilities in spring 3.2.0 - 3.2.14
This is a patch version bump, so there should theoretically be minimal side effects.
=> Bump spring dependencies to 3.2.18.RELEASE

build.gradle, gradle.properties
Publish the darkcluster test artifacts so the Mock test classes can be reused.
This isn't testable in snapshot, as all artifacts were available in local snapshot.
=> publish the test artifacts for darkcluster

build.gradle, data/build.gradle, data/src/main/java/com/linkedin/data/schema/PdlBuilder.java, data/src/main/java/com/linkedin/data/schema/grammar/PdlParseUtils.java, gradle.properties
StringEscapeUtils is deprecated in the latest version of commons-lang3
with recommendation to move to commons-text.
=> Switch from commons-lang3 to commons-text.

build_script/bintrayRelease.gradle
Although the previous fix solved the issue for test artifacts, the fix
didn't actually add extra artifacts to the publication. This fix waits
until sub-projects are evaluated to add the extra artifacts, since this
is when they're defined.
Where "extra artifacts" are artifacts with non-standard classifiers (e.g. `-all` for "far JARs").
**Note:** The diff looks weird, but all I did was wrap the relevant logic in an `afterEvaluate` closure.
=> Fix Maven publication for extra artifacts again

data/src/main/java/com/linkedin/data/element/AbstractDataElement.java, data/src/test/java/com/linkedin/data/element/TestDataElement.java
User can generate pathspec from dataelement, based on the element's schema.
For map type and array type, the pathspec is supposed to be a wildcard (asteriod sign), but for now if the element's schema is a typeref to a map, it is still using the element key (instead of a wildcard)
This change is to fix and add test to show the change.
=> Fix the pathSpec generated for typeRef DataElement

d2-schemas/src/main/pegasus/com/linkedin/d2/DarkClusterConfig.pdl, d2-schemas/src/main/pegasus/com/linkedin/d2/DarkClusterStrategyName.pdl, d2-schemas/src/main/pegasus/com/linkedin/d2/multiplierStrategyType.pdl, d2/src/main/java/com/linkedin/d2/balancer/config/DarkClustersConverter.java, d2/src/main/java/com/linkedin/d2/balancer/config/TransportClientPropertiesConverter.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ClusterProperties.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ClusterPropertiesJsonSerializer.java, d2/src/main/java/com/linkedin/d2/balancer/properties/PropertyKeys.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/test/java/com/linkedin/d2/balancer/StaticLoadBalancerState.java, d2/src/test/java/com/linkedin/d2/balancer/config/DarkClustersConverterTest.java, d2/src/test/java/com/linkedin/d2/balancer/properties/ClusterPropertiesSerializerTest.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerStateTest.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerTest.java, darkcluster/src/main/java/com/linkedin/darkcluster/impl/DarkClusterStrategyFactoryImpl.java, darkcluster/src/main/java/com/linkedin/darkcluster/impl/RelativeTrafficMultiplierDarkClusterStrategy.java, darkcluster/src/test/java/com/linkedin/darkcluster/DarkClusterTestUtil.java, darkcluster/src/test/java/com/linkedin/darkcluster/TestDarkClusterStrategyFactory.java
Adding multiplierStrategyList and transportClientProperties for dark clusters.
multiplierStrategyList - this is a list instead of a single value to decoupling adding a new strategy from the rollout. Esp in large services or where a client side dispatching mechanism is chosen, this will allow the new strategy to be picked up as its available, instead of requiring all dark clients to be upgraded first before turning it on. This is a lesson learned from when DegraderLoadBalancerStrategyName was deprecated in favor of DegraderLoadBalancerStrategyList for the same reason.
There are two strategies: RELATIVE_TRAFFIC and CONSTANT_QPS. only RELATIVE_TRAFFIC is implemented so far. The Javadocs in the corresponding classes have more details on how those strategies work.
transportClientProperties - …
=> DarkCluster schema changes: adding multiplierStrategyList and transportClientProperties

d2/src/test/java/com/linkedin/d2/balancer/config/DarkClustersConverterTest.java
Not sure why my builds didn't catch this before. we removed the automatic defaults for the maxTargetRate and targetRate, so we need to make the applicable changes in the tests.
=> fix failing DarkClustersConverter tests.

build.gradle
Update avroUtil to com.linkedin.avroutil1:helper-all:0.1.11
There was an issue -"java.lang.NoSuchMethodError:setValidateDefaults(Z) exception on holdem & war" in avroUtil, it has been fixed in 0.1.11. To avoid customers encountering this issue, bump avroUtil version.
=> Update avroUtil to com.linkedin.avroutil1:helper-all:0.1.11

data/src/main/java/com/linkedin/data/ByteString.java, data/src/main/java/com/linkedin/data/codec/ProtobufCodecOptions.java, data/src/main/java/com/linkedin/data/codec/ProtobufDataCodec.java, data/src/test/java/com/linkedin/data/codec/CodecDataProviders.java, data/src/test/java/com/linkedin/data/codec/TestCodec.java, data/src/test/java/com/linkedin/data/codec/TestProtobufCodec.java, gradle.properties, li-protobuf/src/main/java/com/linkedin/data/protobuf/ByteArrayReader.java, li-protobuf/src/main/java/com/linkedin/data/protobuf/InputStreamReader.java, li-protobuf/src/main/java/com/linkedin/data/protobuf/ProtoReader.java, li-protobuf/src/main/java/com/linkedin/data/protobuf/ProtoWriter.java, restli-common/src/main/java/com/linkedin/restli/common/ContentType.java
This PR provides an option to serialize floats and doubles as fixed length values. 
Variable length encoding works well for a vast majority of use cases where float and double data are of limited precision, and hence is a sensible default.
However, there are use cases where we need to encode/decode several full precision float and double values (say tensor data for ML features), where the additional varint overhead (+1 byte for floats, +2 bytes for doubles), actually has a negative impact. In such cases, we want an option to fallback to fixed length encoding.
=> Fixed length encoding support for floats and doubles in protobuf

d2-schemas/src/main/pegasus/com/linkedin/d2/DarkClusterConfig.pdl, gradle.properties
turns out transportClientProperties has some required fields and putting it into other repos can fail validation because those required fields aren't in the default {}. So the two choices are to either:
1. set the default to include every required field in transportClientProperties, or
2. make the field optional.
I chose the latter. (#2), as it seems cleaner from the pdl perspective.
I've been working with Karthik on this. Karthik, can you review?
Chris, this is just fyi.
=> change transportClientProperties to optional

gradle.properties, r2-netty/src/main/java/com/linkedin/r2/netty/client/http/HttpChannelInitializer.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/HttpClientFactory.java
1. Fix MaxContentLength bug in HttpChannelInitializer
2. Add info log to log information on http protocol used
=> Fix maxContentLength Issue & Log HttpProtocol used per Service

gradle.properties, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/common/ChannelPoolLifecycle.java
Errors in dark canary dispatchers can throw off validation frameworks. In ChannelPoolLifecycle, if the dark canary is unreachable, you will get errors from netty that are logged in this class. By changing this to warn, it still logs the problem, but at a warn level. If it's truly a problem, such as failing a call, that can and will be detected higher up and can be recorded as an error there. For instance, even outside of dark canary, if it's a RetriableException, a new channel can be created to service the request, so this shouldn't be logged as an error. I will send further details separately.
=> change errors in ChannelPoolLifecycle to warn

data/build.gradle, data/src/main/java/com/linkedin/data/schema/DataSchemaLocation.java, data/src/main/java/com/linkedin/data/schema/resolver/AbstractDataSchemaResolver.java, data/src/main/java/com/linkedin/data/schema/resolver/InJarFileDataSchemaLocation.java, data/src/test/java/com/linkedin/data/schema/resolver/TestDataSchemaResolver.java
When parsing schemas, the AbstractDataSchemaResolver stores bad schema locations in an instance variable. If the DataSchemaLocation is a InJarFileDataSchemaLocation, that means we are storing the entire jar in the _badLocations set, and not allowing it to be garbage collected.
We have seen this cause undue memory pressure / OOMs when resolving Schemas.
This introduces a light-weight representation of InJarFileDataSchemaLocation, by just storing the path to the jar and the path once inside the jar. This fulfills the equals and hashCode requirements of DataSchemaLocation without the overhead of the entire jar.
Discovered by analyzing a heap dump using jxray:
=> Creating a light-weight representation of InJarFileDataSchemaLocation

data/src/main/java/com/linkedin/data/schema/JsonBuilder.java, restli-tools/src/main/java/com/linkedin/restli/tools/snapshot/gen/SnapshotGenerator.java
Reuse the expensive Jackson factories in the JsonBuilder to reduce garbage. Provide an option to encode to a custom writer to allow writing directly to files in some cases for reasons of efficiency
=> JsonBuilder efficiency improvements

.travis.yml, build.gradle, d2/src/test/java/com/linkedin/d2/balancer/servers/ZookeeperConnectionManagerTest.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerTest.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/degrader/DegraderLoadBalancerTest.java, d2/src/test/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancerTest.java, d2/src/test/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStoreWithFiltersTest.java, darkcluster/src/test/java/com/linkedin/darkcluster/TestDarkClusterVerifierManager.java, multipart-mime/src/test/java/com/linkedin/multipart/TestMIMEReader.java, r2-core/src/test/java/test/r2/transport/http/client/TestAsyncPool.java, r2-int-test/src/test/java/test/r2/integ/clientserver/TestStreamEcho.java, r2-int-test/src/test/java/test/r2/integ/clientserver/TestStreamResponse.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestChannelPoolManagerFactorySharingConnection.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestHttpNettyClient.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/stream/http2/TestHttp2NettyStreamClient.java, restli-int-test/build.gradle, restli-int-test/src/test/java/com/linkedin/restli/client/TestResponseDecoder.java, restli-int-test/src/test/java/com/linkedin/restli/client/TestRestLiD2Integration.java, restli-int-test/src/test/java/com/linkedin/restli/client/multiplexer/TestMultiplexerDelays.java, restli-int-test/src/test/java/com/linkedin/restli/examples/RestLiIntegrationTest.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestRequestCompression.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestResponseCompression.java, restli-int-test/src/test/java/com/linkedin/restli/examples/instrumentation/TestLatencyInstrumentation.java, scripts/travis/build.sh, test-util/src/main/java/com/linkedin/test/util/retry/Retries.java, test-util/src/main/java/com/linkedin/test/util/retry/SingleRetry.java, test-util/src/main/java/com/linkedin/test/util/retry/ThreeRetries.java
Enabling tests in the Travis CI build to give us higher confidence in proposed changes. Addresses tests with CI flakiness:
- Tests that are flaky in Travis are added to the group `ci-flaky`, which is excluded only in the CI environment (i.e. they'll still run locally).
- Some flaky tests were given one retry using the `SingleRetry` class, though they should still be investigated (note that some tests might need a retry even when run locally).
- I've created two internal tracking tickets to track addressing the flaky tests: one for R2/D2-related tests, and one for everything else.
**Other changes:**
- Added a new script `scripts/travis/build.sh` which is run for each tag, master, and each PR. However, the tests are skipped when building on a tag to avoid flaky releases.
- Added extra …
=> Enable tests in Travis, use retries for some tests

d2/src/test/java/com/linkedin/d2/balancer/servers/ZookeeperConnectionManagerTest.java, r2-int-test/src/test/java/test/r2/integ/clientserver/TestStreamResponse.java
Excludes:
- `ZookeeperConnectionManagerTest > testMarkUpAndDownMultipleTimesFinalUp`
- `TestStreamResponse > testBackpressure`
=> Exclude 2 flaky tests in Travis CI

d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/util/HostOverrideList.java, d2/src/main/java/com/linkedin/d2/balancer/util/LoadBalancerUtil.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerTest.java, d2/src/test/java/com/linkedin/d2/balancer/util/TestHostOverrideList.java, gradle.properties
**Requirements**
To support features like Fullstack Hovr, D2 needs to support the following routing override scenarios.
1. Route requests going to a given cluster to a specific host.
2. Route requests going to a given service to a specific host.
3. Provide route overrides for multiple clusters and services.
D2 provides an existing override mechanism called TargetHints. However, TargetHints does not meet the above requirements due to the following restrictions.
TargetHints does not allow multiple overrides for different clusters and services.
TargetHints requires users to provide a full URL as opposed to a URL prefix like the D2 announcer. Therefore, we lose the flexibility of appending the service paths for different D2 services.
**Implementation**
Similar to TargetHints, HostOverrideList …
=> Implement Host Override List feature in D2.

gradle.properties, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestHttpNettyStreamClient.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/RestLiAnnotationReader.java, restli-server/src/test/java/com/linkedin/restli/internal/server/model/SampleResources.java, restli-server/src/test/java/com/linkedin/restli/internal/server/model/TestRestLiApiBuilder.java
When a finder resource class returns a non-record (Data type is POJO or not defined in PDL files) the restspec generation will be halted by seeing a NPE. The NPE is caused by `valueClass` being `null`.
=> Handle valueClass NPE issue and give warnings

data/src/main/java/com/linkedin/data/codec/entitystream/AbstractDataDecoder.java, data/src/main/java/com/linkedin/data/codec/entitystream/AbstractDataEncoder.java, data/src/main/java/com/linkedin/data/codec/entitystream/ProtobufDataDecoder.java, data/src/main/java/com/linkedin/data/codec/entitystream/ProtobufStreamDataCodec.java, data/src/test/java/com/linkedin/data/codec/CodecDataProviders.java, data/src/test/java/com/linkedin/data/codec/entitystream/TestStreamCodec.java, gradle.properties, restli-common/src/main/java/com/linkedin/restli/common/ContentType.java
1. Add streamProtobuf data codec and use it in content type
2. Expose codec interfaces required to extend for application specific value ordinals
=> add protobuf stream data codec and use in PROTOBUF2

gradle.properties
There are no code changes between this release and the previous release.
Bumping because this version will be the first to be released only as an
external library.
=> Release 29.1.0

gradle.properties, restli-int-test-api/build.gradle
In order to avoid failures in LinkedIn's external dependency system, we
have to get rid of the `all` classifier since apparently it causes
failures.
For context: the `all` classifier of `:restli-int-test-api` contains the main classes along with generated data templates and rest classes
=> Reclassify -all as -with-generated for restli-int-test-api

scripts/travis/publish-tag.sh
There exists a problem now where a Bintray upload can partially fail,
leaving the repo in a bad state where future uploads may fail due to
conflicts. This fix adjusts the Travis script so that a failed Bintray
upload will result in an API call to completely delete the version.
=> Roll back Bintray upload on failure in Travis

gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/symbol/RestLiSymbolTableProvider.java
There are a few instances where we may want to use a pre-generated response symbol table (Say in services talking to remote mobile/web clients where symbol order and name needs to be determined at build time). Add a constructor in the symbol table provider to account for such use cases.
=> Expose an additional constructor that can accept pre-generated response symbol table

gradle.properties, restli-common/src/main/java/com/linkedin/restli/common/SymbolTableBasedContentTypeProvider.java, restli-common/src/test/java/com/linkedin/restli/internal/common/TestContentType.java
This is useful for cases like remote clients where the client wants the server to encode the response with the symbol table it has, instead of the one the server has
=> Allow the client to specify the response symbol table

r2-filter-compression/src/main/java/com/linkedin/r2/filter/compression/streaming/BufferedReaderInputStream.java
only propagate the exception message instead of the entire exception here
=> Only include the underlying exception message in BufferedReaderInputStream

darkcluster-test-api/src/main/java/com/linkedin/darkcluster/MockClusterInfoProvider.java, darkcluster/src/main/java/com/linkedin/darkcluster/impl/DarkClusterStrategyFactoryImpl.java, darkcluster/src/test/java/com/linkedin/darkcluster/TestDarkClusterStrategyFactory.java
The Dark Cluster ClusterListener is registered after we have already started listening to the cluster, so we need to explicitly trigger a refresh of the dark cluster strategies. The previous change introduced this bug by moving all strategy changes into the ClusterListener (instead of creating the strategy on demand), but forgetting to make sure we have an updated state after we start listening. 
I added a unit test and logging to make sure we don't regress and can tell the order in production logs.
=> fix dark cluster startup problem

gradle-plugins/build.gradle, gradle-plugins/src/integTest/groovy/com/linkedin/pegasus/gradle/PegasusPluginCacheabilityTest.groovy, gradle-plugins/src/integTest/groovy/com/linkedin/pegasus/gradle/PegasusPluginIntegrationTest.groovy, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle-plugins/src/test/java/com/linkedin/pegasus/gradle/TestPegasusPlugin.java
This PR needs to go into master after https://github.com/linkedin/rest.li/pull/328/
The Issue:
The issue is that the pegasus plugin, when preparing the schemas for
publication, will copy the schemas to the build directory without
removing stale schemas. Without the fix, these stale schemas will be
packaged into the data template jar -> which is a problem.
The current workaround, which is implemented, is that we have a delete
task and a copy task. The delete task is triggered by a gradle project
flag. The copy moves the files as intended. This workaround is not
viable since it breaks the UP-TO-DATE checks between builds. In
particular, it breaks the UP-TO-DATE checks during a HOT RELOAD
(runPlay task of the Play Framework).
The Fix:
Instead of the workaround as above, we "skip" the delete …
=> Update Pegasus Plugin's CopySchema tasks to delete stale schemas 

CHANGELOG.md, data/src/main/java/com/linkedin/data/codec/ProtobufCodecOptions.java, data/src/main/java/com/linkedin/data/codec/ProtobufDataCodec.java, data/src/main/java/com/linkedin/data/codec/entitystream/ProtobufDataEncoder.java, data/src/test/java/com/linkedin/data/codec/CodecDataProviders.java, data/src/test/java/com/linkedin/data/codec/TestProtobufCodec.java, gradle.properties, li-protobuf/src/main/java/com/linkedin/data/protobuf/ProtoWriter.java, li-protobuf/src/main/java/com/linkedin/data/protobuf/Utf8Utils.java
The graceful degradation is similar to jackson, in the sense that every invalid surrogate is replaced by ?
=> Add an option (enabled by default) to gracefully degrade on encountering invalid surrogate pairs during protobuf string serialization

CHANGELOG.md, data/src/main/java/com/linkedin/data/codec/AbstractJacksonDataCodec.java, data/src/main/java/com/linkedin/data/codec/JacksonDataCodec.java, data/src/main/java/com/linkedin/data/codec/entitystream/AbstractJacksonDataDecoder.java, data/src/main/java/com/linkedin/data/codec/entitystream/JacksonJsonDataDecoder.java, data/src/main/java/com/linkedin/data/codec/entitystream/JacksonJsonDataEncoder.java, data/src/main/java/com/linkedin/data/codec/entitystream/JacksonJsonDataListDecoder.java, data/src/main/java/com/linkedin/data/codec/entitystream/JacksonJsonDataMapDecoder.java, data/src/main/java/com/linkedin/data/codec/entitystream/JacksonStreamDataCodec.java, data/src/test/java/com/linkedin/data/codec/TestJacksonCodec.java, data/src/test/java/com/linkedin/data/codec/entitystream/TestJacksonJsonDataEncoder.java, gradle.properties
1. Make JsonFactory parameterized so that multiple codec instances can share the same factory if necessary
2. Make the default factory a static singleton for factory reuse to minimize garbage
Interning seems to be messing with batch_get where the keys are not schema but are values, resulting in a large number of strings being interned.
=> Disable string interning in Jackson JSON since it causes GC issues

CHANGELOG.md, data-transform/src/main/java/com/linkedin/data/transform/filter/FilterConstants.java, data-transform/src/main/java/com/linkedin/data/transform/filter/MaskComposition.java, data-transform/src/main/java/com/linkedin/data/transform/filter/request/MaskCreator.java, data-transform/src/test/java/com/linkedin/data/transform/filter/TestFilterOnData.java, data-transform/src/test/java/com/linkedin/data/transform/filter/TestMaskCompositionOnData.java, data-transform/src/test/java/com/linkedin/data/transform/filter/TestMaskCreation.java, gradle.properties, restli-common/src/main/java/com/linkedin/restli/internal/common/URIMaskUtil.java, restli-common/src/main/java/com/linkedin/restli/internal/common/URIParamUtils.java, restli-common/src/test/java/com/linkedin/restli/internal/common/TestURIMaskUtil.java, restli-int-test-client/src/test/java/com/linkedin/restli/examples/groups/TestPatchGeneration.java, restli-server/src/main/java/com/linkedin/restli/internal/server/util/ArgumentUtils.java
Fixes the following issues:
Encoding:
- Projection parameters were first encoded using default logic and then overwritten using the encoded value from URIMask encoding. Avoiding the unnecessary double encoding for projection parameters.
- During mask creation, we iterate through the entire datamap to cleanup empty masks. Since {'a': 1 } and { 'a' : { '$*': 1} } are functionally equivalent, we can avoid the extra iteration by setting $*:1.
This might increase the URI size slightly, but the chance of someone using array start/count with default values for both is going to be very low, so doing this optimization makes sense.
- During encoding a string is created for each sub datamap and then appended to the parent string builder. This is avoided by passing in the string builder to encode …
=> Improve performance of uri mask encoding and decoding

CHANGELOG.md, restli-client/src/main/java/com/linkedin/restli/client/AbstractRequestBuilder.java
We have a use case where we want a method to be able to take any type of
request builder (e.g. BatchGetRequestBuilder or FindRequestBuilder) and
we want to be able to add fields to the request.
Currently, we can accomplish this by using
setParam(RestConstants.FIELDS_PARAM, newHashSet(fields)), but it would
be simpler to just expose the addFields method instead.
=> Make addFields on AbstractRequestBuilder public.

d2-int-test/build.gradle, d2-int-test/src/test/java/com/linkedin/d2/loadbalancer/strategies/TestLoadBalancerStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/RelativeLoadBalancerTestHelper.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/ConstantErrorCountManager.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/ConstantLatencyManager.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/ConstantRequestCountManager.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/DynamicErrorCountManager.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/DynamicLatencyManager.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/DynamicRequestCountManager.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/ErrorCountCorrelation.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/ErrorCountManager.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/LatencyCorrelation.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/LatencyManager.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/LoadBalancerStrategyTestRunner.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/LoadBalancerStrategyTestRunnerBuilder.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/RequestCountCorrelation.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/framework/RequestCountManager.java
Changes include:
1. A test framework to provide different call count, latency, error rate in multiple intervals to test load balancer strategies. Users can plugin different behaviors to perform all the scenario tests.
2. The actual integration test for RelativeLoadBalancer. Some of the tests run against both relative strategy and the old degrader strategy, and verify the expected behaviors are the same.
=> D2 relative strategy integration test

d2-int-test/src/test/java/com/linkedin/d2/loadbalancer/strategies/TestLoadBalancerPerformanceSimulation.java, d2-int-test/src/test/java/com/linkedin/d2/loadbalancer/strategies/TestLoadBalancerStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/RelativeLoadBalancerStrategyFactory.java
Created a simulation test for d2 relative load balancer. The test is similar to integration test, but the purpose is different. The main purpose of this test is to give some insights on the configuration default value setup. This test focuses on using different configuration values, test the different impact to the system, including the average cluster latency.
Using the simulation, I personally prefer use highLatencyFactorThreshold = 1.3, lowLatencyFactorThreshold = 1.2 as the default, but this can be changed later after collecting more data from ServiceCallEvent.
=> Simulation test for d2 relative load balancer

src/testsuite_compatibility_matrix.md
The "Fruits" entry seems to be wrongly added, thus removing
=> Remove "Fruits" from test suite compatibility matrix as it appear to be added by mistake

gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java
Added a gradle property to skip generateRestModel task so the users can opt-in to skip.
It is useful when the user want to skip rerunning this task.
=> Add gradle property to skip generateRestModel task

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/util/ClusterInfoProvider.java, d2/src/main/java/com/linkedin/d2/balancer/util/TogglingLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/zkfs/ZKFSLoadBalancer.java, gradle.properties
ZKFSLoadBalancer and TogglingLoadBalancer were missing implementations of registerClusterListener and unregisterClusterListener, so services were never getting updates after startup.  There's a default implementation in ClusterInfoProvider for backwards compatibility reasons, but these are really required, because of how classes can be wrapped.
Unfortunately, there's no easy way to simulate a state refresh to do an end-to-end test outside of really bringing up a service. Verified fix through debugger after stack was fully constructed.
=> add missing ClusterInfoProvider implementations

scripts/update-changelog
The script was using a bash command which had different behavior on Mac.
The behavior will now be the same between Mac and Linux.
=> Make the update-changelog script Mac-compatible

d2-int-test/src/test/java/com/linkedin/d2/loadbalancer/strategies/TestLoadBalancerPerformanceSimulation.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/QuarantineManager.java
Added a test to simulate the situation when the qps is super low
Test condition:
A cluster of 20 hosts
In each interval, only send 20 requests in total
The latency range is from 100 to 500 ms, randomly generated
Test result:
When fast recovery is enabled, some hosts will drop but they will recover soon
When fast recovery is not enabled, there are several hosts that will stay at point 1 for a long time. I only ran 100 intervals, there are 4-5 hosts that stayed at point 1 for half of the intervals till the end.
=> Add test for low qps simulation

CHANGELOG.md, gradle.properties, restli-common/src/main/java/com/linkedin/restli/common/validation/RestLiDataValidator.java, restli-int-test-server/src/main/java/com/linkedin/restli/examples/greetings/server/AutomaticValidationDemoResource.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestRestLiValidation.java
Fields marked as ReadOnly will be optional for UPDATE methods.
=> Relax validation for upsert usecase: UPDATE used for create or update.

CHANGELOG.md, darkcluster/src/main/java/com/linkedin/darkcluster/impl/DarkClusterStrategyFactoryImpl.java, gradle.properties
We need to update the DarkClusterConfigMap before registering the ClusterListener in DarkClusterStrategyFactoryImpl::start. Otherwise, we get a timeout trying to update the DarkClusterConfigMap (reasons unknown). While we will investigate the timeout further, we have verified that directly calling the onClusterAdded first and then registering the ClusterListener fixes the problem. 
The ideal solution is to have registerClusterListener() function similarly to SimpleLoadBalancer.listenToCluster(), which will request the data from the eventbus, and trigger ClusterSubscriber.handlePut(), which will iterate through the ClusterListeners. Another issue will be opened to track that solution.
=> update DarkClusterConfigMap before registering ClusterListener

CHANGELOG.md, data/src/main/java/com/linkedin/data/codec/symbol/DefaultSymbolTableProvider.java, gradle.properties
Services may want to use a custom SSL socket factory for connecting to the symbol table provider on other services.
=> Provide an option to set an overridden SSL socket factory for the default symbol table provider

d2/src/main/java/com/linkedin/d2/balancer/strategies/LoadBalancerQuarantine.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/PartitionState.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/RelativeLoadBalancerStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/StateUpdater.java, d2/src/main/java/com/linkedin/d2/jmx/JmxManager.java, d2/src/main/java/com/linkedin/d2/jmx/NoOpJmxManager.java, d2/src/main/java/com/linkedin/d2/jmx/RelativeLoadBalancerStrategyJmx.java, d2/src/main/java/com/linkedin/d2/jmx/RelativeLoadBalancerStrategyJmxMBean.java, d2/src/test/java/com/linkedin/d2/jmx/RelativeLoadBalancerStrategyJmxTest.java
Adding a couple of JMX monitors for relative load balancer strategy, including
1. Standard Deviation, average absolute deviation, median absolute deviation and max absolute deviation of cluster latency.
2. Number of unhealthy hosts
3. Number of hosts in quarantine
4. Total points in the hash ring
=> Add JMX monitors for RelativeLoadBalancerStrategy

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/Facilities.java, d2/src/main/java/com/linkedin/d2/balancer/simple/AbstractLoadBalancerSubscriber.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/util/ClusterInfoProvider.java, d2/src/main/java/com/linkedin/d2/balancer/util/DelegatingFacilities.java, d2/src/main/java/com/linkedin/d2/balancer/util/TogglingLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/zkfs/ZKFSLoadBalancer.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerTest.java, darkcluster-test-api/src/main/java/com/linkedin/darkcluster/MockClusterInfoProvider.java, darkcluster/src/main/java/com/linkedin/darkcluster/impl/DarkClusterStrategyFactoryImpl.java, gradle.properties
Add a callback method for ClusterInfoProvider.getDarkClusterConfigMap.
bumping the minor version because I technically made backwards incompatible changes to the Facilities interface (by not provide a default implementation of ClusterInfoProvider) and to ClusterInfoProvider (by adding a new interface method).
Also note that I did not deprecate the old interface method; there's a bug in the jdk that is preventing me from doing that. I suspect that the deprecation suppress works across modules but not within the same module, because I didn't get the warning for the MockClusterInfoProvider, but I did get it for ZKFSLoadBalancer and TogglingLoadBalancer.
Using this callback in DarkClusterStrategyFactoryImpl solves the timeout issue in startup, verified through pulling these changes into an …
=> add callback based ClusterInfoProvider.getDarkClusterConfigMap

d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClientFactory.java, d2/src/main/java/com/linkedin/d2/balancer/config/RelativeStrategyPropertiesConverter.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerState.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerStateTest.java
Exposed a configuration in d2 client library to enable the relative load balancer. To have the relative load balancer work, client and server need to meet the following criteria:
1. Server configured the relative strategy in d2 lps file and updated to Zookeeper
2. Client upgrades the pegasus dependency version
3. Client turn on the enableRelativeLoadBalancer to true
To understand the pilot onboarding process, please see https://docs.google.com/document/d/19DpiTNuzXpdSaK-kYPRYg9RJenxJfuIy5zYX_l_1gtA/edit#heading=h.dpqigh1gl2z0
=> Create client side config to enable relative load balancer from client library

generator/src/main/java/com/linkedin/pegasus/generator/DataSchemaParser.java, generator/src/main/java/com/linkedin/pegasus/generator/TemplateSpecGenerator.java, generator/src/test/java/com/linkedin/pegasus/generator/TestPegasusDataTemplateGenerator.java, generator/src/test/resources/generator/Bar.pdl, generator/src/test/resources/generator/FooArray1.pdl, generator/src/test/resources/generator/FooArray2.pdl, generator/src/test/resources/generator/FooMap1.pdl, generator/src/test/resources/generator/FooMap2.pdl
Previous fix didn't take care the schema type of Map and Array etc. The non-consistency problem happens in the following scenario:
Suppose there are 3 PDL files, 
Foo1.pdl which has a field of array with type Bar
Foo2.pdl which also has a field of array with type Bar
This 3 schema file will generate Foo1.java Foo2.java and Bar.java and also BarArray.java
It is the annotation in the BarArray.java appeared to have non-consistency in terms appearing to have 2 different generated-by files. Sometimes it is Foo1.pdl, sometimes it is Foo2.pdl.
The solution can be multiple:
1. Just add "pushSchemaLocation" calls to put Bar.pdl location in the BarArray generated class. But this is wrong since the BarArray class should be generated by Foo1 or Foo2
2nd solution is to have the input always sorted. …
=> Fix the non-deterministic issue

.travis.yml, CHANGELOG.md, scripts/help-text/release.txt, scripts/release, scripts/travis/build.sh, scripts/travis/publish-tag.sh
This change will allow the maintainers of Rest.li to publish release
candidate versions (e.g. `1.2.3-rc.1`) from non-master branches in order
to test experimental features in a safe way as dictated by industry
convention as per the [SemVer](https://semver.org/) spec. Also cleans up the changelog a bit.
Notes:
- Changes to `scripts/release` add support and assertions for the local CLI.
- Changes to `scripts/travis/publish-tag.sh` add support on the Travis CI side.
- The change to `.travis.yml` enables deployment (i.e. bintray publishing) for RC tags.
=> Allow publishing release candidate versions

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java
Before we put extension schemas into the extensionSchema jar.
Now we would like to put the extension schemas into the same jar as base schema but under /extensions path.
=> Put extension schemas into the dataTemplate jar under /extensions path

CHANGELOG.md, gradle.properties, restli-common/src/main/java/com/linkedin/restli/common/validation/RestLiDataValidator.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestRestLiValidation.java
This fix treats `ReadOnly` required fields as optional when validating
`(BATCH)PARTIAL_UPDATE` patch inputs. Without this fix, users were unable
to perform patch set operations on record fields where the record
contains a `ReadOnly` field. Were the field included, it would fail
`ReadOnly` validation; were it omitted, it would fail since it's required.
With this fix, users can omit the field from the patch input.
**NOTE:** This PR is incomplete, as I still need to add integration tests.
=> Treat ReadOnly fields as optional in PU patches

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerState.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerStateTest.java, gradle.properties
When we applied version 29.6.0-rc.1 we found an issue at LinkedIn internal testing. The issue is that the previous code assumes each uri will create a TrackerClient object, it did not check which scheme the uri supports. In reality, when client only supports one scheme, and server host can announce to both http and https. When that happens, we should explicitly check if the uri scheme is supported by client side, if not, we should return null when getting the TrackerClient.
Testing:
1. Added unit test
2. Generated snapshot and tested in identity-mt's pcl, it passed now
=> Fixed build trackerClient bug when scheme does not match

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/ChangedFileReportTask.java, gradle.properties
Declaring an incremental task without declaring outputs is now deprecated. Declare file outputs or use TaskOutputs.upToDateWhen() instead. resolves #354
REF: https://docs.gradle.org/current/userguide/upgrading_version_5.html#declaring_an_incremental_task_without_outputs
=> Fix ChangedFileReportTask.java for gradle 6

CHANGELOG.md, d2-int-test/src/test/java/com/linkedin/d2/loadbalancer/strategies/TestLoadBalancerPerformanceSimulation.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancer.java, d2/src/test/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancerTest.java, gradle.properties
In D2ClientConfig, there are several configurations that are using a completely new config from LinkedIn global config. In order to make the configuration in sync, especially for those who are not using default d2client from container, we are made this change.
All the configs I changed in this PR are based on global-config/globals/si-pegasus.src
<property name="__r2d2DefaultClient__.r2d2Client.warmUp" value="true" /> 
<property name="__r2d2DefaultClient__.r2d2Client.warmUpConcurrentRequests" value="1" /> 
<property name="__r2d2DefaultClient__.r2d2Client.warmUpTimeoutSeconds" value="60" /> 
<property name="__r2d2DefaultClient__.r2d2Client.enableRequestTimeoutPerRequest" value="true"/> 
<w:wildcard name="^.*.useNewEphemeralStoreWatcher" …
=> Update default values in d2 client based on global config

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/resolver/ExtensionsDataSchemaResolver.java, generator/src/main/java/com/linkedin/pegasus/generator/FileFormatDataSchemaParser.java, generator/src/test/java/com/linkedin/pegasus/generator/TestDataSchemaParser.java
When we are parsing schemas from a jar, the entry from both "pegasus" and "extension" should be considered. But in the code when we check if it is "pegasus" , I use
```
entry.getName().startsWith(_schemaResolver.getSchemasDirectoryName().getName()) || isExtensionEntry(entry)
```
where the resolver will return "extension" when getSchemasDirectoryName is called. Which is an error while it should be 
```
entry.getName().startsWith("pegasus") || isExtensionEntry(entry)
```
The semantic is to say: if the entry is either started with "pegasus" or started with "extension", I will parse this entry
=> Fix a bug when check with entry prefix

CHANGELOG.md, restli-tools/src/main/java/com/linkedin/restli/tools/data/ExtensionSchemaValidationCmdLineApp.java, restli-tools/src/test/extensions/invalidExtensionAnnotation/FooExtensions.pdl, restli-tools/src/test/extensions/invalidExtensionSchemaName/FooExtend.pdl, restli-tools/src/test/extensions/invalidFieldAnnotation/FooExtensions.pdl, restli-tools/src/test/extensions/invalidFieldName/BazExtensions.pdl, restli-tools/src/test/extensions/invalidFieldType/FooExtensions.pdl, restli-tools/src/test/extensions/invalidVersionSuffix/BarExtensions.pdl, restli-tools/src/test/extensions/validCase/BarExtensions.pdl, restli-tools/src/test/extensions/validCase/FooExtensions.pdl, restli-tools/src/test/java/com/linkedin/restli/tools/data/TestExtensionSchemaValidationCmdLineApp.java, restli-tools/src/test/pegasus/Bar.pdl, restli-tools/src/test/pegasus/Baz.pdl, restli-tools/src/test/pegasus/DummyKey.pdl, restli-tools/src/test/pegasus/DummyKeyWithWrongType.pdl, restli-tools/src/test/pegasus/DummyKeyWithoutAnnotation.pdl, restli-tools/src/test/pegasus/Foo.pdl
Add following validations for extension schemas
1. The extension schema name has to follow the naming convention - 'baseSchemaName' + "Extensions"
2. The extension schema can only include base schema
3. The extension schema's fields can only be Typeref or array of Typeref
4. The extension schema's field's annotation - versionSuffix value has to match the versionSuffix value in "resourceKey" annotation.
And tests
=> Update ExtensionSchemaValidationCmdLineApp with more validations

CHANGELOG.md, data-avro/src/test/java/com/linkedin/data/avro/TestSchemaTranslator.java, gradle.properties, restli-common/src/main/java/com/linkedin/restli/common/validation/RestLiDataSchemaDataValidator.java, restli-common/src/main/java/com/linkedin/restli/common/validation/RestLiDataValidator.java, restli-server/src/main/java/com/linkedin/restli/server/validation/RestLiValidationFilter.java
There are three main changes in this PR:
- in RestLiValidatorFilter, exposes the creation of the request and response RestLiDataValidator. This will allow for other use cases that extend the RestLiValidatorFilter to override this creation and have their own implementation
- Within RestLiDataValidator, a new DataSchemaAnnotationValidator each time 'validateOutput' is called. Inside the RestLiDataSchemaDataValidator, now it creates the validator in the constructor and pass that instance along each time.
- Within RestLiDataValidator, exposes the creation of the input entity validator
Existing unit tests pass. No functionality should be changed in the PR.
=> Update RestLiValidatorFilter and RestLiDataValidator to expose creation of restli validators

CHANGELOG.md, restli-common/src/main/java/com/linkedin/restli/common/validation/RestLiDataValidator.java, restli-int-test-api/src/main/idl/com.linkedin.restli.examples.greetings.client.autoValidationDemos.restspec.json, restli-int-test-api/src/main/idl/com.linkedin.restli.examples.greetings.client.autoValidationWithProjection.restspec.json, restli-int-test-api/src/main/idl/com.linkedin.restli.examples.greetings.client.validationDemos.restspec.json, restli-int-test-api/src/main/pegasus/com/linkedin/restli/examples/greetings/api/ValidationDemo.pdl, restli-int-test-api/src/main/snapshot/com.linkedin.restli.examples.greetings.client.autoValidationDemos.snapshot.json, restli-int-test-api/src/main/snapshot/com.linkedin.restli.examples.greetings.client.autoValidationWithProjection.snapshot.json, restli-int-test-api/src/main/snapshot/com.linkedin.restli.examples.greetings.client.validationDemos.snapshot.json, restli-int-test-server/src/main/java/com/linkedin/restli/examples/greetings/server/AutomaticValidationDemoResource.java, restli-int-test-server/src/main/java/com/linkedin/restli/examples/greetings/server/AutomaticValidationWithProjectionResource.java, restli-int-test-server/src/main/java/com/linkedin/restli/examples/greetings/server/ValidationDemoResource.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestRestLiValidation.java
This change allows a `PARTIAL_UPDATE` or `BATCH_PARTIAL_UPDATE` request to
set a `ReadOnly`/`CreateOnly` field if that field is the descendant of an
array. This is needed because there's no real way to "patch" individual
array elements in Rest.li, so array patching actually sets the entire
array. Thus, users need a way to "patch" an array while maintaining the
existing values of `ReadOnly`/`CreateOnly` fields.
**Note:**
- The IDL/snapshot changes are just so I can test the logic for `CreateOnly` by adding the create-only field `bar3` inside the array in the PDL model.
- I renamed `DataValidator` to `RestLiAnnotationDataValidator` because it makes more sense, IMO.
=> Loosen validation for array-descendant patch fields

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/CheckPegasusSnapshotTask.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GeneratePegasusSnapshotTask.java, restli-tools/src/main/java/com/linkedin/restli/tools/snapshot/gen/PegasusSchemaSnapshotExporter.java, restli-tools/src/main/java/com/linkedin/restli/tools/snapshot/gen/PegasusSchemaSnapshotGenerationCmdLineApp.java, restli-tools/src/test/java/com/linkedin/restli/tools/ExporterTestUtils.java, restli-tools/src/test/java/com/linkedin/restli/tools/snapshot/gen/TestPegasusSchemaSnapshotExporter.java, restli-tools/src/test/pegasus/Location.pdl, restli-tools/src/test/pegasus/com/linkedin/restli/tools/pegasusSchemaSnapshotTest/BirthInfo.pdl, restli-tools/src/test/pegasus/com/linkedin/restli/tools/pegasusSchemaSnapshotTest/Date.pdsc, restli-tools/src/test/pegasus/com/linkedin/restli/tools/pegasusSchemaSnapshotTest/FullName.pdl, restli-tools/src/test/pegasusSchemaSnapshot/BirthInfo.pdl, restli-tools/src/test/pegasusSchemaSnapshot/Date.pdl, restli-tools/src/test/pegasusSchemaSnapshot/FullName.pdl
Add generatePegasusSchemaSnapshot task
The task will read pegasus schema files from input directory and generate snapshots of pegasus schemas.
It will be triggered if extension schema exist or if "enablePegasusSchemaCompatibilityCheck" configuration is provided.
Test: Unit test and manual test in other repos.
=> Add generatePegasusSchemeSnapshot task

CHANGELOG.md, generator/src/main/java/com/linkedin/pegasus/generator/TemplateSpecGenerator.java, gradle.properties
This enables certain techniques that use subclassing to work, such as
some using CGLib to intercept method calls.
Creating this as a follow-up to an email thread I started over the weekend.
=> Remove final from nested generated classes.

CHANGELOG.md, d2-int-test/src/test/java/com/linkedin/d2/loadbalancer/strategies/TestLoadBalancerStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/balancer/clients/BackupRequestsClient.java, d2/src/test/java/com/linkedin/d2/balancer/clients/TestBackupRequestsClient.java, gradle.properties
**Background**
Recently we found some corner cases that is causing D2 Zookeeper call taking a long time and eventually exhausted all threads. After doing some investigation, we found there are 2 places that are making blocking calls to Zookeeper:
1. TimeoutRequestClient
2. BackupRequestClient
We decided to directly deprecate the usage of TimeoutRequestClient, and change the call to be async in BackupRequestClient.
**Changes include**
1. Change the TimeoutRequestClient to be disabled by default (The actual switch is in global config which we will also turn off)
2. Exposed a config to enable the async call in BackupRequestClient.
2. Added the support to make the Zookeeper call to be async in BackupRequestClient.
=> Change D2 call to async in BackupRequestClient

CHANGELOG.md, degrader/src/main/java/com/linkedin/util/degrader/DegraderImpl.java, degrader/src/test/java/com/linkedin/util/degrader/TestDegrader.java, gradle.properties
There are complaints from service owners that DegraderImpl LoggerFactory.getLogger is taking long time, and the call occurs very frequently that may impact client side performance. After looking into the code, I found that whenever we instantiate a new ImmutableConfig in DegraderImpl, we will call LoggerFactory.getLogger once to get the default value for the logger. This change will create a static variable for the default logger.
=> Optimize logger in degrader load balancer

CHANGELOG.md, generator/src/main/java/com/linkedin/pegasus/generator/DataSchemaParser.java, generator/src/main/java/com/linkedin/pegasus/generator/FileFormatDataSchemaParser.java
This is meant to replace PR #416 
PR #376 made schema parsing deterministic in part by sorting parser
results. When using `DataSchemaParser` to parse data schemas from multiple
sources, a separate `ParseResult` instance is constructed for each source
then ultimately combined into a new singular instance. This introduced a
performance regression when parsing from many sources due to unnecessary
sorting. This change fixes that by allowing `FileFormatDataSchemaParser`
to reuse the root instance rather than constructing a new one.
Also adds more comments for clarity.
=> Optimize schema parsing by reusing ParseResult instances

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/jmx/DegraderLoadBalancerStrategyV3Jmx.java, d2/src/main/java/com/linkedin/d2/jmx/DegraderLoadBalancerStrategyV3JmxMBean.java, d2/src/main/java/com/linkedin/d2/jmx/RelativeLoadBalancerStrategyJmx.java, gradle.properties
- Add relative strategy monitoring metrics in DegraderLoadBalancerStrategyV3Jmx
- It is a safe practice to ensure relative strategy works correctly before broader roll-out.
- Also a useful tool for tuning relative factor based on degrader strategy performance.
=> Add monitoring metrics for relative strategy in DegraderLoadBalancerStrategyV3Jmx

d2-int-test/src/test/java/com/linkedin/d2/loadbalancer/strategies/TestLoadBalancerStrategy.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/StateUpdaterTest.java, restli-int-test/src/test/java/com/linkedin/restli/client/multiplexer/TestMultiplexerIntegration.java
Adds retries to a couple D2 tests and improves a Multiplexer unit test to be tolerant of failures in CI.
This is motivated by the recent high rate of flaky tests in CI.
=> Address a few flaky tests

CHANGELOG.md, data/src/main/java/com/linkedin/data/collections/CheckedMap.java, data/src/main/java/com/linkedin/data/template/RecordTemplate.java, data/src/main/java/com/linkedin/data/template/UnionTemplate.java, generator/src/main/java/com/linkedin/pegasus/generator/JavaDataTemplateGenerator.java, gradle.properties
The changes in this PR are backwards incompatible with the changes introduced in 29.7.0 (and 29.7.1). Both these versions have the [GC issue](http://squeakytech.blogspot.com/2015/10/lambda-expressions-events-and-weak.html#:~:text=What%20happens%20when%20you%20store,Your%20assumption%20may%20be%20wrong) and should be deprecated.
=> Move from lambdas to explicit change listeners since lambda garbage collection is unreliable in Java

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/compatibility/CompatibilityMessage.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/FileCompatibilityType.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PropertyUtil.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/SharedFileUtils.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/CheckPegasusSnapshotTask.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/CheckRestModelTask.java, restli-tools/src/main/java/com/linkedin/restli/tools/snapshot/check/PegasusSchemaSnapshotCompatibilityChecker.java, restli-tools/src/test/java/com/linkedin/restli/tools/snapshot/check/TestPegasusSchemaSnapshotCompatibilityChecker.java, restli-tools/src/test/pegasusSchemaSnapshot/compatibleSchemaSnapshot/BirthInfo.pdl, restli-tools/src/test/pegasusSchemaSnapshot/currSnapshot/BirthInfo.pdl, restli-tools/src/test/pegasusSchemaSnapshot/currSnapshot/com.linkedin.test.BirthInfo.pdl, restli-tools/src/test/pegasusSchemaSnapshot/incompatibleSchemaSnapshot/BirthInfo.pdl, restli-tools/src/test/pegasusSchemaSnapshot/prevSnapshot/BirthInfo.pdl, restli-tools/src/test/pegasusSchemaSnapshot/prevSnapshot/com.linkedin.test.Date.pdl
checkPegasusSchemaSnapshotTask is used to check the pegasus schema's compatibility.
The check is based on the snapshots(.pdl files) which are generated in generatePegasusSchemaSnapshotTask.
=> Add checkPegasusSchemaSnapshotTask

generator/src/main/java/com/linkedin/pegasus/generator/DataSchemaParser.java, generator/src/test/java/com/linkedin/pegasus/generator/TestDataSchemaParser.java
This is for parsing result easy to get base schema. when both extension and base schemas are in the resolver path.
=> Add method in ParseResult class to get base schema

CHANGELOG.md, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/records/WithSpecialFieldsRecord.pdl, generator/src/main/java/com/linkedin/pegasus/generator/JavaDataTemplateGenerator.java, gradle.properties
The code generator generates a private member variable per field with the name of the field prefixed by an underscore. If a record field is named "fields", this conflicts with the static member variable of the same name that is generated in each record class.
=> Fix bug affecting record fields named "fields".

CHANGELOG.md, data/src/main/java/com/linkedin/data/Data.java, data/src/main/java/com/linkedin/data/DataComplexIdentitySet.java, data/src/main/java/com/linkedin/data/DataMap.java, data/src/main/java/com/linkedin/data/codec/ProtobufCodecOptions.java, data/src/main/java/com/linkedin/data/codec/ProtobufDataCodec.java, data/src/main/java/com/linkedin/data/codec/entitystream/ProtobufDataEncoder.java, data/src/test/java/com/linkedin/data/TestDataComplexIdentitySet.java, gradle.properties, li-protobuf/src/main/java/com/linkedin/data/protobuf/ProtoWriter.java
Use an identity hashset implementation that uses DataComplex#dataComplexHashCode under the hood for better performance when detecting cycles
=> Add an option to configure ProtoWriter buffer size. Set the default to 4096 to prevent thrashing

CHANGELOG.md, generator-test/src/test/java/com/linkedin/pegasus/generator/test/pdl/WithCustomTypeDefaultsTest.java, generator-test/src/test/java/com/linkedin/pegasus/generator/test/pdl/fixtures/WithCustomTypeDefaultsCustomInt.java, generator-test/src/test/java/com/linkedin/pegasus/generator/test/pdl/fixtures/WithCustomTypeDefaultsCustomIntCoercer.java, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/records/WithCustomTypeDefaults.pdl, generator/src/main/java/com/linkedin/pegasus/generator/JavaDataTemplateGenerator.java, gradle.properties
The new static DEFAULT_ fields that are code generated need to reference
coercers that might not be initialized until a subsequent static block.
All that is required to fix this is to reorder those statements, but it
does not seem possible with JCodeModel. What we can do instead is break
up the declaration from the initialization and order the assignment and
coercer registration statements the way we want to within a single init
block.
The generated code now looks like:
private static final T DEFAULT_field;
static {
Custom.initializeCustomClass(T.class);
Custom.initializeCoercerClass(...);
DEFAULT_field = ...;
}
=> Fix bug referring to coercer before registration.

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/annotation/AnnotationCheckResolvedPropertiesVisitor.java, data/src/main/java/com/linkedin/data/schema/annotation/IdentitySchemaVisitor.java, data/src/main/java/com/linkedin/data/schema/annotation/SchemaAnnotationHandler.java, data/src/main/java/com/linkedin/data/schema/annotation/SchemaAnnotationProcessor.java, data/src/main/java/com/linkedin/data/schema/compatibility/AnnotationCompatibilityChecker.java, data/src/main/java/com/linkedin/data/schema/compatibility/CompatibilityMessage.java, data/src/test/java/com/linkedin/data/schema/compatibility/TestAnnotationCompatibilityChecker.java, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/TestSchema1.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/TestSchema2.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/TestSchema3.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/TestSchema4.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/TestSchema1.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/TestSchema2.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/TestSchema3.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/TestSchema4.pdl, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/SchemaAnnotationHandlerClassUtil.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/internal/CompatibilityLogChecker.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/CheckPegasusSnapshotTask.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/ValidateSchemaAnnotationTask.java, restli-tools/src/main/java/com/linkedin/restli/internal/tools/ClassJarPathUtil.java, restli-tools/src/main/java/com/linkedin/restli/tools/annotation/SchemaAnnotationValidatorCmdLineApp.java, restli-tools/src/main/java/com/linkedin/restli/tools/compatibility/CompatibilityInfoMap.java, restli-tools/src/main/java/com/linkedin/restli/tools/compatibility/CompatibilityReport.java, restli-tools/src/main/java/com/linkedin/restli/tools/idlcheck/CompatibilityInfo.java, restli-tools/src/main/java/com/linkedin/restli/tools/snapshot/check/PegasusSchemaSnapshotCompatibilityChecker.java
Extend checkPegasusSchemaSnapshot task to be enable to check schema annotation compatibility, if SchemaAnnotationHandler is provided.
1. Update SchemaAnnotationHandler interface to have new api - annotationCompatibilityCheck, which can be used to check the custom annotation compatibility check
2. Create a new SchemaVisitor - AnnotationCheckResolvedPropertiesVisitor, which is to get a map of node in a schema to it's resolvedProperties. It can be used to check the annotation compatibility for olderResolvedProperties and newerResolvedProperties.
3. AnnotationCompatibilityChecker which leverages the annotation processor to check the compatibilities of annotation changes.
Test:
Unit tests
Manual test in sample repos.
=> Extend checkPegasusSchemaSnapshot task to be able to check schema annotation compatibility

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/RelativeLoadBalancerStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/StateUpdater.java, d2/src/main/java/com/linkedin/d2/jmx/RelativeLoadBalancerStrategyJmx.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/StateUpdaterTest.java, d2/src/test/java/com/linkedin/d2/jmx/RelativeLoadBalancerStrategyJmxTest.java, gradle.properties
**Background**
For relative load balancer onboarding, we're trying to find different type of services to onboard, one type is services with partitions. However, one problem with today's inGraph is that we always emit metrics for partition 0, it turns out one of the client that I'm onboarding, they only talk to partition 1, they never talk to partition 0.
To perfectly solve this problem, I think we should fire one inGraph for each partition, however, it's really hard since at inGraph registration time, we do not know how many partitions are there, partitions can be very dynamic. So the trick here is to always emit metrics for the 1st added partition, so that at least we have some meaningful data.
**Changes include**
1. Emit metrics for the first added partition
2. Add a small debug log …
=> Add partition support in relative load balancer inGraph

CHANGELOG.md, data/src/main/java/com/linkedin/data/ByteString.java, data/src/main/java/com/linkedin/data/Data.java, data/src/main/java/com/linkedin/data/DataList.java, data/src/main/java/com/linkedin/data/DataMap.java, data/src/main/java/com/linkedin/data/codec/AbstractJacksonDataCodec.java, data/src/main/java/com/linkedin/data/codec/DataCodec.java, data/src/main/java/com/linkedin/data/codec/ProtobufDataCodec.java, data/src/main/java/com/linkedin/data/codec/entitystream/AbstractDataEncoder.java, data/src/main/java/com/linkedin/data/collections/CheckedList.java, data/src/main/java/com/linkedin/data/collections/CheckedMap.java, data/src/main/java/com/linkedin/data/template/WrappingArrayTemplate.java, data/src/main/java/com/linkedin/data/template/WrappingMapTemplate.java, data/src/main/java/com/linkedin/util/FastByteArrayOutputStream.java, data/src/test/java/com/linkedin/data/TestData.java, data/src/test/java/com/linkedin/data/codec/TestCodec.java, data/src/test/java/com/linkedin/data/template/TestArrayTemplate.java, data/src/test/java/com/linkedin/data/template/TestMapTemplate.java, generator-test/src/test/java/com/linkedin/pegasus/generator/override/TestCustomAnyRecord.java, generator-test/src/test/java/com/linkedin/pegasus/generator/test/TestCustomAnyRecord.java, gradle.properties, restli-client/src/main/java/com/linkedin/restli/client/RestClient.java, restli-client/src/test/java/com/linkedin/restli/client/TestClientBuilders.java, restli-server/src/main/java/com/linkedin/restli/internal/server/response/ResponseUtils.java, restli-server/src/main/java/com/linkedin/restli/internal/server/util/DataMapUtils.java, restli-server/src/main/java/com/linkedin/restli/server/multiplexer/MultiplexedRequestHandlerImpl.java, restli-server/src/test/java/com/linkedin/restli/server/multiplexer/TestMultiplexedRequestHandlerImpl.java
Minimize memory copies and object creation during encoding
Use String switch instead of map lookup in traverse callback for better performance
Reset isTraversing when cloning
Cache data objects in wrapped mapped/lists lazily on get
Compute dataComplexHashCode lazily for DataList and DataMap
=> Minimize memory copies and object creation during encoding

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/annotation/AnnotationCheckResolvedPropertiesVisitor.java, data/src/main/java/com/linkedin/data/schema/annotation/ExtensionSchemaAnnotationHandler.java, data/src/main/java/com/linkedin/data/schema/compatibility/AnnotationCompatibilityChecker.java, data/src/test/java/com/linkedin/data/schema/compatibility/TestAnnotationCompatibilityChecker.java, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/AlbumExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/BookExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/CompanyExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/FooExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/FruitExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/IdentityExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/JobExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/SchoolExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/TestSchema5.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/currentSchema/TestSchema6.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/AlbumExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/BookExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/CompanyExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/FooExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/FruitExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/IdentityExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/JobExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/SchoolExtensions.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/TestSchema5.pdl, data/src/test/resources/com/linkedin/data/schema/compatibility/previousSchema/TestSchema6.pdl, restli-tools/src/main/java/com/linkedin/restli/tools/data/ExtensionSchemaValidationCmdLineApp.java, restli-tools/src/main/java/com/linkedin/restli/tools/snapshot/check/PegasusSchemaSnapshotCompatibilityChecker.java
Add ExtensionSchemaAnnotationHandler for extension schema annotation compatibility check.
The new handler implements 'checkCompatibility' method, which introduces specific rules for extension annotation compatibility check.
Test:
unit tests
manual test.
=> Add ExtensionSchemaAnnotationHandler 

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties
Set javac source and target compatibility of dataTemplate compile task to "1.8" as the cogen changes in 29.7.0 is using Java 8 features.
=> Set source compatibility on data template compile task.

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/PartitionState.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/RelativeLoadBalancerStrategyFactory.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/StateUpdater.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/StateUpdaterTest.java, gradle.properties
Improve the relative load balancer log:
1. Adding service name, otherwise we do not know which service has changed the degrader score
2. Limiting the size of the recovery map and quarantine map, removed points map. Otherwise for a cluster of hundreds of machines, one entry of log will be too big.
=> [Relative Load Balancer] Improve log

CHANGELOG.md, gradle.properties
This PR doesn't do anything, it only bump the minor version of pegasus.
Why do we need this?
I need this for LinkedIn HI preparation. For the HI to onboard to relative load balancer, the prerequisites is to have all the mps using a certain container version and a certain pegasus version. To reduce the effort of asking everyone to bump the pegasus version, we want container to give an error when clients downgrade the pegasus version, and we agreed with SF team that the downgrade error will happen on a minor version downgrade. Therefore, I'm upgrading the minor version and will use this version in the container.
=> Empty commit to bump minor version

restli-tools/src/main/java/com/linkedin/restli/tools/data/SchemaFormatTranslator.java
**Issue**:
Unit tests do not pass when I run unit tests on my mac system.
**Repro**:
Run the following command off the "master" branch on both Mac and Linux
systems.
./gradlew :restli-tools:test --tests com.linkedin.restli.tools.data.TestSchemaFormatTranslator --rerun-tasks
Running the test will pass on the Linux system but will fail on the
LinkedIn Mac system.
different canonical and absolute paths.
The 2 element in the if stmt below is the culprit.
In SchemaFormatTranslator#getTopLevelSchemaToTranslatedSchemaMap,
if (!location.getSourceFile().getAbsolutePath().endsWith(_sourceFormat) ||
!location.toString().startsWith(_sourceDir.getAbsolutePath()) ||
!isTopLevelSchema(schema, location))
On my mac system, I get the following values at if stmt above.
location.toString: …
=> Fix bug in SchemaFormatTranslator that caused files to be skipped on a Mac system.

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties
Fix bug: 
If there is no input schema, do not run pegasusSchemaSnapshotCheck. The check statement was wrong.
=> Fix bug: if there is no input schema, do not run pegasusSchemaSnapshotCheck

CHANGELOG.md, gradle.properties, restli-common/src/main/java/com/linkedin/restli/common/RestConstants.java, restli-server/src/main/java/com/linkedin/restli/server/symbol/RestLiSymbolTableRequestHandler.java, restli-server/src/test/java/com/linkedin/restli/server/TestRestLiSymbolTableRequestHandler.java, restli-tools/src/main/java/com/linkedin/restli/tools/symbol/RestLiSymbolTableProvider.java, restli-tools/src/test/java/com/linkedin/restli/tools/symbol/TestRestLiSymbolTableProvider.java
We have a client who adds suffix to the request path.
Given an application named `foo` and a resource with `bar`
```
@RestLiCollection(name = "bar", namespace = "com.foo")
```
they want to support a d2 URL such as
```
d2://foo?action=...
```
the resolved url becomes
```
some-host.com/foo/bar?action=...
```
When we enable protobuf for them, the `RestLiSymbolTableRequestHandler` sees
```
some-host.com/foo/bar/symbolTable
some-host.com/foo/bar/symbolTable/<tableName>
```
In this PR, we are adding support to check the last 2 arguments given a path.
To prevent naming collision and backwards compatibility, we are guarding the
logic behind a header
=> Support symbolTable requests with suffixes

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/compatibility/CompatibilityChecker.java, data/src/main/java/com/linkedin/data/schema/compatibility/CompatibilityOptions.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties, restli-tools/src/test/java/com/linkedin/restli/tools/snapshot/check/TestPegasusSchemaSnapshotCompatibilityChecker.java, restli-tools/src/test/pegasusSchemaSnapshot/Foo.pdl, restli-tools/src/test/pegasusSchemaSnapshot/compatibleSchemaSnapshot/Foo.pdl
Adding an enum in CompatibilityOptions.Mode - EXTENSION to allow adding required record field in extension schemas.
The previous PR was closed accidentally, since I forced to update the branch it does not allow me to reopen the PR. Therefore create a new PR.
=> Adding required record field is allowed and should be considered as backward compatible change in extension schemas

CHANGELOG.md, generator/src/main/java/com/linkedin/pegasus/generator/CaseSensitiveFileCodeWriter.java, generator/src/main/java/com/linkedin/pegasus/generator/JavaCodeUtil.java, generator/src/main/java/com/linkedin/pegasus/generator/PegasusDataTemplateGenerator.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateDataTemplateTask.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateRestClientTask.java, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java, restli-tools/src/test/java/com/linkedin/restli/tools/clientgen/TestRestRequestBuilderGenerator.java, restli-tools/src/test/resources/idls/arrayDuplicateA.namespace.restspec.json, restli-tools/src/test/resources/idls/arrayDuplicateB.namespace.restspec.json
Issue:
Was working on two different file systems and noticed that after a rync,
I was getting a "DuplicateClassException" on my Linux system - there
were duplicate files in similar paths.
Typically a Mac/Windows system will have a case insensitive file system,
whereas a Linux system will have a case sensitive file system. For a
case insensitive file system, "~/com/astro" and "~/com/ASTRO" point to
the same folder. For a case sensitive file system, "~/com/astro" and
"~/com/ASTRO" will be different folders.
Example:
File1: namespace = com.astro.file1
File2: namespace = com.aSTRo.file2
The following files would be generated with the path specified.
1) Case insensitive (if file1 is generated first):
com/astro/file1
/file2
2) Case insensitive (if file2 is generated first):
com/aSTRo/file1 …
=> Update generators to optionally generate files with lower case path.

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/clients/DegraderTrackerClientImpl.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClient.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClientFactory.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClientImpl.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/StateUpdater.java, d2/src/test/java/com/linkedin/d2/balancer/clients/TrackerClientTest.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/StateUpdaterTest.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/TrackerClientMockHelper.java, gradle.properties
**Background**
In the existing degrader load balancer, we have one special logic about Dyno tests: When a dyno test is started, they will explicitly indicate uriProperties "doNotSlowStart" for the uri, so that when a host's weight is adjusted in Zookeeper, it does not perform any slow start. However, I just realized the same feature is not added to relative load balancer. Hence this PR will add the parity.
=> [Relative Load Balancer] Add parity of do not slow start in Dyno test

CHANGELOG.md, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/symbol/RestLiSymbolTableProvider.java, restli-tools/src/test/java/com/linkedin/restli/tools/symbol/TestRestLiSymbolTableProvider.java
- Return null if uri prefix doesn't match. 
- If the fetch call 404s internally store an empty symbol table and return null. This will avoid repeated invocations to services that are not yet ready to support symbol tables
=> Enhance request symbol table fetch

CHANGELOG.md, data/src/main/java/com/linkedin/data/Data.java, data/src/main/java/com/linkedin/data/DataList.java, data/src/main/java/com/linkedin/data/DataMap.java, gradle.properties
This is to avoid severe performance degradation at high QPS due to ThreadLocal slowdown.
See: https://jira.atlassian.com/browse/JRASERVER-71058 for a similar issue.
=> Enable cycle check when serializing only when assertions are enabled.

CHANGELOG.md, data/src/main/java/com/linkedin/data/codec/symbol/DefaultSymbolTableProvider.java, restli-common/src/main/java/com/linkedin/restli/common/RestConstants.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/RestLiApiBuilder.java, restli-server/src/main/java/com/linkedin/restli/server/symbol/RestLiSymbolTableRequestHandler.java, restli-server/src/test/java/com/linkedin/restli/internal/server/model/SampleResources.java, restli-server/src/test/java/com/linkedin/restli/internal/server/model/TestRestLiApiBuilder.java, restli-server/src/test/java/com/linkedin/restli/server/TestRestLiSymbolTableRequestHandler.java, restli-tools/src/main/java/com/linkedin/restli/tools/symbol/RestLiSymbolTableProvider.java, restli-tools/src/test/java/com/linkedin/restli/tools/symbol/TestRestLiSymbolTableProvider.java
1. Throw error in API builder if Resource name conflicts with "symbolTable"
2. Add symbol-table-request header for requesting symbol table to avoid conflict with resource requests.
=> Reserve symbol table resource name

CHANGELOG.md, build.gradle
This should resolve some classloader issues introduced in
javax.activation code with java 11.
=> Bump javax.mail:mail to 1.4.4

CHANGELOG.md, data-avro/src/main/java/com/linkedin/data/avro/util/AvroUtil.java, gradle.properties
Change AvroUtil.genericRecordFromJson to use newCompatibleJsonDecoder so that the json -> avro reader can read json converted by any version of avro.
Bump minor version in case this version will be used in avro HI
=> Change AvroUtil to use newCompatibleJsonDecoder from avro-util

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/UnionDataSchema.java, data/src/main/java/com/linkedin/data/schema/validation/ValidateDataAgainstSchema.java, data/src/test/java/com/linkedin/data/schema/validation/TestValidation.java, gradle.properties, restli-common/src/main/java/com/linkedin/restli/common/util/ProjectionMaskApplier.java, restli-int-test-api/src/main/idl/com.linkedin.restli.examples.greetings.client.emptyUnion.restspec.json, restli-int-test-api/src/main/pegasus/com/linkedin/restli/examples/greetings/api/ValidateEmptyUnion.pdl, restli-int-test-api/src/main/snapshot/com.linkedin.restli.examples.greetings.client.emptyUnion.snapshot.json, restli-int-test-server/src/main/java/com/linkedin/restli/examples/greetings/server/ValidateEmptyUnionResource.java, restli-int-test-server/src/test/java/com/linkedin/restli/docgen/TestResourceSchemaCollection.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestEmptyUnionValidation.java
Before this fix, the RestLiValidationFilter will allow empty union to pass, i.e if there is a union that is an empty map, when doing the validation. 
That is too wide open and risky. So this fix, change it  restricted only when a projection is specified in the union.
=> Fix empty union validation to only allow validation pass when projection in union is present

src/pdsc_syntax.md
tried to navigate and couldn't. 
links in outline use `_` while H2 `id`s generated have `-`.
=> fix internal links in outline

CHANGELOG.md, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/snapshot/gen/PegasusSchemaSnapshotExporter.java
This PR is a fix to remove extra whitespace at the end of the line in the pegasus schema snapshot files.
Test: generated snapshot and tested against dr-restaurants mp.
=> Fix extra whitespace at the end of the line in the pegasus schema snapshot files

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/AbstractSchemaParser.java, data/src/main/java/com/linkedin/data/schema/DataSchemaResolver.java, data/src/main/java/com/linkedin/data/schema/resolver/AbstractMultiFormatDataSchemaResolver.java, data/src/test/java/com/linkedin/data/schema/generator/TestAbstractGenerator.java, data/src/test/java/com/linkedin/data/schema/resolver/TestDataSchemaResolver.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/TranslateSchemasTask.java, gradle.properties
Improve logging when conflicts are detected during parsing. Message now specifies the location of the conflict instead of printing the schema. Having the location is more useful to resolve conflict errors.
=> Update translate schemas task to look in the input folder first when resolving schemas.

CHANGELOG.md, generator-test/src/test/java/com/linkedin/data/schema/generator/TestPegasusDataTemplateGenerator.java, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/unnamed/SimpleArray.pdl, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/unnamed/UnionNameConflict.pdl, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/unnamed/UnionNameConflictArray.pdl, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/unnamed/UnionNameConflictMap.pdl, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/unnamed/records/Simple.pdl, generator/src/main/java/com/linkedin/pegasus/generator/TemplateSpecGenerator.java, gradle.properties
Java doesn't allow inner class names to be same as enclosing classes. Detect and resolve such naming conflicts for unnamed inner types(array, map and union).
=> Detect and resolve naming conflits for unnamed inner types(array, map and union).

CHANGELOG.md, restli-server/src/main/java/com/linkedin/restli/internal/server/model/RestLiAnnotationReader.java, restli-server/src/test/java/com/linkedin/restli/internal/server/model/SampleResources.java, restli-server/src/test/java/com/linkedin/restli/internal/server/model/TestRestLiApiBuilder.java
Fix incorrect behavior for validating the `@PathKeyParam` method parameter annotation. This resulted in a build failure if specifying a path key from the current resource (rather than a parent resource). This makes the behavior consistent with the `@PathKeysParam` annotation.
For example, without this bug fix the following fails:
```
@RestLiCollection(name = "foo")
class FooResource implements KeyValueResource<Long, EmptyRecord>
{
@Action(name = "doSomething", resourceLevel = ResourceLevel.ENTITY)
public void doSomething(@PathKeyParam("fooId") Long id) {}
}
```
...Because the logic to validate the key name attribute inside `@PathKeyParam` iterates over the resource up through all its parents and super-parents, starting with the _first parent_ rather than _the resource itself_.
=> Allow using PathKeyParam for non-parent path keys

CHANGELOG.md, restli-server/src/main/java/com/linkedin/restli/internal/server/filter/FilterRequestContextInternalImpl.java, restli-server/src/main/java/com/linkedin/restli/server/filter/FilterRequestContext.java, restli-server/src/test/java/com/linkedin/restli/internal/server/filter/TestFilterRequestContextInternalImpl.java
The interface has a default implementation for now to keep it
compatible, but that should be removed in the next major version.
=> Expose resource method parameters in FilterRequestContext

CHANGELOG.md, data/src/main/java/com/linkedin/data/DataComplexTable.java, data/src/test/java/com/linkedin/data/TestData.java, data/src/test/java/com/linkedin/data/TestDataComplexTable.java, gradle.properties
Hashcodes for DataComplex objects are generated using a thread local,
and there can be collisions if multiple threads are used to construct a
DataComplex object.
=> Fix bug in DataComplexTable that breaks Data::copy if there are hash collisions.

gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java
- Invoking Configuration#isEmpty() will force the underlying Configuration to resolve all files - this is bad and can break native IDEA project import
- Rather, we can see if the Configuration has any first-order dependencies associated with it, which is probably the author's original intent
- If the Configuration exists and contains any first-order dependencies, only then should we warn.
=> [bugfix] Prevent eager resolution of UNUSED_CONFIGURATIONS values

CHANGELOG.md, restli-common/src/main/java/com/linkedin/restli/common/validation/CreateOnly.java, restli-common/src/main/java/com/linkedin/restli/common/validation/ReadOnly.java
Update CreateOnly and ReadOnly javadocs to be more accurate that the validation is performed by RestLiValidationFilter.
=> Update CreateOnly and ReadOnly javadocs to be more accurate.

CHANGELOG.md, data/src/main/java/com/linkedin/data/collections/CheckedMap.java, data/src/main/java/com/linkedin/data/schema/validator/DataSchemaAnnotationValidator.java, data/src/test/java/com/linkedin/data/collections/TestCheckedMap.java, data/src/test/java/com/linkedin/data/collections/TestCheckedUtil.java, gradle.properties
Change listener list now clears finalized weak references when it detects any change listener was finalized or when listeners are notified.
=> Fix memory leak in CheckedMap when one map is used to create multiple record templates.

CHANGELOG.md, gradle.properties, r2-core/src/main/java/com/linkedin/r2/filter/transport/ClientRetryFilter.java
In the original implementation, the original exception is discarded and replaced with RetriableRequestException. This will lose the error type and error status code, causing D2 degrader to disfunction.
The fix is to preserve the original error type, and wrap a RetriableRequestException inside the cause.
=> Fix a bug of losing HTTP status code when a retriable response goes through ClientRetryFilter

CHANGELOG.md, data/src/main/java/com/linkedin/data/codec/AbstractJacksonDataCodec.java, data/src/main/java/com/linkedin/data/schema/CompactPdlBuilder.java, data/src/main/java/com/linkedin/data/schema/IndentedPdlBuilder.java, data/src/main/java/com/linkedin/data/schema/PdlBuilder.java, data/src/main/java/com/linkedin/data/schema/SchemaToPdlEncoder.java, data/src/test/java/com/linkedin/data/schema/TestPdlBuilder.java, data/src/test/java/com/linkedin/data/schema/TestSchemaToPdlEncoder.java, gradle.properties
The PDL encoder already sorts the top-level properties on a field by
their names. This extends this sorting to nested properties.
An example of a nested property that is sorted is:
@nested = {
"a" : "a",
"b" : "b"
}
When default values are records, their fields are sorted in the order
that the fields are defined in the schema. For example:
date: record Date {
month: int
day: int
year: int
} = {
"month": 1,
"day": 1,
"year": 2021
}
This enables the PDL encoder to be used for autoformatting PDLs, since
the order of map entries will be deterministic.
=> Sort properties and defaults when encoding PDLs.

scripts/release
Simple improvement for Rest.li maintainers.
=> Add Travis CI link to output of release job script

CHANGELOG.md, data-transform/src/main/java/com/linkedin/data/transform/filter/request/MaskCreator.java, data-transform/src/test/java/com/linkedin/data/transform/filter/TestMaskCreation.java, data/src/main/java/com/linkedin/data/schema/PathSpec.java, data/src/main/java/com/linkedin/data/schema/PathSpecSet.java, data/src/test/java/com/linkedin/data/schema/TestPathSpec.java, data/src/test/java/com/linkedin/data/schema/TestPathSpecSet.java
The PathSpecSet provides functionalities to more easily build or edit a set of PathSpec. In addition, it offers the support for a full projection so that methods like "contains" always return true making it easier for the client code to write logic with the set.
=> Add PathSpecSet: a set of PathSpecSet with support for full projection

CHANGELOG.md, gradle.properties, r2-filter-compression/src/main/java/com/linkedin/r2/filter/compression/ClientCompressionFilter.java, r2-filter-compression/src/main/java/com/linkedin/r2/filter/compression/ClientStreamCompressionFilter.java, r2-int-test/src/test/java/test/r2/integ/clientserver/TestStreamResponseCompression.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/HttpClientFactory.java
Always enable client compression filter so that responses can be decompressed. If the request already has an accept encoding header set do not overwrite it
=> Compression filter changes

CHANGELOG.md, data/src/main/java/com/linkedin/data/template/UnionTemplate.java, data/src/test/java/com/linkedin/data/template/TestRecordAndUnionTemplate.java, gradle.properties
New function for UnionTemplate to directly reeturn the key name for a
given union member.
./gradlew :data:build
BUILD SUCCESSFUL in 47s
21 actionable tasks: 21 executed
=> Add UnionTemplate.memberKeyName()

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/clients/RetryClient.java, gradle.properties, r2-core/src/main/java/com/linkedin/r2/filter/transport/ServerRetryFilter.java
Suppose A sends request to B, and B sends request to C. When C is overloaded, B will retry its requests on C. If all of the retry attempts failed, the error will be propagated back to A. But we would like to prevent the RetriableRequestException from C from cascading to the indirect caller A, and therefore, we need to disable retry at B in this case.
=> Prevent RetriableRequestException from cascading to the indirect caller

CHANGELOG.md, restli-server/src/main/java/com/linkedin/restli/internal/server/response/ResponseUtils.java, restli-server/src/main/java/com/linkedin/restli/server/StreamRestLiServer.java, restli-server/src/test/java/com/linkedin/restli/internal/server/response/TestResponseUtils.java
This PR is to fix restli-client side decoding of error response data map failure, when restli server returns error data for stream requests.
=> [rest.li] Fix content type header not set in case of StreamException from rest.li server

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/generator/DefaultSampleDataCallback.java, generator-test/src/test/java/com/linkedin/data/schema/generator/TestSchemaSampleDataGenerator.java, gradle.properties
Doc gen did not handle the case that if resource key is an enum type without any symbols. Enum without symbols is a valid use case. This PR is fixing this issue.
Test:
Unit test.
=> Fix bug that if the schema is an enum without any symbols, doc gen should handle it rather than throwing exception.

CHANGELOG.md, gradle.properties, restli-server/src/main/java/com/linkedin/restli/internal/server/util/MIMEParse.java, restli-server/src/test/java/com/linkedin/restli/internal/server/util/TestMIMEParse.java, restli-server/src/test/java/com/linkedin/restli/internal/server/util/TestRestUtils.java
Rest.li is setting the response `content-type` based on the best matching `accept` mime type. However it only sets the base mime type while ignoring any mime type parameters. If a mime type parameter is malformed, it is silently ignored.
Changes:
* Include mime type params when setting the response content type
* Throw an InvalidMimeTypeException when there are invalid params in the accept header.
=> Include mime type params when setting the response content-type

CHANGELOG.md, gradle.properties, restli-server/src/main/java/com/linkedin/restli/internal/server/response/ErrorResponseBuilder.java
In previous changes, we add error logs to 2xx and 3xx status where an exception is thrown from the servers to tell developers that this is anti-pattern. But sometimes there is a blurred boundary in the category of 3xx. (Which is mostly for redirect traffic) 
The added error logs propagated to the client side and causing some excessive and troubled client to judge poorly. (Because we added more information to the log) 
Thus I exclude 3xx from adding the error log to help them.
=> Exclude 3xx status from logging errors

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/balancer/clients/RetryClient.java, d2/src/test/java/com/linkedin/d2/balancer/clients/RetryClientTest.java, gradle.properties
The current implementation of RetryClient will buffer every single incoming StreamRequest regardless of its entity stream size, which could potentially cause memory issues. Therefore, we would like to disable client retry for stream request by default. We will be adding two separate configs to control restRetry (enable by default) and streamRetry (disable by default).
=> Add separate configuration control for retrying RestRequest and StreamRequest

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/PartitionState.java, gradle.properties
There is a report from user that UnmodifiableList.forEach stack is unreasonably long: https://harrier.tools.corp.linkedin.com/#/lnkd-services/profiler/event/21019?isAsyncProfiler=true&metric=count
After taking a look, I found that I wrap an UnmodifiableList again and again in the code, each UnmodifiableList points to another UnmodifiableList, hence fix it in the PR.
This method is how I create a new PartitionState and wraps the UnmodifiableList:
PartitionState (PartitionState oldPartitionState)
{
this(oldPartitionState.getPartitionId(),
oldPartitionState.getRingFactory(),
oldPartitionState.getPointsPerWeight(),
new HashSet<>(oldPartitionState.getRecoveryTrackerClients()),
oldPartitionState.getClusterGenerationId(),
new HashMap<>(oldPartitionState.getQuarantineMap()),
new …
=> Fix d2 unmodifiable list

CHANGELOG.md, gradle.properties, restli-int-test-api/src/main/idl/com.linkedin.restli.examples.defaults.api.fillInDefaults.restspec.json, restli-int-test-api/src/main/pegasus/com/linkedin/restli/examples/defaults/api/HighLevelRecordWithDefault.pdl, restli-int-test-api/src/main/snapshot/com.linkedin.restli.examples.defaults.api.fillInDefaults.snapshot.json, restli-int-test-server/src/main/java/com/linkedin/restli/examples/greetings/server/defaults/FieldFillInDefaultResources.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestFillInDefaultValue.java, restli-server/src/main/java/com/linkedin/restli/internal/server/response/CollectionResponseBuilder.java
This fix is because we lack of filling in default values in the paging metadata and custom metadata in the collection response for methods like finders and get_all.
Previously we just iterate the elements and filling in the default values, this PR is adding code to check not just elements but also paging metadata and custom metadata
=> Add default fill in for custom metadata and collection metadata

CHANGELOG.md, d2-schemas/src/main/pegasus/com/linkedin/d2/D2Service.pdl, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/balancer/LastSeenBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerState.java, d2/src/main/java/com/linkedin/d2/balancer/ZKFSLoadBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClient.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClientImpl.java, d2/src/main/java/com/linkedin/d2/balancer/event/D2MonitorEventEmitter.java, d2/src/main/java/com/linkedin/d2/balancer/properties/PropertyKeys.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ServiceProperties.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ServicePropertiesJsonSerializer.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerState.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/degrader/DegraderLoadBalancerStrategyV3.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/PartitionState.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/DeterministicSubsettingMetadata.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/DeterministicSubsettingMetadataProvider.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/DeterministicSubsettingStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/SubsettingStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/SubsettingStrategyFactory.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/SubsettingStrategyFactoryImpl.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/ZKDeterministicSubsettingMetadataProvider.java, d2/src/main/java/com/linkedin/d2/balancer/zkfs/ZKFSTogglingLoadBalancerFactoryImpl.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/StateUpdaterTest.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/TrackerClientMockHelper.java, d2/src/test/java/com/linkedin/d2/balancer/subsetting/DeterministicSubsettingStrategyTest.java, d2/src/test/java/com/linkedin/d2/balancer/subsetting/ZKDeterministicSubsettingMetadataProviderTest.java, gradle.properties
Low QPS is a long-standing problem with the D2 client-side non-cooperative load balancing library. When QPS is low to a server host, its load balancing signals are weak, e.g., its average latency might be volatile when comparing with the average cluster latency, resulting in ineffective degradations and recoveries. 
D2 Subsetting approaches this problem by limiting a single client to only access a subset of the downstream hosts, resulting in higher QPS and stronger signals of a downstream host with the same amount of requests from the client.
The key of D2 Subsetting is to maintain an overall balanced traffic distribution to the downstream, even though the clients are picking different subsets from the downstream hosts.
=> D2 Cluster Subsetting Implementation

CHANGELOG.md, data-avro/src/main/java/com/linkedin/data/avro/DefaultDataToAvroConvertCallback.java, data-avro/src/test/java/com/linkedin/data/avro/TestDataTranslator.java, gradle.properties
Avro schema translator should use the default value from the nested field if the parent record level default doesn't provide a value for the field.
This behavior is consistent with how PDL schema defaults are handled.
=> Fix default value resolution logic in avro translator to match PDL.

restli-client/src/test/java/com/linkedin/restli/client/TestParSeqBasedCompletionStage.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestParseqBasedFluentClientApi.java, restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/fluentspec/ActionMethodSpec.java, restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/fluentspec/AssociationResourceSpec.java, restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/fluentspec/CollectionResourceSpec.java, restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/fluentspec/ParameterSpec.java, restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/fluentspec/SpecUtils.java, restli-tools/src/main/resources/apiVmTemplates/resource.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_create_id.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_create_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_delete.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_get.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_partial_update_no_return.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_partial_update_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_update.vm, restli-tools/src/main/resources/apiVmTemplates/rest.create_id.vm, restli-tools/src/main/resources/apiVmTemplates/rest.create_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.delete.vm, restli-tools/src/main/resources/apiVmTemplates/rest.get.vm, restli-tools/src/main/resources/apiVmTemplates/rest.partial_update_no_return.vm, restli-tools/src/main/resources/apiVmTemplates/rest.partial_update_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.update.vm
=== Included in PR & already done ===
KeyTypeRef : in CollectionResourceSpec
AssocKeyTypeRef : in AssociateResourceSpec's CompoundKeySpec
Action ReturnTypeRef : in ActionMethodSpec
ParameterSpec (which will handle following)
Action's ActionParam
Finder' QueryParam
Tests for KeyTypeRef
p.s. AssocKeyTypeRef already tested in AssocKeys
p.s. Action's return and actionParam will be tested in https://github.com/linkedin/rest.li/pull/580
=== Not Included in PR ===
Finder's use of AssocKeyParam
Finder's use of QueryParam
**All the TODO will be handled in follow up PRs**
=> Add TypeRef Infos to corresponding Spec files

restli-client/src/test/java/com/linkedin/restli/client/TestParSeqBasedCompletionStage.java
It became flaky in Travis-CI because Travis-CI provides so few threads in the common fork-join pool.
=> Try to tune parameter in tests so it can be stable in Travis-CI's environment

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/subsetting/ZKDeterministicSubsettingMetadataProvider.java, d2/src/test/java/com/linkedin/d2/balancer/subsetting/ZKDeterministicSubsettingMetadataProviderTest.java, gradle.properties
Instead of using nodeUri, we use host fqdn to fetch D2 subsetting metadata.
Previously, we use the nodeUri in the form of "https://${com.linkedin.metadata.fqdn}:${com.linkedin.metadata.application.port.https}/${com.linkedin.metadata.context_path}${d2.resourcePath}" to get subsetting metadata. After this change, we will simply use "{com.linkedin.metadata.fqdn}"
=> Use host FQDN instead of nodeUri to get D2 subsetting metadata

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/properties/ServiceProperties.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ServicePropertiesJsonSerializer.java, gradle.properties
Address the bug where the String config value is not able to auto convert to Boolean:
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
at com.linkedin.d2.balancer.properties.ServicePropertiesJsonSerializer.fromMap(ServicePropertiesJsonSerializer.java:206)
at com.linkedin.d2.balancer.properties.ServicePropertiesJsonSerializer.fromMap(ServicePropertiesJsonSerializer.java:40)
```
=> Fix converting enableClusterSubsetting to Boolean in ServicePropertiesJsonSerializer

build.gradle, defaultEnvironment.gradle
Bintray is doing intentional service blackouts right now in order to get
the attention of use cases that are still reading artifacts from
Bintray (of which pegasus is one...). This adds LI's JFrog Artifactory
instance as a maven repo and bumps parseq to the version that's
currently hosted on JFrog. The Bintray address can be removed once
that's down for good, just to be sure.
=> Add LI JFrog Artifactory to buildscript repos

restli-client/src/main/java/com/linkedin/restli/client/ExecutionGroup.java, restli-client/src/main/java/com/linkedin/restli/client/FluentClient.java, restli-client/src/main/java/com/linkedin/restli/client/ParSeqBasedCompletionStage.java, restli-client/src/main/java/com/linkedin/restli/client/ParSeqBasedFluentClient.java, restli-client/src/test/java/com/linkedin/restli/client/TestExecutionGroup.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestParSeqBasedFluentClientApiWithExecutionGroup.java, restli-tools/src/main/resources/apiVmTemplates/action.vm, restli-tools/src/main/resources/apiVmTemplates/batch_finder.vm, restli-tools/src/main/resources/apiVmTemplates/finder.vm, restli-tools/src/main/resources/apiVmTemplates/resource.vm, restli-tools/src/main/resources/apiVmTemplates/resource_interface.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_create_id.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_create_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_delete.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_get.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_partial_update_no_return.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_partial_update_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_update.vm, restli-tools/src/main/resources/apiVmTemplates/rest.create_id.vm, restli-tools/src/main/resources/apiVmTemplates/rest.create_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.delete.vm, restli-tools/src/main/resources/apiVmTemplates/rest.get.vm, restli-tools/src/main/resources/apiVmTemplates/rest.get_all.vm, restli-tools/src/main/resources/apiVmTemplates/rest.partial_update_no_return.vm, restli-tools/src/main/resources/apiVmTemplates/rest.partial_update_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.update.vm, restli-tools/src/main/resources/macros/library.vm
- Integrated the execution group into the template
- The FluentClient interface has been renamed to ParSeqBasedFluentClient
=> Integration execution group to fluent API

build.gradle, defaultEnvironment.gradle, scripts/get-module-dependencies, scripts/help-text/get-module-dependencies.txt, scripts/travis/build.sh
When building pegasus, a comma-separated list provided as project property `pegasus.skipTestsForSubprojects` will be read and used to determine which subproject's tests to skip. For now, this is only applied to `r2-int-test` if none of `r2-int-test`'s test dependencies are touched.
I also sequentially ran the tests for each subproject to see which one takes the most time, the results are pretty interesting...
`r2-int-test` has by far the most lengthy tests at 28 minutes, `restli-int-test` in second at 12 minutes, and `d2` in third at around 5 minutes. Most everything else is around or below one minute.
(Note: The results of this test could probably be made more accurate by cleaning build artifacts before each run... but oh well)
```
(1/63) -> d2
BUILD SUCCESSFUL in 4m 51s
(2/63) -> …
```
=> Support for skipping subproject tests via properties

build.gradle, defaultEnvironment.gradle
We had to add both LinkedIn's JFrog repo in addition to LinkedIn's JFrog
repo for Bintray backups, but the main JFrog repo was recently
configured to also act as a view into the backups repo. Thus, we no
longer need to explicitly reference the backup repo.
=> Remove JFrog Bintray backup from Maven repos

build.gradle
Since our build is parallel and has some lengthy test suites, failing fast can help to free up the Travis CI environment.
This is disabled locally for now since we're not sure if there are unintended consequences in aborting like this. Perhaps aborting while code generation is going on could be problematic? Since the Travis build is a clean checkout, it doesn't matter as much. (I haven't done any research at all on the danger here, but doing it this way just to be safe).
=> Make the build fail fast in CI

CHANGELOG.md, restli-int-test-server/src/main/java/com/linkedin/restli/examples/greetings/server/CustomTypesResource3.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestCustomTypesClient.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestParseqBasedFluentClientApi.java, restli-tools/src/main/resources/macros/library.vm
Fix bug in generated fluent client APIs when typerefs are used as association key params
=> Fix bug in generated fluent client APIs when typerefs are used as association key params

restli-int-test-api/src/main/idl/com.linkedin.restli.examples.greetings.client.associations.restspec.json, restli-int-test-api/src/main/snapshot/com.linkedin.restli.examples.greetings.client.associations.snapshot.json, restli-int-test-server/src/main/java/com/linkedin/restli/examples/greetings/server/AssociationsResource.java, restli-int-test-server/src/main/java/com/linkedin/restli/examples/greetings/server/altkey/AltKeyDataProvider.java, restli-int-test-server/src/main/java/com/linkedin/restli/examples/greetings/server/altkey/AssociationAltKeyResource.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestParseqBasedFluentClientApi.java, restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/fluentspec/MethodSpec.java, restli-tools/src/main/resources/apiVmTemplates/action.vm, restli-tools/src/main/resources/apiVmTemplates/batch_finder.vm, restli-tools/src/main/resources/apiVmTemplates/finder.vm, restli-tools/src/main/resources/apiVmTemplates/rest.delete.vm, restli-tools/src/main/resources/apiVmTemplates/rest.get.vm, restli-tools/src/main/resources/apiVmTemplates/rest.partial_update_no_return.vm, restli-tools/src/main/resources/apiVmTemplates/rest.partial_update_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.update.vm, restli-tools/src/main/resources/macros/library.vm
Current FluentAPI uses API such as
`get(CompoundKey)`
this change another set of API which use spreaded version of the compoundKey
e.g., if CompoundKey consists of Long and String, it would be
`get(Long id, String message)`
=> Add APIs with assock key param fluentapi

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java
During application of the Pegasus Gradle plugin, check the current project version agains the min required/suggested versions and either fail or warn with an actionable message.
For now, only enforce Gradle `1.0` to keep compatibility. I will follow this up with a backward-incompatible PR for the next major release to enforce `5.2.1`.
The recommended version should be what the next enforced version will be. For now, that's `5.2.1` (see above). Then, it'll be `5.3`.
=> Check Gradle version against min required/suggested versions

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/clients/DynamicClient.java, r2-core/src/main/java/com/linkedin/r2/filter/FilterChain.java, r2-core/src/main/java/com/linkedin/r2/filter/FilterChainImpl.java, r2-core/src/main/java/com/linkedin/r2/filter/TimedRestFilter.java, r2-core/src/main/java/com/linkedin/r2/filter/TimedStreamFilter.java, r2-core/src/main/java/com/linkedin/r2/filter/transport/FilterChainClient.java, r2-core/src/main/java/com/linkedin/r2/message/timing/TimingKey.java, r2-netty/src/main/java/com/linkedin/r2/netty/client/HttpNettyClient.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/HttpClientFactory.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/common/AbstractNettyClient.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestHttpClientFactory.java
Details can be found in https://github.com/linkedin/rest.li/issues/587.
=> Fix TimingKey Memory Leak #587

CHANGELOG.md, generator/src/main/java/com/linkedin/pegasus/generator/DataSchemaParser.java, generator/src/main/java/com/linkedin/pegasus/generator/FileFormatDataSchemaParser.java, gradle.properties
Both of these optimizations combined, reduce the entirety of client code
generation from 2 minutes to 20 seconds on a large codebase. These 
bottlenecks were discovered by using a flame-graph attached below. The 
sections highlighted in purple essentially don't exist after these changes.
1) Remove usage of `TreeMap`. Using a `TreeMap` with a `DataSchema` key is
very expensive. Every single comparison was calling `toString()` which
forces both schemas to be serialized to JSON, then compared.
The point of this `TreeMap` was just to have deterministic
ordering, when the source file ordering has changed. To maintain this
behavior we can just sort the input up front, and maintain a
`LinkedHashMap` for consistent ordering.
2) Replace `binding()` call in loop with `existingDataSchema()`. The …
=> Fix bottlenecks in DataSchemaParser

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties
This is needed for compatibility with Gradle 7, which removes the long
deprecated "runtime" and "compile" configurations.
=> Use runtimeClasspath instead of runtime config.

CHANGELOG.md, gradle.properties, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceModel.java, restli-server/src/main/java/com/linkedin/restli/server/ResourceDefinition.java
This PR exposes `getResourceClass` in `ResourceDefinition` so that `ResourceDefinitionListener` can code using that information. Current ResourceModel (the implementation of ResourceDefinitionListener) already has that method implemented.
=> Expose getResourceClass in ResourceDefinition

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/subsetting/ZKDeterministicSubsettingMetadataProvider.java, gradle.properties
Fix a bug in ZKDeterministicSubsettingMetadataProvider to make host set distinct.
Also, make the info/debug level log more verbose.
=> Fix a bug in ZKDeterministicSubsettingMetadataProvider to make host set distinct

CHANGELOG.md, gradle.properties, restli-common/src/main/pegasus/com/linkedin/restli/restspec/ActionSchema.pdl, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceMethodDescriptor.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceModelEncoder.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/RestLiAnnotationReader.java, restli-server/src/main/java/com/linkedin/restli/server/annotations/Action.java, restli-tools/src/main/java/com/linkedin/restli/tools/compatibility/ResourceCompatibilityChecker.java, restli-tools/src/test/java/com/linkedin/restli/tools/compatibility/TestResourceCompatibilityChecker.java, restli-tools/src/test/java/com/linkedin/restli/tools/snapshot/circular/CircularResource.java, restli-tools/src/test/resources/idls/curr-greeting-simple-fail.restspec.json, restli-tools/src/test/resources/idls/curr-greeting-simple-pass.restspec.json, restli-tools/src/test/resources/idls/prev-greeting-simple.restspec.json, restli-tools/src/test/resources/snapshots/circular-circular.snapshot.json
For example, we can use this hint to decide which actions to pull into queries and which into mutations when building GQL schemas off rest.li resources.
=> Introduce a readonly attribute on the action annotation

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/grammar/PdlSchemaParser.java, data/src/test/java/com/linkedin/data/schema/grammar/TestPdlSchemaParser.java, data/src/test/resources/com/linkedin/data/schema/grammar/TestEnumForParserContextLocations.pdl, data/src/test/resources/com/linkedin/data/schema/grammar/TestFixedForParserContextLocations.pdl, data/src/test/resources/com/linkedin/data/schema/grammar/TestRecordForParserContextLocations.pdl, data/src/test/resources/com/linkedin/data/schema/grammar/TestTyperefForParserContextLocations.pdl, gradle.properties
This feature would be useful for tools that provide additional functionality like linting, code search etc on the PDL schemas.
=> Add support for returning location of schema elements from the PDL schema parser.

CHANGELOG.md, gradle.properties, r2-core/src/main/java/com/linkedin/r2/message/timing/TimingKey.java
This is safe because unregistering does no I/O; it only removes from a
concurrent map.
Without using daemon threads, the threads created by the ExecutorService
will never be shut down unless the Java process is killed forceably with
System.exit or by an external system.
We found that this is impacting many internal products that initialize their Espresso databases locally for integration testing. The tool that does that is kept alive indefinitely by the static thread pool in TimingKey. While this has been worked around in new versions of the tool by explicitly calling System.exit, it shouldn't be necessary; and there are compatibility tests that fail because rest.li is updated while the tool is not.
=> Use daemon thread to unregister TimingKeys.

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties
I closed a previous version of this change because it included more involved changes to remove references to "compile" and "testCompile" as well. Restoring just this small change to remove the references to "runtime" for Gradle 7 compatibility.
=> Remove one more "runtime" configuration reference.

CHANGELOG.md, data/src/main/java/com/linkedin/util/CustomTypeUtil.java, gradle.properties
Use class.getClassLoader() instead thread.getContextClassLoader() to get the class loader due to the java 8 -> java 11 backward incompatible behavior.
Issue:
In Java 8 a new thread would “inherit” the classloader of the thread that forked it, but in Java 11 the new thread will use the default class loader. Because of this backward incompatible problem between Java 8 and Java 11, thread.getContextClassLoader() is not getting class loader in CustomTypeUtil.
Solution:
We are going to use class.getClassLoader() to get the class loader, if class.getClassLoader() is failing to get the class loader, we fall back to use thread.getContextClassLoader() to get the class loader.
=> Use class.getClassLoader() instead thread.getContextClassLoader()

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerState.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClient.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClientImpl.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerState.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/LoadBalancerStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/degrader/DegraderLoadBalancerStrategyV3.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/RelativeLoadBalancerStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/StateUpdater.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/DeterministicSubsettingMetadata.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/DeterministicSubsettingStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/SubsettingState.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/SubsettingStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/SubsettingStrategyFactory.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/SubsettingStrategyFactoryImpl.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/ZKDeterministicSubsettingMetadataProvider.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/degrader/DegraderLoadBalancerTest.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/StateUpdaterTest.java, d2/src/test/java/com/linkedin/d2/balancer/subsetting/DeterministicSubsettingStrategyTest.java, d2/src/test/java/com/linkedin/d2/balancer/subsetting/SubsettingStateTest.java, d2/src/test/java/com/linkedin/d2/balancer/subsetting/ZKDeterministicSubsettingMetadataProviderTest.java, gradle.properties
1. Fix a race condition where two threads with same clusterGenerationId attempts to update subset simultaneously, one thread still gets the old cached subset. The fix is to make the update a critical section.
2. Fix a bug when client cluster changes, the clusterGenerationId passed into loadBalancerStrategy is not changed, causing stale state.
3. Fix a bug when minClusterSubsetSize changes, the client is still pulling the cached subset.
=> Fix race conditions in D2 cluster subsetting

src/reference_return_entity.md
Doc uses deprecated `shouldReturnEntity()` which is misleading.
=> @ReturnEntity doc: Use ResourceContext's `isReturnEntityRequested()`

CHANGELOG.md, gradle-plugins/src/integTest/groovy/com/linkedin/pegasus/gradle/PegasusPluginCacheabilityTest.groovy, gradle-plugins/src/integTest/groovy/com/linkedin/pegasus/gradle/PegasusPluginIntegrationTest.groovy, gradle-plugins/src/integTest/groovy/com/linkedin/pegasus/gradle/publishing/PegasusPluginIvyPublishIntegrationTest.groovy, gradle-plugins/src/integTest/resources/ivy/modern/gradle7/expectedChildIvyDescriptorContents.txt, gradle-plugins/src/integTest/resources/ivy/modern/gradle7/expectedGrandparentIvyDescriptorContents.txt, gradle-plugins/src/integTest/resources/ivy/modern/gradle7/expectedParentIvyDescriptorContents.txt, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateDataTemplateTask.java, gradle.properties
1. Add schemas as source set resources and rely on the Java plugin to
copy them into the artifact instead of doing so directly, to avoid
copying duplicates. Copying the same file twice now throws an error
by default in Gradle 7.
2. Change getter names in GenerateDataTemplateTask to conform to what
Gradle 7 requires and deprecate the old ones.
3. Run most plugin tests against a matrix of Gradle versions, including
Gradle 7.
4. Update integration tests to pass.
=> More changes for Gradle 7 compatibility.

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties
PegasusPlugin should not force its users to apply either the Idea or
the Eclipse plugins. In some setups, neither plugin is needed, such
as when using IntelliJ's native Gradle import.
=> Do not apply Idea and Eclipse plugins.

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/validation/CoercionMode.java, data/src/main/java/com/linkedin/data/schema/validation/ValidateDataAgainstSchema.java, data/src/test/java/com/linkedin/data/schema/validation/TestValidation.java, gradle.properties
Support has already been added for non-numeric float/double values (`NaN`, `Infinity`, `-Infinity`) in Rest.li, but support wasn't added in the validation logic. This was causing validation failures for serialized (i.e. not in-memory) non-numeric float/double values, which only occured in upstream resources (services receiving these values in a response).
Updates the validation testing to more thoroughly test non-numeric float values.
=> Fix validation of non-numeric float values

CHANGELOG.md, restli-server/src/main/java/com/linkedin/restli/internal/server/RestLiRouter.java, restli-server/src/test/java/com/linkedin/restli/server/test/TestRestLiResourceModels.java, restli-server/src/test/java/com/linkedin/restli/server/test/TestRestLiRouting.java, restli-server/src/test/java/com/linkedin/restli/server/twitter/StatusCollectionResource.java, restli-server/src/test/java/com/linkedin/restli/server/twitter/TwitterAccountsResource.java
In previous RestLiRouter logic, we check:
If query parameter contains
"q" -> we treat that URL contains a finder name -> we thought that URL contains query parameters
"action" -> we treat URL contains  a action name -> we thought that URL contains action parameters
Therefore, a url contains "q" and "action" will be thought as a query which contains both QueryParameters and ActionParameters.
This is essentially werid logic (for example, deciding whether the URL contains query parameters by just checking single query name "q"), but that is what it was.
This bug fix however defined a new rule:
If GET and "bq" in parameters, treat this as a batchFinder, so "q" and "action" can be both query parameter name
If GET and "q" in parameters,  treat this as a Finder, so "action" can be both query …
=> Update RestliRouter to allow "action", "q" as parameter name

CHANGELOG.md, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/data/ExtensionSchemaValidationCmdLineApp.java, restli-tools/src/test/extensions/invalidNoExtensionAnnotation/BazExtensions.pdl, restli-tools/src/test/extensions/validCase/BazExtensions.pdl, restli-tools/src/test/extensions/validCase/FooExtensions.pdl, restli-tools/src/test/java/com/linkedin/restli/tools/data/TestExtensionSchemaValidationCmdLineApp.java
Summary:
This change is relaxing the extension schema check to make @extension annotation is optional for 1-1 injections. 
For 1-1 injections @extension is not required, If there is no extension annotation, by default ER uses extended entity's urn as the resource key to fetch the injected entity.
Test:
Added unit tests.
=> Relax extension schema check to make @extension annotation is optional for 1-1 injections

CHANGELOG.md, restli-tools/src/main/java/com/linkedin/restli/tools/data/ExtensionSchemaValidationCmdLineApp.java, restli-tools/src/test/extensions/invalidNoExtensionAnnotation/BazExtensions.pdl, restli-tools/src/test/extensions/validCase/BazExtensions.pdl, restli-tools/src/test/extensions/validCase/FooExtensions.pdl, restli-tools/src/test/java/com/linkedin/restli/tools/data/TestExtensionSchemaValidationCmdLineApp.java
This RB is revering the #654 commit. 
We decided to make @extension.param is a required annotation when defining 1-to-1 injections.
=> Revert "Relax extension schema check to make @extension annotation is optional for 1-to-1 injections (#654)"

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/FileCompatibilityType.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PropertyUtil.java, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/compatibility/CompatibilityInfoMap.java, restli-tools/src/main/java/com/linkedin/restli/tools/compatibility/CompatibilityReport.java
This PR is adding the compatibility level configuration for extension schema compatibility check.
1. It supports 4 compatibility levels which are the same as restModel compatibility levels: OFF, IGNORE, BACKWARDS, EQUIVALENT(https://linkedin.github.io/rest.li/modeling/compatibility_check#compatibility-levels).
2. The configuration name is "pegasusPlugin.extensionSchema.compatibility".
3. Users could use this config to define the compatibility level when running the extension schema compatibility check, for example:
"./gradlew checkPegasusExtensionSchemaSnapshot -PpegasusPlugin.extensionSchema.compatibility=ignore"
or directly add this property in the gradle.properties file.
Test:
Generated snapshot and manual tested the configs.
Todo: update Rest.li doc for this change.
=> Adding compatibility level configs for extension schema compatibility check

CHANGELOG.md, data/src/main/java/com/linkedin/data/collections/CheckedMap.java, data/src/test/java/com/linkedin/data/collections/TestCheckedMap.java, gradle.properties
This is useful because entrySet() by default returns an unmodifiableMap making bulk remove operations painful and inefficient (store all keys to be removed into another data structure and then do another pass to remove).
=> Add a predicate based bulk remove method for checkedMap

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/UnionDataSchema.java, data/src/main/java/com/linkedin/data/schema/validator/DataSchemaAnnotationValidator.java, data/src/test/java/com/linkedin/data/schema/validator/TestValidator.java, gradle.properties
Union members originally didn't support custom properties and thus validation on the members was not supported. With aliased unions, members now support custom properties and thus can specify custom validation.
This PR updates the validation logic so these custom validation are applied correctly.
=> Add support for validating aliased union members.

CHANGELOG.md, build.gradle, gradle.properties, r2-core/src/test/java/com/linkedin/r2/transport/http/client/TestServer.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestHttpNettyClient.java
With JDK8u282, the ALPN APIs are merged with JDK itself and the ALPN jar is not required. The support for this is added in the netty. Without this newer netty, we get "Unable to wrap SSLEngine of type sun.security.ssl.SSLEngineImpl" runtime error. So this PR updates the netty to avoid this error.
=> Bump netty version to use ALPN support needed for JDK8u282.

CHANGELOG.md, gradle.properties, restli-server/src/main/java/com/linkedin/restli/internal/server/ResourceContextImpl.java, restli-server/src/main/java/com/linkedin/restli/internal/server/ServerResourceContext.java, restli-server/src/main/java/com/linkedin/restli/internal/server/util/MIMEParse.java, restli-server/src/main/java/com/linkedin/restli/internal/server/util/RestUtils.java, restli-server/src/main/java/com/linkedin/restli/server/LocalRequestProjectionMask.java, restli-server/src/test/java/com/linkedin/restli/internal/server/TestResourceContextImpl.java
Provide the ability to set cookies and projection params in request context's local attributes to avoid serializing/deserializing them for requests that are executed in-process.
=> Optimize in-process request execution.

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/DataSchemaResolver.java, data/src/main/java/com/linkedin/data/schema/resolver/AbstractDataSchemaResolver.java, data/src/main/java/com/linkedin/data/schema/resolver/AbstractMultiFormatDataSchemaResolver.java, data/src/main/java/com/linkedin/data/schema/resolver/ClasspathResourceDataSchemaResolver.java, data/src/main/java/com/linkedin/data/schema/resolver/ExtensionsDataSchemaResolver.java, data/src/main/java/com/linkedin/data/schema/resolver/FileDataSchemaResolver.java, data/src/main/java/com/linkedin/data/schema/resolver/MultiFormatDataSchemaResolver.java, data/src/main/java/com/linkedin/data/schema/resolver/SchemaDirectory.java, data/src/main/java/com/linkedin/data/schema/resolver/SchemaDirectoryName.java, data/src/test/java/com/linkedin/data/schema/resolver/TestDataSchemaResolver.java, data/src/test/java/com/linkedin/data/schema/resolver/TestExtensionsDataSchemaResolver.java, data/src/test/java/com/linkedin/data/schema/resolver/TestFileDataSchemaResolver.java, data/src/test/resources/extensions/com/linkedin/restli/example/AlbumExtensions.pdl, generator/src/main/java/com/linkedin/pegasus/generator/DataSchemaParser.java, generator/src/main/java/com/linkedin/pegasus/generator/FileFormatDataSchemaParser.java, generator/src/main/java/com/linkedin/pegasus/generator/PegasusDataTemplateGenerator.java, generator/src/test/java/com/linkedin/pegasus/generator/TestDataSchemaParser.java, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/annotation/SchemaAnnotationValidatorCmdLineApp.java, restli-tools/src/main/java/com/linkedin/restli/tools/data/SchemaFormatTranslator.java, restli-tools/src/test/java/com/linkedin/restli/tools/clientgen/TestRequestBuilderSpecGenerator.java
This change also introduces the concept of "source" and "resolver"
directories when creating a `DataSchemaParser`. "Source" directories are
used to parse/load the input schemas, while the "resolver" directories
will only be used for resolving referenced schemas.
=> Add support for resolving from multiple schema source directories.

CHANGELOG.md, darkcluster/src/main/java/com/linkedin/darkcluster/impl/ConstantQpsDarkClusterStrategy.java, darkcluster/src/test/java/com/linkedin/darkcluster/TestConstantQpsDarkClusterStrategy.java, darkcluster/src/test/java/com/linkedin/darkcluster/TestDarkClusterStrategyFactory.java, darkcluster/src/test/java/com/linkedin/darkcluster/TestRelativeTrafficMultiplierDarkClusterStrategy.java, gradle.properties
Bug is preventing us from ramping the feature into production. Appears that maybe the clusterInfoProvider returns 0 before it gets a chance to discover what's actually there?
=> Squash a flea. ConstantQps burst value should never eval to 0

CHANGELOG.md, gradle.properties, restli-common/src/main/java/com/linkedin/restli/common/RestConstants.java, restli-server/src/main/java/com/linkedin/restli/server/validation/RestLiValidationFilter.java, restli-server/src/test/java/com/linkedin/restli/server/validation/TestRestLiValidationFilter.java
This is useful if clients are doing validation or don't care about it.
=> Enable skipping request and response validation via the use of request headers

CHANGELOG.md, gradle.properties, restli-common/src/main/java/com/linkedin/restli/common/RestConstants.java, restli-server/src/main/java/com/linkedin/restli/server/validation/RestLiValidationFilter.java, restli-server/src/test/java/com/linkedin/restli/server/validation/TestRestLiValidationFilter.java
We still retain a hook for applications to override and disable request validation on a per-app basis using whatever logic they choose to implement.
=> Remove support for disabling request validation via headers since doing so can have dangerous side effects

CHANGELOG.md, data-avro/src/main/java/com/linkedin/data/avro/DataTranslator.java, gradle.properties
avro 1.10+ is more strict and throws an exception when trying to access a field not in the record schema.
=> dont access avro record fields that may not exist in DataTranslator

CHANGELOG.md, d2-schemas/src/main/pegasus/com/linkedin/d2/DarkClusterConfig.pdl, d2/src/main/java/com/linkedin/d2/balancer/config/DarkClustersConverter.java, d2/src/test/java/com/linkedin/d2/balancer/config/DarkClustersConverterTest.java, darkcluster/src/main/java/com/linkedin/darkcluster/impl/ConstantQpsDarkClusterStrategy.java, darkcluster/src/test/java/com/linkedin/darkcluster/TestConstantQpsDarkClusterStrategy.java, gradle.properties, r2-core/src/main/java/com/linkedin/r2/transport/http/client/ConstantQpsRateLimiter.java, r2-core/src/main/java/com/linkedin/r2/transport/http/client/SmoothRateLimiter.java, r2-core/src/main/java/com/linkedin/r2/transport/http/client/ratelimiter/RateLimiterExecutionTracker.java, r2-core/src/test/java/com/linkedin/r2/transport/http/client/ratelimiter/TestConstantQpsRateLimiter.java
- DarkClusterConfig's dispatcherOutboundTargetRate: int -> float
This change enables low qps use cases to more finely configure their per-host inbound dark qps.
- ConstantQpsRateLimiter - Introduce randomness while maintaining constant per period rate
This addresses a thundering herd problem resulting from a central signaling of many replicas simultaneously running ConstantQpsRateLimiter.
=> ConstantQpsDarkClusterStrategy post-prod fixes

gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java
In previous PR
https://github.com/linkedin/rest.li/commit/e720a5bf4ff110aa0981c5e5f1ab0f7b01367688#diff-881c39f18a279b2c4590938b0e7eb00edaf336ee6ad1291488f80b7f589d13c9R102
The contributor forgot to add the config into PegasusPlugin so user can opt in or opt out.
This PR is to add that back.
=> Add a pegasus plugin config to use case sensitive path in datetemplate generation and rest client generation

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties
This change is making /extensions directory as the resource root. It was a miss when we introduced /extensions directory.
Tested the snapshot in a MP.
=> Make extensions directory as the resource root

CHANGELOG.md, gradle.properties, restli-server/src/main/java/com/linkedin/restli/internal/server/util/RestUtils.java, restli-server/src/main/java/com/linkedin/restli/server/BaseRestLiServer.java, restli-server/src/main/java/com/linkedin/restli/server/RestLiConfig.java, restli-server/src/test/java/com/linkedin/restli/internal/server/util/TestRestUtils.java
Add server config support to define supported accept types
1) if this is set server will support only the accept types defined in list and if non of accept type requested by client is supported it will default to empty type ie json
2) if not set server will support all supported content types ie. custom or defined within restli.
=> Add server config support to define supported accept types

CHANGELOG.md, restli-server/src/main/java/com/linkedin/restli/server/resources/Jsr330Adapter.java, restli-server/src/test/java/com/linkedin/restli/server/resources/TestInjectResourceFactory.java, restli-server/src/test/java/com/linkedin/restli/server/resources/fixtures/ConstructorArgResource.java, restli-server/src/test/java/com/linkedin/restli/server/resources/fixtures/DefaultConstructorArgResource.java, restli-server/src/test/java/com/linkedin/restli/server/resources/fixtures/PublicConstructorArgResource.java
In section 4.1 of JSR 330, there is explicitly a package protected
constructor: https://jcp.org/en/jsr/detail?id=330#orig
This is also consistent with guice and others as well as errorprone:
https://errorprone.info/bugpattern/UnnecessarilyVisible
=> Change JSR330Adapter to use getDeclaredConstructors

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties
This is needed by plugins that need to identify which directory holds
the schemas in order to operate on them. We cannot assume that it is
always called "pegasus", because of the ability to override.
=> Make PegasusPlugin#getDataSchemaPath public.

src/contribute.md
In previou PR raised by customer :
https://github.com/linkedin/rest.li/pull/696
it was applied to `gh-pages` branch.
That will not work. This PR re-apply the change in `gh-page-source` branch
=> Reapply PR 696 in gh-page-source

CHANGELOG.md, darkcluster/src/test/java/com/linkedin/darkcluster/TestConstantQpsDarkClusterStrategy.java, gradle.properties, r2-core/src/main/java/com/linkedin/r2/transport/http/client/SmoothRateLimiter.java, r2-core/src/test/java/com/linkedin/r2/transport/http/client/ratelimiter/TestConstantQpsRateLimiter.java
Previous code tends to not actually introduce randomness before executing callbacks. This is caused by event loop iterations being rapidly scheduled back to back (such as setting the rate), which flip the boolean that tracks whether or not a delay should be incurred. This patch replaces the hasDelayed boolean with a more durable timestamp to compare against.
Most important change is a robust unit test that should accurately simulate production. Let me know if I'm missing something with this test setup. The new test fails spectacularly without the patch to SmoothRateLimiter applied.
=> Fix bug in SmoothRateLimiter where executionDelay is not honored

build.gradle
Adds jacocoTestReport and JacocoTestCoverageVerification tasks to the project, which need to be run manually for now.
=> Enable jacoco code coverage for the project.

CHANGELOG.md, gradle.properties, r2-core/src/main/java/com/linkedin/r2/transport/http/client/SmoothRateLimiter.java, r2-core/src/main/java/com/linkedin/r2/transport/http/client/ratelimiter/Rate.java, r2-core/src/test/java/com/linkedin/r2/transport/http/client/ratelimiter/TestConstantQpsRateLimiter.java
Further testing shows benefit in randomness of query distribution over a given period when setRate is idempotent. Current implementation of setRate tends to favor maintaining throughput over maintaining a consistently random distribution over a period.
=> Make SmoothRateLimiter setRate idempotent

src/max_batch_size.md
Fix the list of methods which can use `@MaxBatchSize` annotation.
=> Fix list of methods can use  annotation

CHANGELOG.md, generator/src/main/java/com/linkedin/pegasus/generator/FileFormatDataSchemaParser.java
=> Deprecate old constructor in FileFormatDataSchemaParser

CHANGELOG.md, restli-client-testutils/src/main/java/com/linkedin/restli/client/testutils/MockBatchCollectionResponseFactory.java, restli-client-testutils/src/test/java/com/linkedin/restli/client/testutils/test/TestMockBatchCollectionResponseFactory.java
Rest.li's testutils currently doesn't have support for generating mock BATCH_FINDER method responses. This PR adds support for that.
=> Add mock response generator factory for BATCH_FINDER methods.

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/CheckSnapshotTask.java, gradle.properties
Previously we didn't write any compatibility report if no files found. 
That case typically happens for the "test" sourceSet. Since normally Gradle process "main" sourceset first and then "test" sourceset, therefore this bug is not causing trouble since "test" sourceset just reuse "main" sourceset result.
But it will cause IOException in some corner cases, such as user directly try to process test sourceset.
This change add an additional check. As a result, if no files found, no compatibility report will be return and no compatibility report will be checked
=> Add file existence check before performing compatibility report check

CHANGELOG.md, restli-server/src/main/java/com/linkedin/restli/internal/server/ResourceContextImpl.java, restli-server/src/main/java/com/linkedin/restli/server/ResourceContext.java
This method has been deprecated since version `27.2.0`, so users have had time to migrate to the preferred method.
Cleaning this up before I forget..
=> Remove interface method ResourceContext#shouldReturnEntity

CHANGELOG.md, restli-server/src/main/java/com/linkedin/restli/internal/server/model/RestLiAnnotationReader.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/RestModelConstants.java
Validate the type parameter of `ActionResult`, not `ActionResult` itself. Also improve the build error message for cases where an Action method's return type is a custom typeref but the `@Action` parameter doesn't specify a `returnTyperef` attribute.
Context:
For an Action method that has a custom typeref return type (e.g. `CustomLong`) yet doesn't indicate in the `@Action` parameter that it has a typeref class (e.g. `CustomLongRef.class`), the error will show up as the following:
- If the return type is `CustomLong`: `com.linkedin.restli.server.ResourceConfigException: @Action method 'doAction' on class 'com.example.impl.ExampleResource' has an invalid return type 'com.example.CustomLong'. Expected a DataTemplate or a primitive`
- If the return type is `ActionResult<CustomLong>`: an …
=> Fix validation for ActionResult return types

CHANGELOG.md, gradle.properties, r2-core/src/main/java/com/linkedin/r2/filter/TimedRestFilter.java, r2-core/src/main/java/com/linkedin/r2/filter/TimedStreamFilter.java, r2-core/src/main/java/com/linkedin/r2/message/timing/TimingKey.java, r2-core/src/test/java/com/linkedin/r2/message/timing/TestTimingKey.java
Change to log warning instead of throwing an error when a duplicate timing key name is registered.
Guarantee uniqueness of filter timing key names.
=> Fixed issues with potential duplicate TimingKeys being registered.

CHANGELOG.md, gradle.properties, restli-common/src/main/pegasus/com/linkedin/restli/restspec/ResourceSchema.pdl, restli-docgen/src/main/java/com/linkedin/restli/docgen/examplegen/ExampleRequestResponseGenerator.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceModel.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceModelEncoder.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/RestLiAnnotationData.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/RestLiAnnotationReader.java, restli-server/src/main/java/com/linkedin/restli/server/ResourceDefinition.java, restli-server/src/main/java/com/linkedin/restli/server/annotations/RestLiActions.java, restli-server/src/main/java/com/linkedin/restli/server/annotations/RestLiAssociation.java, restli-server/src/main/java/com/linkedin/restli/server/annotations/RestLiCollection.java, restli-server/src/main/java/com/linkedin/restli/server/annotations/RestLiSimpleResource.java, restli-server/src/test/java/com/linkedin/restli/internal/server/model/SampleResources.java, restli-server/src/test/java/com/linkedin/restli/internal/server/model/TestResourceModel.java, restli-server/src/test/java/com/linkedin/restli/internal/server/model/TestRestLiAnnotationReader.java, restli-tools/src/main/java/com/linkedin/restli/tools/compatibility/ResourceCompatibilityChecker.java, restli-tools/src/test/java/com/linkedin/restli/tools/compatibility/TestResourceCompatibilityChecker.java, restli-tools/src/test/resources/idls/curr-greeting-simple-fail.restspec.json, restli-tools/src/test/resources/idls/curr-greetings-as-fail.restspec.json, restli-tools/src/test/resources/idls/curr-greetings-assoc-fail.restspec.json, restli-tools/src/test/resources/idls/curr-greetings-assoc-pass.restspec.json, restli-tools/src/test/resources/idls/curr-greetings-coll-fail.restspec.json, restli-tools/src/test/resources/idls/prev-greetings-assoc.restspec.json
This is an optional param that is meant to be populated by resources for whom the resource name is not the same as d2 service name (if not populated we default to null). This is useful for situations like generating routing hints for graphQL.
This value is also emitted into the IDL. Any changes to this value are considered backward incompatible.
=> Introduce d2ServiceName annotation on rest.li resources

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperAnnouncer.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperConnectionManager.java, d2/src/main/java/com/linkedin/d2/jmx/JmxManager.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperAnnouncerJmx.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperAnnouncerJmxMXBean.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperConnectionManagerJmx.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperConnectionManagerJmxMBean.java, gradle.properties
Ensures that errors that occur during the announcement are captured to log and that the state of
the announcer's success is visible to monitoring. Adds mbean for the ZooKeeperConnectionManager.
=> Logging and JMX enhancements for D2 ZooKeeper backend.

CHANGELOG.md, data/src/main/java/com/linkedin/data/codec/symbol/DefaultSymbolTableProvider.java, data/src/test/java/com/linkedin/data/codec/symbol/TestDefaultSymbolTableProvider.java, gradle.properties
This is required to add any static headers required for the application downstream calls
=> update DefaultSymbolTableProvider to take default headers as input

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerState.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerState.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/SubsettingState.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/ZKDeterministicSubsettingMetadataProvider.java, d2/src/test/java/com/linkedin/d2/balancer/clients/RetryClientTest.java, d2/src/test/java/com/linkedin/d2/balancer/subsetting/SubsettingStateTest.java, gradle.properties
This PR is a critical bug fix that addresses a race condition in D2 subsetting cache.
The sequence that triggers the race condition is as follows:
1. D2 receives a `ServiceProperties` update, and in the new config, D2 subsetting is enabled.
2. In `handlePut()` of `ServiceLoadBalancerSubscriber`, the new `ServiceProperties` is put into the `SimpleLoadBalancerState`.
3. Another thread jumps in, reads the new `ServiceProperties` and updates the D2 subset cache with the TrackerClient map.
4. `handlePut()` continues and calls `_state.refreshClients()`. New TransportClients and TrackerClients are created and the old ones are shutdown.
5. But in the subset cache, it still holds on to the old TrackerClient, while the underlying TransportClient has already been shutdown.
6. All the subsequent …
=> Fix a race condition where TransportClient is shutdown while subset cache still holds reference to it

CHANGELOG.md, data/src/main/java/com/linkedin/data/codec/symbol/DefaultSymbolTableProvider.java, data/src/test/java/com/linkedin/data/codec/symbol/TestDefaultSymbolTableProvider.java, gradle.properties
This change fixes missing header required for LI internal tracing which couldn't be injected at boot time because dynamic tree id required in trace.
=> Add dummy trace header to fetch default remote symbol table

CHANGELOG.md, gradle.properties, restli-docgen/src/main/java/com/linkedin/restli/docgen/DefaultDocumentationRequestHandler.java
In `DefaultDocumentationRequestHandler`, the documentation renderers are lazily initialized. Request threads will block on the completion of this initialization, which could cause problems if it takes too long. This changes that, as request threads will simply fail if it's not complete.
=> Fail documentation requests while renderers are being lazily initialized

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/discovery/event/PropertyEventBusImpl.java, gradle.properties
Fix for SI-24257, where NPS is thrown when registering listener before publisher exists on an event bus.
Some event buses are created without a publisher, as a publisher can be set later via setPublisher. However the register listener function assumes that a publisher exists when a first listener is added for a property name, and attempts to tell it to start publishing. Fix is to simply check for a null publisher. Same issue potentially exists in unregister. setPublisher already correctly handles starting publishing if listeners are already registered.
=> Fix for SI-24257 (NPS from PropertyEventBusImpl)

restli-int-test-server/build.gradle
build failed with this message
```
Execution failed for task ':restli-int-test-server:startServer'.
> No signature of method: org.gradle.internal.logging.compatbridge.LoggingManagerInternalCompatibilityBridge.captureStandardOutput() is applicable for argument types: (org.apache.tools.ant.types.LogLevel) values: [info]
Possible solutions: captureStandardOutput(org.gradle.api.logging.LogLevel)
```
=> Update outdated gradle class used in restli-int-server module's buid.gradle

CHANGELOG.md, darkcluster/src/main/java/com/linkedin/darkcluster/api/DarkGateKeeper.java, darkcluster/src/main/java/com/linkedin/darkcluster/impl/DarkClusterManagerImpl.java, darkcluster/src/test/java/com/linkedin/darkcluster/TestDarkClusterManager.java, gradle.properties
Previously, DarkGateKeeper can only apply to all dark clusters. Exposing an API to make it configurable for each dark cluster
=> Make DarkGateKeeper configurable given a dark cluster name

CHANGELOG.md, gradle.properties, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceModelEncoder.java
Our documentationRender would respond to Options calls by checking the restspec json files from class path using a direct resource name as the file name. 
But some cusomters added a prefix as api-name to pegasus plugin's idl options when generating the idl files, therefore the idl file in class path will have that prefix and documentationRender will not find it for option calls.
This change, is to fix this case by searching for all restspec.json files in the classpath, so that the restspec.json which prefixed by api-names are also taken into account.
Tested by local optionss call, e.g.
`curl "localhost:9000/<service-name>/<resource-name>" -X OPTIONS`
=> Fix a bug during documentation rendering where it does not account for api-name in the path when searching for restepec file

CHANGELOG.md, data-avro/src/main/java/com/linkedin/data/avro/DefaultAvroToDataConvertCallback.java, data-avro/src/test/java/com/linkedin/data/avro/TestSchemaTranslator.java, gradle.properties
This commit fixes a bug for record default values that do not specify default values for each field. If a field is optional and is missing a default value in the record default value, `fieldValue` in `translateField()` will be `null` instead of `Data.NULL`.
Without this fix, Avro schema translation will fail with a `NullPointerException`.
```
java.lang.NullPointerException
at com.linkedin.data.avro.AbstractDefaultDataTranslator.translate(AbstractDefaultDataTranslator.java:136)
at com.linkedin.data.avro.DefaultAvroToDataConvertCallback.translateField(DefaultAvroToDataConvertCallback.java:88)
at com.linkedin.data.avro.AbstractDefaultDataTranslator.translate(AbstractDefaultDataTranslator.java:138)
at com.linkedin.data.avro.DefaultAvroToDataConvertCallback.translateField(DefaultAvroToDataConve …
```
=> Bugfix for Avro schema translation for schemas with partial record default values

CHANGELOG.md, d2/build.gradle, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerStateItem.java, d2/src/main/java/com/linkedin/d2/balancer/simple/ClusterInfoItem.java, d2/src/main/java/com/linkedin/d2/balancer/simple/ClusterLoadBalancerSubscriber.java, d2/src/main/java/com/linkedin/d2/balancer/simple/ServiceLoadBalancerSubscriber.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerState.java, d2/src/main/java/com/linkedin/d2/jmx/ClusterInfoJmx.java, d2/src/main/java/com/linkedin/d2/jmx/ClusterInfoJmxMBean.java, d2/src/main/java/com/linkedin/d2/jmx/D2ClientJmxManager.java, d2/src/main/java/com/linkedin/d2/jmx/JmxManager.java, d2/src/main/java/com/linkedin/d2/jmx/ServicePropertiesJmx.java, d2/src/main/java/com/linkedin/d2/jmx/ServicePropertiesJmxMBean.java, d2/src/test/java/com/linkedin/d2/balancer/simple/ClusterLoadBalancerSubscriberTest.java, d2/src/test/java/com/linkedin/d2/balancer/simple/ServiceLoadBalancerSubscriberTest.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerStateTest.java, d2/src/test/java/com/linkedin/d2/jmx/ClusterInfoJmxTest.java, d2/src/test/java/com/linkedin/d2/jmx/D2ClientJmxManagerTest.java, d2/src/test/java/com/linkedin/d2/jmx/JmxManagerTest.java, d2/src/test/java/com/linkedin/d2/jmx/ServicePropertiesJmxTest.java, gradle.properties
Implement rest.li changes for adding D2 Canary metrics. This commit adds the following items:
1. Add canary distribution policy into ClusterInfo and SimpleLoadBalancerState to facilitate
constructing corresponding JMX beans
2. New callbacks in SimpleLoadBalancerState for notifying listeners about ServiceProperties updates, the callbacks can then be used to register / deregister corresponding JMX and Sensor in the follow-up diff.
3. Simple JMX and MBeans for ClusterInfo and ServiceProperties, for now we only expose canary distribution policy. In the future, we can add more metrics about Service or Cluster properties by resuing the same framework.
=> Implement rest.li changes for adding D2 Canary metrics

CHANGELOG.md, gradle.properties, restli-server/src/main/java/com/linkedin/restli/server/RestLiServer.java
In some optimization cases, we need to skip some rest.li filters for in-process invocation, where we need to have access to final rest.li filters used to initialize rest.li server. This RB provides a way to expose RestLiConfig used to initialize RestLiServer.
=> Expose RestLiConfig from RestLiServer

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/ZKConnection.java
When async shutdowns are used there can be a race between the shutdown
and incoming new watcher events which will produce errors in logs. Silencing
them to avoid unnecessary noise that suggest a problem where none exists.
=> Silence errors on Zookeeper shutdown race.

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerTest.java, gradle.properties
Updated partition accessor exception branch to map unmapped keys to default partition. 
added debug log for dev to identify any partition misconfiguration during testing.
Note: this breaks the current contract to fail fast on unmappable URI, but this should ideally be fine if tested on staging env.
=> update d2 partitioning logic to map unmapped keys to default partition

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/ZKFSLoadBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/zkfs/ZKFSTogglingLoadBalancerFactoryImpl.java, gradle.properties
Previously, canary distribution provider was passed in only from last-seen load balancer factory, which causes the canary distribution provider being null for ZKFS toggling load balancer. This PR is to fix that by passing in the provider from ZKFS load balancer factory as well.
=> Fix passing in canary distribution provider from ZKFS load balancer factory

CHANGELOG.md, gradle.properties, restli-common/src/main/pegasus/com/linkedin/restli/restspec/FinderSchema.pdl, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceMethodDescriptor.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceModelEncoder.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/RestLiAnnotationReader.java, restli-server/src/main/java/com/linkedin/restli/server/annotations/Finder.java, restli-server/src/test/java/com/linkedin/restli/server/invalid/InvalidResources.java, restli-server/src/test/java/com/linkedin/restli/server/test/TestRestLiResourceModels.java, restli-tools/src/main/java/com/linkedin/restli/tools/compatibility/ResourceCompatibilityChecker.java, restli-tools/src/test/java/com/linkedin/restli/tools/compatibility/TestResourceCompatibilityChecker.java, restli-tools/src/test/resources/idls/curr-greetings-coll-fail.restspec.json, restli-tools/src/test/resources/idls/curr-greetings-coll-pass.restspec.json, restli-tools/src/test/resources/idls/prev-greetings-coll.restspec.json
This provides a way for client applications to batch multiple finder requests together into a single batch finder request to optimize downstream fanout.
=> Provide a way to link a finder with a functionally equivalent batch finder declaratively

CHANGELOG.md, data-avro/src/main/java/com/linkedin/data/avro/DataTranslator.java, data/src/main/java/com/linkedin/data/schema/compatibility/CompatibilityChecker.java, data/src/main/java/com/linkedin/data/schema/compatibility/CompatibilityMessage.java, data/src/test/java/com/linkedin/data/schema/compatibility/TestCompatibilityChecker.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateDataTemplateTask.java, gradle.properties
This is added to fail equivalent compatibility check and also avoid skipping publish snapshot/idl task which are only executed if snapshot/idl are not equivalent.
=> Add Enum symbols order change as compatible message in checker

CHANGELOG.md, data-avro/src/main/java/com/linkedin/data/avro/DataTranslator.java, data-avro/src/test/java/com/linkedin/data/avro/TestDataTranslator.java, gradle.properties
This PR updates data schema to avro translation to handle Data.Null value in pegasus DataMap and translate it to Avro null
=> Translate Data.null to Avro null if schema field is optional

CHANGELOG.md, data/src/main/java/com/linkedin/data/codec/AbstractJacksonDataCodec.java, gradle.properties
Some users have runtimes that pin jackson-core to older pre 2.10
versions. This introduces compatibility issues with the newer
JsonFactoryBuilder APIs. For the remaining jackson-core 2.x releases we
can continue to use the deprecated JsonFactory.enable/disable methods.
=> Avoid using JsonFactoryBuilder to be more compatible with pre 2.10 jackson at runtime

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/clients/FailoutClient.java, d2/src/test/java/com/linkedin/d2/balancer/clients/FailoutClientTest.java, gradle.properties
There was an extra call to `super.restRequest(request, requestContext, callback);` in FailoutClient.
Removing the extra call and adding unit tests
=> Fix FailoutClient invoking delegated client's restRequest twice

CHANGELOG.md, gradle.properties, restli-common/build.gradle, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/CollectionMetadata.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/CreateStatus.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/EmptyRecord.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/ErrorResponse.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/ExtensionSchemaAnnotation.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/Link.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/PegasusSchema.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/UpdateStatus.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/multiplexer/IndividualBody.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/multiplexer/IndividualRequest.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/multiplexer/IndividualResponse.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/multiplexer/MultiplexedRequestContent.pdsc, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/multiplexer/MultiplexedResponseContent.pdsc, restli-common/src/test/java/com/linkedin/restli/common/TestLegacyPdscEquivalence.java
This is required since PDSCs are still used in web products and Restli common models jar only packed PDL files. 
This PR manually adds translated PDSC files to the restli-common module as the auto-translation task can't be added due to the circular dependency of restli-tools on restli-common.
=> Translate restli-common PDL files to PDSC files to support legacy web use cases

CHANGELOG.md, gradle.properties, restli-server/src/main/java/com/linkedin/restli/internal/server/model/RestLiAnnotationReader.java, restli-server/src/test/java/com/linkedin/restli/internal/server/model/TestRestLiAnnotationReader.java
Finders can have linked batch finders associated with them. To ensure that the validation of these linked batch finders happens correctly, we need to process all the batch finder methods before the finder methods when processing annotations.
=> Handle method order when validating methods to ensure consistent linked batch finder validation

CHANGELOG.md, gradle.properties, r2-core/src/main/java/com/linkedin/r2/message/QueryTunnelUtil.java, r2-core/src/test/java/test/r2/message/TestQueryTunnel.java
This will filter out requests which use a non-HTTP verb for the content of X-HTTP-Method-Override.
=> Validate tunneling HTTP method override content.

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/clusterfailout/FailedoutClusterConnectionWarmUpHandler.java, d2/src/main/java/com/linkedin/d2/balancer/clusterfailout/FailedoutClusterManager.java, d2/src/main/java/com/linkedin/d2/balancer/clusterfailout/FailoutConfigProviderFactory.java, d2/src/main/java/com/linkedin/d2/balancer/clusterfailout/ZKFailoutConfigProvider.java, d2/src/test/java/com/linkedin/d2/balancer/clusterfailout/FailedoutClusterManagerTest.java, d2/src/test/java/com/linkedin/d2/balancer/clusterfailout/ZKFailoutConfigProviderTest.java, gradle.properties
Add a handler for handling warm up connections to peer clusters after watchers are established.
Since establishing connections can be expensive and all the clients need to connect to hosts in the downstream's peer clusters, by pre-establishing the connections, we can avoid the thundering herd effect of all clients trying to connect at the same time.
=> Add connection warmup handler

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/properties/ClusterStoreProperties.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ServiceStoreProperties.java, d2/src/test/java/com/linkedin/d2/balancer/properties/ClusterPropertiesSerializerTest.java, d2/src/test/java/com/linkedin/d2/balancer/properties/ServicePropertiesSerializerTest.java, gradle.properties
D2 clients with deprecated pegasus versions, `[29.22.12 to 29.30.0] inclusive`, will crash when reading ZK data pushed by `d2-config-service 3.x`, which includes canary configs fields but with null values when there is no canary configs. 
Many client apps are still on the deprecated versions, so we will modify the ZK serializers (both cluster and service) to only include non-null fields in ZK data. 
Please also see related d2-config-service RB which uses these new serializers and did integration tests to verify ZK data.
=> Serialize ZK data with non-null fields only

CHANGELOG.md, darkcluster/src/main/java/com/linkedin/darkcluster/impl/DarkClusterManagerImpl.java, gradle.properties
The current code has a bug in the dark request logic: the boolean `darkRequestSent` will be overwritten in the for loop, so it only reflects whether the request is sent to the last dark cluster configured. However, this boolean should be true if the dark request is sent to **any** of the dark clusters.
=> Bugfix: mark a dark request as sent if it is sent to any dark clusters

CHANGELOG.md, generator/src/main/java/com/linkedin/pegasus/generator/TemplateSpecGenerator.java, gradle.properties
Skip deprecation config will only remain in the direct input schema and not passed down recursively. This is to ensure there is no conflict behavior in common shared models between difference schema.
=> Ensure skip deprecation config is only applied to the direct input schema

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/jmx/D2ClientJmxManager.java, d2/src/test/java/com/linkedin/d2/jmx/D2ClientJmxManagerTest.java, gradle.properties
This is a follow-up PR for a [previous change](https://github.com/linkedin/rest.li/pull/782/files#diff-9993e287812781a541ea17425748df60fe6966b7a77ea69eba72fcf8a5890102) to add null checks for cluster and service properties in D2ClientJmxManager which caused NPE in some rare edge cases (when the cluster or service properties received from PropertyEventBus is null, as seen in EXC-320587 and SI-27628).
=> Add null-checks for cluster and service properties in D2ClientJmxManager

CHANGELOG.md, generator/src/main/java/com/linkedin/pegasus/generator/spec/PrimitiveTemplateSpec.java, generator/src/test/java/com/linkedin/pegasus/generator/TestTemplateSpecGenerator.java, gradle.properties
Prior to the change, `<PrimitiveTemplateSpec>.getBindingName()` returns null, this is because the PrimitiveTemplateSpec does not have its class name properly set.
=> Fix PrimitiveTemplateSpec not having className

CHANGELOG.md, data/src/main/java/com/linkedin/data/codec/entitystream/JacksonSmileStreamDataCodec.java, gradle.properties
Found another usage of a Jackson FactoryBuilder that causes some issues
for clients that pin jackson to an older version at runtime.
This PR is similar to #803
=> Avoid using SmileFactoryBuilder to be more compatible with pre 2.10 jackson at runtime

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerState.java, d2/src/main/java/com/linkedin/d2/balancer/clusterfailout/FailedoutClusterConnectionWarmUpHandler.java, d2/src/main/java/com/linkedin/d2/balancer/clusterfailout/FailedoutClusterManager.java, d2/src/main/java/com/linkedin/d2/balancer/clusterfailout/ZKFailoutConfigProvider.java, d2/src/main/java/com/linkedin/d2/balancer/simple/AbstractLoadBalancerSubscriber.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerState.java, d2/src/test/java/com/linkedin/d2/balancer/LoadBalancerTestState.java, d2/src/test/java/com/linkedin/d2/balancer/PartitionedLoadBalancerTestState.java, d2/src/test/java/com/linkedin/d2/balancer/StaticLoadBalancerState.java, d2/src/test/java/com/linkedin/d2/balancer/clusterfailout/FailedoutClusterManagerTest.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerStateTest.java, d2/src/test/java/com/linkedin/d2/discovery/event/PropertyEventBusTest.java, gradle.properties
When a failout is over or when a peer cluster is no longer accepting request, we should remove clusters/uris watches for that peer cluster to reduce the load on ZK:
* Cancels any pending connection warm-up requests
* Support cluster watches removal to be scheduled to sometime in the future to allow in-flight requests to finish.
* If there was no existing watches on the peer cluster, it's likely that cluster failout is the only consumer of the peer cluster info. Only remove the watches on the peer cluster if this is the case.
* Added a `stopListenToCluster` method to `LoadBalancerState`
* `SimpleLoadBalancerState` will invoke `ensureNotListening` on `cluster` and `uri` subscribers
=> Support removing cluster watches after failout is over

CHANGELOG.md, d2-test-api/build.gradle, gradle.properties
In https://github.com/linkedin/rest.li/pull/811, some new dependencies are introduced with the zookeeper upgrade. Tests depending on `d2-test-api` are failing to compile. Adding the missing dependencies to fix tests.
=> Fix d2-test-api dependencies

CHANGELOG.md, build.gradle, gradle.properties, restli-server/build.gradle, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceModelEncoder.java
Prior to Java 9, AppClassLoader is a subclass of URLClassLoader, but this is not the case after Java 9.
Therefore casting AppClassLoader to URLClassLoader will fail in Java 11.
This change removed related logic contains casting and instead use ClassGraph to search for restspec file instead.
=> Avoid casting classloader to URLLoader in ResourceModelEncoder to be compatible with Java 11

CHANGELOG.md, d2-int-test/build.gradle, d2/build.gradle, gradle.properties, restli-example-server/build.gradle
The updated ZooKeeper client depends on Netty, but uses a newer version.
Prior to that version Netty switched its netty-all Maven coordinates from
being a super jar to being a pom that transitively depends on the other
Netty dependencies. This makes it possible for it to bring in a conflicting
version of Netty, resulting in two versions in the classpath. ZooKeeper
appears fine with our current Netty version, so excluding the transitive
dependencies seems the safest way to ensure no issues are caused by
upgrading Netty to match the ZooKeeper version.
=> Exclude transitive Netty dependency for ZooKeeper client.

CHANGELOG.md, gradle.properties, restli-docgen/src/main/java/com/linkedin/restli/docgen/DefaultDocumentationRequestHandler.java, restli-docgen/src/main/java/com/linkedin/restli/docgen/NonBlockingDocumentationRequestHandler.java
Back in January, we changed the blocking DDRH to be non-blocking (fail requests sent during initialization)
to solve an edge-case issue of request thread pool exhaustion. This started causing a lot more complaints,
as many more use cases were now seeing errors for `OPTIONS` calls that would otherwise be successful.
This change brings back the old blocking behavior as default, and adds `NonBlockingDocumentationRequestHandler`
as a subclass of the DDRH which users can configure if they see thread pool exhaustion in their use case.
=> Revert DefaultDocumentationRequestHandler to be blocking again

CHANGELOG.md, generator/src/main/java/com/linkedin/pegasus/generator/JavaCodeGeneratorBase.java, gradle.properties
"notify" is an internal method in Object.java class, therefore if we don't sanitize it, there will be conflict when generating data template
=> add "notify" to reserved word set when generating date template

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/subsetting/ZKDeterministicSubsettingMetadataProvider.java, gradle.properties
This change will support supplying D2 subsetting peer cluster name at run-time, so that the service can automatically fill in the peer cluster name from the ZooKeeper announcers during server start-up.
=> Support supplying D2 subsetting peer cluster name at run-time

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/ZKConnection.java, gradle.properties
When apps have custom de-announcement, they may end up double de-announcing, and zk connection will be closed after the first de-announcement and throw errors at the 2nd de-announcement (not causing any issue in the app though). Here we update the error message for the exception to better guide the users.
=> Update the error message to better guide users when zkRef is null

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/validation/ValidateDataAgainstSchema.java, data/src/main/java/com/linkedin/data/schema/validation/ValidationOptions.java, data/src/test/java/com/linkedin/data/schema/validation/TestValidation.java, gradle.properties, restli-common/src/main/java/com/linkedin/restli/common/validation/RestLiDataValidator.java
Some clients cannot encode fixed values as avro encoded strings and instead use base64 encoding. Currently, these fail validation in the RestliValidationFilter. 
Provide an option to customize the validation options used in the filter, and add a validation option to fix base64 encoded fixed values.
=> Add a validation option to coerce base64 encoded fixed values

CHANGELOG.md, gradle.properties, restli-server/src/main/java/com/linkedin/restli/internal/server/methods/arguments/ActionArgumentBuilder.java
This is useful for cases that want to customize validation of action arguments.
=> Expose an easy way to override validation options for ActionArgumentBuilder

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/ZKConnection.java, gradle.properties
As titled, we used to catch the exception and log a debug message for async-shutdown only. But it was reported for regular shutdown as well. It's safe to catch the exception instead of throwing for all shutdown.
=> Catch exceptions when connection state change event is received after ZK connection shutdown

d2/build.gradle, data/src/test/java/com/linkedin/data/TestData.java
- Internal apis encapsulated starting 1.9, exporting jvmstat
- Updated constructor calls, deprecated in newer versions of Java
=> Java 11 - export jvm stat for java version >= 1_9

d2/build.gradle
Follow-up to #834, jvm stat needs to be exposed for the javadoc task as well for java 1.9+
=> [Java 11] Export jvm stat in :d2:javadoc

CHANGELOG.md, gradle.properties, r2-netty/src/main/java/com/linkedin/r2/netty/client/HttpNettyClient.java, r2-netty/src/main/java/com/linkedin/r2/netty/client/HttpNettyClientJmx.java, r2-netty/src/main/java/com/linkedin/r2/netty/client/HttpNettyClientJmxMBean.java
There can be a misleading situation where DNS resolution is timing out due to host system DNS issues, which present as request timeouts in the error messages. In these situations the request is actually never made, since the DNS resolution is done within the same timeout boundaries as the request. This will clarify the error messages and also makes it possible to use JMX metrics to track DNS latency.
=> Add support for r2 Netty client DNS metrics, and clarify timeout errors for DNS timeouts.

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperAnnouncer.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperServer.java, d2/src/main/java/com/linkedin/d2/discovery/event/D2ServiceDiscoveryEventHelper.java, d2/src/main/java/com/linkedin/d2/discovery/event/LogOnlyServiceDiscoveryEventEmitter.java, d2/src/main/java/com/linkedin/d2/discovery/event/NoopServiceDiscoveryEventEmitter.java, d2/src/main/java/com/linkedin/d2/discovery/event/ServiceDiscoveryEventEmitter.java, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStore.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperServerJmx.java, d2/src/test/java/com/linkedin/d2/balancer/properties/UriPropertiesTest.java, d2/src/test/java/com/linkedin/d2/balancer/servers/ZooKeeperServerTest.java, d2/src/test/java/com/linkedin/d2/balancer/servers/ZookeeperConnectionManagerTest.java, d2/src/test/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStoreChildrenWatcherTest.java, d2/src/test/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStoreTest.java, d2/src/test/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperPermanentStoreTest.java, d2/src/test/java/com/linkedin/d2/util/TestDataHelper.java, gradle.properties
Reference schemas in previous avro-schema RB, design doc at "[WIP][INDIS] End-to-End Monitoring Design".
Emit service discovery status related events at:
1) (de)announcements
2) when received updated host list (emit for each URI). 
3) first time requesting the host list for a cluster on cache miss. 
Note: will add tests once implementation is approved. Will add corresponding container part code soon.
=> Emit service discovery status related events

CHANGELOG.md, restli-server/src/main/java/com/linkedin/restli/server/CollectionResult.java, restli-server/src/main/java/com/linkedin/restli/server/GetResult.java, restli-server/src/main/java/com/linkedin/restli/server/UpdateEntityResponse.java, restli-server/src/main/java/com/linkedin/restli/server/UpdateResponse.java, restli-server/src/test/java/com/linkedin/restli/server/TestCollectionResult.java, restli-server/src/test/java/com/linkedin/restli/server/TestConstants.java, restli-server/src/test/java/com/linkedin/restli/server/TestGetResult.java, restli-server/src/test/java/com/linkedin/restli/server/TestRecordTemplateClass.java, restli-server/src/test/java/com/linkedin/restli/server/TestUpdateEntityResponse.java, restli-server/src/test/java/com/linkedin/restli/server/TestUpdateResponse.java
Add equals and hashCode methods to CollectionResult, GetResult, UpdateResponse and UpdateEntityResponse. This is helpful to client's unit tests as it compares value instead of reference.
=> Add equals and hashCode methods to classes

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/balancer/LastSeenBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/ZKFSLoadBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperAnnouncer.java, d2/src/main/java/com/linkedin/d2/balancer/zkfs/ZKFSTogglingLoadBalancerFactoryImpl.java, d2/src/main/java/com/linkedin/d2/discovery/event/D2ServiceDiscoveryEventHelper.java, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStore.java, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/builder/ZooKeeperEphemeralStoreBuilder.java, d2/src/test/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStoreChildrenWatcherTest.java, d2/src/test/java/com/linkedin/d2/util/TestDataHelper.java, gradle.properties, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestHttpNettyStreamClient.java
In a previous PR: https://github.com/linkedin/rest.li/pull/835, there was a mistake that uses ZookeeperAnnouncer as a helper to emit service discovery status events for both server-side and client-side events (reference context about service discovery status events in the previous PR), but the announcer will only work for server-side events. This PR is to fix the client-side events for d2 client by adding the event emitter directly to ZookeeperEphemeralStore thru D2ClientConfig.
=> Add service discovery status event emitter to d2 client

data/src/main/java/com/linkedin/data/schema/IndentedPdlBuilder.java
In some scenarios, we have a PDL where we need to write a comment that looks like 
`Flavors for an elementary particle and a fundamental constituent of matter\n\nThis is to test multi-line comment`
This is a 3 line comment with an empty 2nd line. However, since the 2nd line is empty, we do not want a trailing whitespace on the right (see image below). This PR helps address this.
=> [rest.li] Update IndentedPdlBuilder to remove extra whitespace when writing a blank comment line

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/ClientSelector.java, d2/src/main/java/com/linkedin/d2/balancer/subsetting/SubsettingState.java, gradle.properties
- Change logging level of D2 cluster subsetting updates to DEBUG
- Only emit an INFO level log when subsetting is enabled for a new service
=> Change logging level of D2 cluster subsetting updates to DEBUG

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateRestClientTask.java, gradle.properties
This PR is to fix the Gradle 7 validation errors in GenerateRestClientTask when build a rest.li service
```
- Type 'com.linkedin.pegasus.gradle.tasks.GenerateRestClientTask' method 'generateLowercasePath()' should not be annotated with: @Optional, @Input.
Reason: Input/Output annotations are ignored if they are placed on something else than a getter.
- Type 'com.linkedin.pegasus.gradle.tasks.GenerateRestClientTask' property '_isRestli1BuildersDeprecated' has redundant getters: 'get_isRestli1BuildersDeprecated()' and 'is_isRestli1BuildersDeprecated()'.
Reason: Boolean property '_isRestli1BuildersDeprecated' has both an `is` and a `get` getter.
- Type 'com.linkedin.pegasus.gradle.tasks.GenerateRestClientTask' property '_isRestli1BuildersDeprecated' is missing an input or output annotation. …
```
=> Fix the Gradle 7 validation errors in GenerateRestClientTask

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateRestModelTask.java, gradle.properties
When build one product with Gradle 7, we see the error below:
```
A problem was found with the configuration of task ':<module>:generateRestModel' (type 'GenerateRestModelTask').
- Type 'com.linkedin.pegasus.gradle.tasks.GenerateRestModelTask' property 'idlDestinationDir' is annotated with @PathSensitive but that is not allowed for 'OutputDirectory' properties. 
Reason: This modifier is used in conjunction with a property of type 'OutputDirectory' but this doesn't have semantics. 
Possible solution: Remove the '@PathSensitive' annotation.
Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#incompatible_annotations for more details about this problem.
```
`@PathSensitive` doesn't make sense to `OutputDirectory` properties, this PR remove @PathSensitive from …
=> Remove @PathSensitive from property idlDestinationDir in GenerateRestModelTask

CHANGELOG.md, build.gradle, gradle.properties
https://nvd.nist.gov/vuln/detail/CVE-2022-42889
=> Upgrade Apache Commons Text to 1.10.0 as vulnerability fix (CVE-2022-42889)

CHANGELOG.md, gradle-plugins/build.gradle, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/CheckIdlTask.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/CheckRestModelTask.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/CheckSnapshotTask.java, gradle.properties
This PR enable task validation check in the build of the gradle plugin so no validation warning of Gradle tasks can pass the build now. 
I also fixed the existing validation errors, which are listed below:
```
> Task property validation failed. See https://docs.gradle.org/5.2.1/userguide/more_about_tasks.html#sec:task_input_output_annotations for more information on how to annotate task properties.
> Warning: Task type 'com.linkedin.pegasus.gradle.tasks.CheckIdlTask': property 'isEquivalent' is not annotated with an input or output annotation.
> Warning: Task type 'com.linkedin.pegasus.gradle.tasks.CheckIdlTask': property 'isModelCompatible' is not annotated with an input or output annotation.
> Warning: Task type 'com.linkedin.pegasus.gradle.tasks.CheckIdlTask': property …
```
=> Enable task validation check in the build of the gradle plugin and fix some validation errors with Gradle 7

CHANGELOG.md, gradle.properties, r2-int-test/src/test/java/test/r2/integ/clientserver/TestStreamingTimeout.java, r2-netty/src/main/java/com/linkedin/r2/netty/common/StreamingTimeout.java
This should help with determining the cause of the timeout. If the channel is not writable, then it is likely that the remote endpoint has stopped consuming date. Otherwise, the local endpoint is the likely culprit.
=> Add channel writability to streaming timeout exception

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/simple/ClusterLoadBalancerSubscriber.java, d2/src/main/java/com/linkedin/d2/balancer/simple/UriLoadBalancerSubscriber.java, gradle.properties
Recently, we have seen issues of D2 layer not able to notify Client layer when it receives data. So, we're working on adding some logs to help identify issues. This RB adds the missing info logs for receiving D2 Cluster and D2 URIs for the very first time. Same logging is already there for D2 Service.
=> Add additional logging to help tracing the receiving of initial D2 Cluster and D2 URIs

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/DataSchemaConstants.java, data/src/main/java/com/linkedin/data/schema/annotation/AnnotationCheckResolvedPropertiesVisitor.java, data/src/main/java/com/linkedin/data/schema/annotation/AnnotationEntry.java, data/src/main/java/com/linkedin/data/schema/annotation/DataSchemaRichContextTraverser.java, data/src/main/java/com/linkedin/data/schema/annotation/PathSpecBasedSchemaAnnotationVisitor.java, data/src/main/java/com/linkedin/data/schema/annotation/SchemaAnnotationValidationVisitor.java, data/src/main/java/com/linkedin/data/schema/annotation/SchemaVisitor.java, data/src/main/java/com/linkedin/data/schema/annotation/SchemaVisitorTraversalResult.java, data/src/main/java/com/linkedin/data/schema/annotation/TraverserContext.java, data/src/main/java/com/linkedin/data/schema/annotation/TraverserContextImpl.java, gradle.properties
The current schema traversal mechanism copies the ArrayDeque with all path specs and traverse specs. This creates huge allocations that are immediately garbage collected. The problem is acute in services like voyager-api where the anti-abuse filter uses this mechanism to traverse all schemas referenced directly by any rest.li resource. A sample JFR for example showed 124GB of allocs in ~3 minutes, which caused service startup performance to be materially affected.
This PR optimizes this mechanism by maintaining a single ArrayList internally and using integer limits to keep track of position in the list. It also changes the return type to List instead of ArrayDeque and returns an immutable list to avoid callers from modifying it.
=> Reduce memory allocations during rich schema traversal

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties
The `getArchivePath()` API doesn’t carry any task dependency and has been deprecated. Replace it with `getArchiveFile()` on Gradle 7,  but keep `getArchivePath()` to be backwards-compatibility with Gradle version older than 5.1.
If we don't make the fix, when build one of our product, we may see the warning
```
> Task :jeeves-api:checkForDuplicates
Execution optimizations have been disabled for task ':jeeves-api:checkForDuplicates' to ensure correctness due to the following reasons:
Gradle detected a problem with the following location: '/Users/yli4/dev/jeeves/build/jeeves-api/libs/jeeves-api-data-template-2.1.93.jar'. Reason: Task ':jeeves-api:checkForDuplicates' uses this output of task ':jeeves-api:mainDataTemplateJar' without declaring an explicit or implicit dependency. This can lead …
```
=> Replace the API call getArchivePath() with getArchiveFile() on Gradle 7 in the Pegasus Plugin

d2/src/main/java/com/linkedin/d2/balancer/clusterfailout/ZKFailoutConfigProvider.java
This assists higher level functions that need to gather data from all of the failout configs. It is left off the interface since the interface should support implementations which do not have a defined set of known clusters.
=> Expose enumeration of clusters to `ZKFailoutConfigProvider`.

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties
our IDL publish is gated by complicated logic, therefore sometimes compatible IDL **change** will not be published.
These two option can override these complicated logic and force publish IDL or Snapshot
=> add property option to force publish idl and snapshot

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/DataSchema.java, data/src/main/java/com/linkedin/data/schema/RecordDataSchema.java, gradle.properties
As fix for following issue
https://github.com/linkedin/rest.li/issues/879
=> change the innitialize size of resolvedProperties to 0 in order to save memory pre-allocated

CHANGELOG.md, data-avro/src/test/java/com/linkedin/data/avro/TestSchemaTranslator.java, data/src/main/java/com/linkedin/data/schema/AbstractSchemaParser.java, gradle.properties
Avro allows for self referential aliases (where the Avro alias is the same as the full name of the schema). This PR adds support for self referential aliases to SchemaTranslator, in particular `SchemaTranslator#avroToDataSchema`.
Added unit tests to test for this case
=> [SchemaTranslator] handle self-referential avro aliases

CHANGELOG.md, gradle.properties, r2-core/src/main/java/com/linkedin/r2/transport/http/server/AbstractAsyncR2StreamServlet.java, r2-core/src/main/java/com/linkedin/r2/transport/http/server/AsyncEventIOHandler.java, r2-core/src/main/java/com/linkedin/r2/transport/http/server/SyncIOHandler.java, r2-jetty/build.gradle, r2-jetty/src/main/java/com/linkedin/r2/transport/http/server/HttpJettyServer.java, r2-jetty/src/test/java/com/linkedin/r2/transport/http/server/TestAsyncLockup.java
There is currently a bug with the AsyncR2StreamServlet which can result in all Jetty worker threads getting blocked permanently.
Even in Async mode, the SyncIOHandler will block the Jetty worker thread until the request body has been fully read by the application. If the application does not read the request body, then the SyncIOHandler will unblock when the final byte of the response has been written. However, a Jetty worker thread is needed to write the response. If all worker threads are stuck in the same situation, then there will be no worker threads available to write a response, and thus no way for any of them to be unblocked.
To fix this issue, we will leverage the SyncIOHandler event loop to write the response. This way each request requires at most one worker thread in order to …
=> Fix Async R2 Servlet deadlock condition

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, gradle.properties
~55% of CPU usage consumed during getPotentialClients is used for constructing weightedUris as shown in the following flamegraph with the Stream collecting.
To minimize this operation, this change is to avoid doing it for clusters that don't have subsetting enabled.
=> Split getPotentialClients between subsetting and not-subsetting

CHANGELOG.md, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/data/ExtensionSchemaValidationCmdLineApp.java
This should be treated as a temporary solution to unblock certain ER users while particular bugs and feature gaps exist.
=> Allow `@ExcludedInGraphQL` annotation on extension schema fields

CHANGELOG.md, build.gradle, data-avro/src/main/java/com/linkedin/data/avro/util/AvroUtil.java, gradle.properties
OutputStrean.toString() decodes bytes using the system default encoding, which might not be unicode, resulting in corrupt text
=> use proper UTF8 encoding in AvroUtil.jsonFromGenericRecord, also deprecate AvroUtil and bump avro-util dependency

CHANGELOG.md, gradle.properties, restli-common/src/main/pegasus/com/linkedin/restli/common/ExtensionSchemaAnnotation.pdl, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/ExtensionSchemaAnnotation.pdsc
This is required due to new ER requirements where a 1-to-many injection on a subresource method needs to specify both query parameters and injected URN parts. Thus, using only "params" won't work.
=> Introduce @extension.injectedUrnParts ER annotation

r2-netty/src/main/java/com/linkedin/r2/netty/common/NettyRequestAdapter.java, r2-netty/src/main/java/com/linkedin/r2/netty/handler/common/ClientEntityStreamHandler.java, r2-netty/src/test/java/com/linkedin/r2/netty/common/TestNettyRequestAdapter.java
If the headers have a `null` value, this will throw an NPE from Netty. In the context of this call this gets caught without logging making the issue difficult to detect (it manifests as a request timeout). Making `null` values treated as empty strings avoids the exception.
=> Fix conversion of R2 headers to Netty headers in requests.

CHANGELOG.md, gradle.properties, r2-core/src/main/java/com/linkedin/r2/transport/common/AbstractClient.java, r2-core/src/test/java/com/linkedin/r2/transport/common/TestAbstractClient.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestHttpNettyStreamClient.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/stream/http2/TestHttp2NettyStreamClient.java
Fixing it to not override the content-length if the request is HEADER type.
This is resubmission of a previous PR #896
=> HEAD requests content-length is not based on the body as per the http spec.

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/SchemaToPdlEncoder.java, data/src/main/java/com/linkedin/util/LineColumnNumberWriter.java, data/src/test/java/com/linkedin/util/TestLineColumnNumberWriter.java, generator-test/src/test/java/com/linkedin/pegasus/generator/test/pdl/PdlEncoderTest.java, gradle.properties
Add ability to get the line and column numbers of schema elements written out by SchemaToPDL encoder.
=> Get line/col number in PDL schema encoder

CHANGELOG.md, gradle.properties, r2-core/src/main/java/com/linkedin/r2/message/RequestContext.java
It is possible to cause a `ConcurrentModificationException` in the `RequestContext` because we synchronize it by using `Collections.synchronizedMap()`, which only synchronizes individual reads/writes. When making a `RequestContext` copy we must iterate over the collection, allowing other threads to interrupt it by modifying the map during the operation.
This fix synchronizes the whole copy operation as well. The default
mutex used for synchronizing in a `SynchronizedMap` is `this`, so
synchronizing on the map itself guards against modification.
=> Improve synchronization on the R2 `RequestContext` local attributes.

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/ValidateExtensionSchemaTask.java, gradle.properties
This is done through creating an output file for the task, which contains the stdout and stderr
=> Make ValidationExtensionSchemaTask cacheable

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerWithFacilitiesDelegator.java, gradle.properties
Add missing interface method in LoadBalancerWithFacilitiesDelegator so `WarmupLoadBalancer` will be able to delegate the new interface methods to the underlying load balancer.
=> Add missing interface method in LoadBalancerWithFacilitiesDelegator

build.gradle
[rest.li](http://rest.li/) open source new version release has been failing because of this error: https://github.com/linkedin/rest.li/actions/runs/5340449592/jobs/9697574024
> Could not resolve all artifacts for configuration ':classpath'.
> Could not find org.jfrog.buildinfo:build-info-extractor-gradle:4.21.0.
Searched in the following locations:
- https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-extractor-gradle/4.21.0/build-info-extractor-gradle-4.21.0.pom
- https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-extractor-gradle/4.21.0/build-info-extractor-gradle-4.21.0.jar
=> Bump jfrog build-info-extractor-gradle to 4.32.0

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperServer.java, gradle.properties
This refactors ZookeeperServer, moving the functionality to generate a `UriProperties` object into a protected helper function. This makes the code slightly cleaner and also enables any class that extends `ZookeeperServer` to have access to every parameter that `ZookeeperServer` writes to ZK.
`ZooKeeperServerTest` continues to pass, and I've confirmed that the function gets full code coverage. We could also add unit tests specifically for this, though I've heard that [testing protected methods is an anti-pattern](https://stackoverflow.com/questions/5601730/should-private-protected-methods-be-under-unit-test)?
=> Refactor ZookeeperServer: put uri property building logic to a method

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/util/partitions/BasePartitionAccessor.java, d2/src/main/java/com/linkedin/d2/balancer/util/partitions/PartitionAccessorFactory.java, d2/src/test/java/com/linkedin/d2/discovery/util/TestD2Config.java, gradle.properties
This feature enables pass custom settings to custom partition accessor so that the custom partition accessor can be configured from the server side.
design doc is here https://docs.google.com/document/d/1m4xeawvNHIvfM927LvzFwg8l1RrYwDuOV7-7TMeoQNg/edit#heading=h.nrawpetlys1f
=> enable passing settings to custom partition accessor

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/idlgen/RestLiResourceModelExporter.java
Details: Allow creating rest model gradle tasks even if there are no IDL files are present at project evaluation time if `rest.idl.processEmptyIdlDir` is set to true for the project.
###Testing Done 
build
=> updated PegasusPlugin to still register restModel tasks even if IDL files dir is empty

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadStateManager.java, gradle.properties
For Pilot testing INDIS read path, we need to avoid the extra step of manually setting the log level to debug on test host. Given that the dual read mode will change very infrequently (only at testing), we set the log level to info.
=> Set log level of dual read mode changes to info

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadStateManager.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, gradle.properties
Currently, the dual read mode is logged about being updated without checking whether it's really updated or just setting with the same existing value. Since cluster dual read mode depends on incoming requests to trigger an update when d2 services under that cluster is called, the cluster dual read mode is logged on every request.
1. Fix the dual read mode logging to be logged only when there is an update.
2. When Ads stream is established, log about the Observer authority. It's just the DNS address. The resolved IP address should be logged in ManagedChannelImpl in grpc-core at:
`List<EquivalentAddressGroup> servers = resolutionResult.getAddresses();
channelLogger.log(ChannelLogLevel.INFO, "Address resolved: {0}", servers);`
QEI deployment with toki
=> Fix logging issues about dual read mode

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/LastSeenBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/ZKFSLoadBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadStateManager.java, d2/src/main/java/com/linkedin/d2/jmx/D2ClientJmxDualReadModeWatcherManager.java, d2/src/main/java/com/linkedin/d2/jmx/D2ClientJmxManager.java, d2/src/main/java/com/linkedin/d2/jmx/DefaultD2ClientJmxDualReadModeWatcherManagerImpl.java, d2/src/main/java/com/linkedin/d2/jmx/JmxManager.java, d2/src/main/java/com/linkedin/d2/jmx/NoOpD2ClientJmxDualReadModeWatcherManagerImpl.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, d2/src/test/java/com/linkedin/d2/jmx/D2ClientJmxManagerTest.java, gradle.properties, r2-int-test/src/test/java/test/r2/integ/TestJetty404.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestChannelPoolManagerFactorySharingConnection.java
Currently Jmx/sensors (load balancer, load balancer state, file stores, clusterInfo, serviceProperties, LoadBalancerStrategy, etc) are having the same name in ZK and xDS read flow. The current code intended to give [D2ClientJmxManager.java](https://github.com/linkedin/rest.li/pull/907/files#diff-9993e287812781a541ea17425748df60fe6966b7a77ea69eba72fcf8a5890102) a different prefix in xDS flow ("-xDS"), which had a bug in container and wasn't working. Even if worked, it would still break the jmx/sensors because depending on the dynamically changing dual read mode value, the primary source (ZK in OLD_LB_ONLY and DUAL_READ modes; xDS in NEW_LB_ONLY mode) should register the jmx/sensor names same as today, so that users can still monitor the same metrics. And, the secondary source should …
=> Dynamically switch jmx/sensor names based on dual read mode and source type

CHANGELOG.md, d2-int-test/build.gradle, d2/build.gradle, d2/src/main/java/com/linkedin/d2/balancer/util/LoadBalancerClientCli.java, gradle.properties
This is needed to allow us make restli compatible with Java 17. The only functionality that's removed is the ability to `resetTogglingStores` from the `LoadBalancerClientCli`, which is unused elsewhere in the codebase.
This change is needed for #929
=> Remove reset toggling stores option in LoadBalancerClientCli to remove Java 17 incompatible code

CHANGELOG.md, gradle.properties
Bumping the major version to 30 is technically the correct thing to do from a semver perspective when a public API is removed. However, it also has a huge impact that outweighs the API breakage in terms of propogating the change to all consumers. We feel like this tradeoff is acceptable.
=> Downgrade major version to 29

CHANGELOG.md, generator/src/main/java/com/linkedin/pegasus/generator/JavaDataTemplateGenerator.java, gradle.properties
This PR adds `@Nullable` annotation to the Java data template generator that generates getters and setters for pegasus data models. Specifically:
1. For setters with mode, add `@Nullable` annotations. E.g. `Foo.setBar(blah, SetMode mode)` => `Foo.setBar(@Nullable blah, SetMode mode)` since `Foo.setBar(blah, SetMode.REMOVE_IF_NULL)` is null-safe.
2. For getters with mode, add `@Nullable` annotation. E.g. `Foo.getBar(GetMode mode)` => `@Nullable Foo.getBar(GetMode mode)`  since `Foo.getBar(GetMode.IGNORE_NULL)` is null-safe.
PSM recently introduced NullAway (https://github.com/uber/NullAway) as a requirement for LMS MPs. However, the library caught several false positives on Rest.Li generated java code, specifically on the cases mentioned above due to missing annotations. Adding these …
=> Add @Nullable annotations for pegasus java getters and setters with mode

.github/workflows/build.yml, .github/workflows/publish.yml, CHANGELOG.md, gradle.properties
To maintain consistency, let's use a variable of type `matrix` in both `build.yml` and `publish.yml`, even though technically we don't need `matrix` in `publish.yml` since we are only using a **single** Java version to publish a RestLi version.
=> Keep the old convention in publish.yml

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerJmx.java, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerJmxMBean.java, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerMonitor.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/main/java/com/linkedin/d2/jmx/SimpleLoadBalancerJmx.java, d2/src/main/java/com/linkedin/d2/jmx/SimpleLoadBalancerJmxMBean.java, gradle.properties
We had issues where Observer accidentally deleted all cluster properties, but we weren't able to see that the client is failing to get clusters on any ingraph metric but only via digging into logs.
For dual read, we've been only monitoring when the data is mismatched, but not when data is received on side (like ZK) but not on the other side (like xDS).
1. Added service and cluster not found counter to simple load balancer jmx, which gets incremented when timeout happens at fetching the resource.
2. Added entry out-of-sync count to dual read monitoring, which gets incremented when data is either mis-match or received on one side but not on the other (until a new version is received on the first side), and gets decremented when the data matches.
=> add service/cluster-not-found count to simple load balancer jmx. And add entry-out-of-sync count to dual read monitoring.

CHANGELOG.md, gradle.properties, li-jersey-uri/src/main/java/com/linkedin/jersey/api/uri/UriComponent.java
**Background**
The root cause is that, after compiling ResLi in Java 11, the new Java 11 implementation was preferred over the Java 8 implementation. However, since the new implementation was introduced after Java 8, a NoSuchMethodError occurred for Java 8 consumers. To resolve the issue, we chose an implementation that exists in both Java 8 and Java 11.
**Changes**
This PR will apply the same fix to URIDecoderUtils.java as was done in the prior PR to [URIDecoderUtils.java](https://github.com/linkedin/rest.li/blob/master/restli-common/src/main/java/com/linkedin/restli/internal/common/URIDecoderUtils.java#L204).
**Tests Done**
Followed the instructions provided by the team who reported the issue and tested locally using curli command.
=> Fix ByteBuffer errors to be compatible with Java 8 runtimes

CHANGELOG.md, data-avro/src/main/java/com/linkedin/data/avro/DataTranslator.java, data/src/main/java/com/linkedin/data/codec/BufferChain.java, gradle.properties
**Background**
As a follow-up to the previous [PR](https://github.com/linkedin/rest.li/pull/937), I am conducting a more thorough search for potential ByteBuffer errors in RestLi.
**Changes**
Searched for usages of the following "problematic" methods and cast to Buffer based on suggestions from [stackoverflow](https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip). 
ByteBuffer position(int newPosition)
ByteBuffer limit(int newLimit)
ByteBuffer mark()
ByteBuffer reset()
ByteBuffer clear()
ByteBuffer flip()
ByteBuffer rewind()
**Tests Done**
Followed the instructions provided by the team who reported the issue and tested locally.
=> Fix the remaining ByteBuffer errors

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/main/proto/XdsD2.proto, d2/src/test/java/com/linkedin/d2/xds/TestXdsToD2PropertiesAdaptor.java, gradle.properties
We need to support D2 symlink (d2 single master/primary feature, [wiki](https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Multi-Colo+Single+Master+Fast+Failover#MultiColoSingleMasterFastFailover-D2SingleMasterSupport)) in INDIS flow. 
The current ZK flow handles symlinks implicitly in SymlinkAwareZookeeper, which captures the data of a symlink node, immediately get the data of the actual master node, and send the fetched data to the symlink node callback. It can't be shared with INDIS flow.  
For symlink clusters, the event bus subscribers, like "ClusterLoadBalancerSubscriber", "UriLoadBalancerSubscriber" subscribe to the symlinks ($FooClusterMaster), instead of the actual master node (FooCluster-prod-ltx1), we need to publish to event bus under the symlink names.
For other clusters, we …
=> Support d2 symlink node in indis flow

d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsToD2PropertiesAdaptor.java
Current Observer only has a symlink for cluster config /d2/clusters/$xxxMaster, but not a counterpart symlink for uri parent /d2/uris/$xxxMaster. In fact, since cluster symlink and uri parent symlink always point to the same actual node name, and it's a redundancy and a burden for the symlink-update tool to maintain two symlinks for the same actual node name. 
We optimize xds flow to use the cluster symlink to listen to the actual nodes for both cluster and uri parent.
Once all apps migrate off ZK flow, we don't need to maintain the uri parent symlink anymore.
updated unit tests.
=> simplify symlink subscription in xds flow

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, gradle.properties
Summary
--------
Fix three issues:
- `XdsClientImpl` currently fails to detect connection failure to the ADS server. Connection failure leads to no notification to the `StreamObserver` since `onError` and `onCompleted` are terminal notifications. Instead, the `onReady` notification needs to be relied on to detect successful connection establishment.
- There were some race conditions
- `startRpcStream` public method didn't use the single-threaded executor for execution. It also didn't check for an already existing stream, which could lead to multiple ads streams.
- It didn't account for backed off client state, when retries are exponentially backed off due to repeat failures. In such cases, stream could still get started due to external method calls.
- Allow passing custom executor for the …
=> Fixed race conditions and bugs in xds client

d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerMonitor.java
Fix an error in dual read data match logging. The logging for new LB (xDS) and old LB (ZK) should be flipped depending on which LB's data come in later.
=> fix dual read data match log

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/jmx/D2ClientJmxManager.java, d2/src/main/java/com/linkedin/d2/jmx/JmxManager.java, d2/src/main/java/com/linkedin/d2/jmx/XdsClientJmx.java, d2/src/main/java/com/linkedin/d2/jmx/XdsClientJmxMBean.java, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, gradle.properties
Add jmx metrics for xds connection lost, closed, reconnected counts, and its current status of being connected or not.
Will create a container PR to add the corresponding ingraph sensor for the same.
=> Add metrics about xds connection status and count

CHANGELOG.md, data/src/main/java/com/linkedin/data/template/FieldDef.java, gradle.properties
Sometimes `_dataSchema` could be very complex and makes computing hash code for this class extremely slow. Since all data fields participated in hash code calculation is final, we should able to calculate it at construction time and avoid paying the cost repeatedly.
=> Let FieldDef lazy-calculate and cache hash code

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/properties/ClusterPropertiesJsonSerializer.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ServicePropertiesJsonSerializer.java, d2/src/main/java/com/linkedin/d2/balancer/properties/UriPropertiesJsonSerializer.java, d2/src/main/java/com/linkedin/d2/balancer/properties/util/PropertyUtil.java, d2/src/main/java/com/linkedin/d2/discovery/PropertySerializer.java, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/SymlinkAwareZooKeeper.java, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/main/proto/XdsD2.proto, d2/src/test/java/com/linkedin/d2/xds/TestXdsToD2PropertiesAdaptor.java, gradle.properties
The initial intent of using D2Node was to pre-deserialize the JSON, but because there is no way for the rest.li client to actually leverage this, it simply re-serializes the JSON then deserializes it again. This causes memory pressure along with validation errors as numerical typesa get mungled.
=> Use Node instead of D2Node and D2URIMap instead of NodeMap for xDS flow

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, gradle.properties
According to benchmark results, this is creating significant garbage. Because this is not exposed as an external API, directly returning null instead of an Optional is safe and will be significantly less expensive.
=> Remove usage of Optional from SimpleLoadBalancer

CHANGELOG.md, gradle.properties, restli-common/src/main/pegasus/com/linkedin/restli/common/CursorPagination.pdl, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/CursorPagination.pdsc, restli-server/src/main/java/com/linkedin/restli/server/CursorCollectionResult.java
Add standardized models for cursor based pagination
=> Add standardized models for cursor based pagination

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerMonitor.java, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadStateManager.java, gradle.properties
We've seen the Cluster, Service, Uri properties OutOfSync metrics in DualReadLoadBalancer sensor being high for some apps (voyager-api-groups-dash, registration-mt, etc). The metric seems to increment on every update of the property (see attached screenshot of UriPropertiesOutOfSyncCount metric). It bumps up periodically, likely during downstream deployments.
This change added debug logs to when entries are added/compared in the dual read caches to further debug the issue.
Another change is for SI-36476 where D2ClientJmxManager tries to find the right jmx name for d2 services being removed at shutdown (the name depends on dual read mode), causing the executor for getting the dual read mode throws errors since it's already shut down. Added a check to skip getting dual read mode if the …
=> add debug log to dual read caches

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerState.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/RelativeLoadBalancerStrategy.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/StateUpdater.java, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/SymlinkUtil.java, d2/src/main/java/com/linkedin/d2/jmx/RelativeLoadBalancerStrategyJmx.java, d2/src/main/java/com/linkedin/d2/jmx/RelativeLoadBalancerStrategyJmxMBean.java, d2/src/main/java/com/linkedin/d2/jmx/SimpleLoadBalancerStateJmx.java, d2/src/main/java/com/linkedin/d2/jmx/SimpleLoadBalancerStateJmxMBean.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsToD2PropertiesAdaptor.java, gradle.properties
gcn-39955
After switched to observer-only mode, job-postings-mt was not able to make downstream calls to d2 services under a symlink cluster. We found that although the uri nodes were fetched correctly for symlink cluster, it was merged with the real cluster name, instead of the symlink cluster name (e.g: FooCluster-prod-ltx1 instead of $FooClusterMaster). The cluster name in the merged uri properties is used (by UriLoadBalancerSubscriber) to find d2 services associated with it, which fails since the services are managed under the symlink cluster name.
This change:
1. merges the uri properties under the symlink cluster name. 
2. report the uri properties to dual read monitoring under the symlink cluster name. 
3. removed the additional publishing under the real cluster name when it's …
=> fix publishing uri and cluster properties for symlink clusters

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/properties/UriPropertiesMerger.java, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStore.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, gradle.properties
As the title. In case bad uri property version is produced for any edge cases (connection loss, etc.), we want to warn that.
build and test
=> add warn logs about invalid property versions

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/util/hashing/MPConsistentHashRing.java, d2/src/main/java/com/linkedin/d2/xds/XdsChannelFactory.java, gradle.properties
Summary
---------
1. `dali --gridproxy` command (required for some apps' local deployment, for eg. `launchpad-mt`) sets up local port forwarding that's incorrectly detected as a proxy by the gRPC managed channel. The fix is to use a no-op proxy detector. See more details about the investigation here: https://jira01.corp.linkedin.com:8443/browse/SI-36671
2. Regarding https://jira01.corp.linkedin.com:8443/browse/SI-36497, there was a request to indicate the issue of unexpected library versions to the app owner since it can be very tough to figure out, due to the error happening during the class loading phase.
Testing Done
-----------
1. Deployed `launchpad-mt` locally with a pegasus snapshot and the xDS stream works fine now:
```
2023/12/19 11:26:28.522 INFO [XdsClientImpl] [Indis xDS …
```
=> Use no-op proxy detector for xDS gRPC managed channel builder

CHANGELOG.md, gradle.properties
As in the title. Container PR will require the new pegasus code. We need to bump the minor version so that MPs which bump container but pin pegasus to a lower version can get build errors (patch version difference won't work, need minor version bump) hinting to bump the corresponding pegasus version too. Otherwise, their build will succeed but the app will crash at runtime since the old pegasus doesn’t have the new code.
=> bump minor version

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, gradle.properties
As reported, some apps ramped to Indis timed out at warmup causing d2 client startup timeout, the warmup executor was a single-thread executor shared by ZK and Indis flow, leading to Indis warmup blocks ZK warmup.
While the RC fix will be reducing the rate limiting on Indis Observer, here we add a separate executor for indis warmup to prevent blocking/affecting ZK flow in the future.
build and test
=> Use a separate indis warmup executor service

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsToD2PropertiesAdaptor.java, gradle.properties
In a [previous PR](https://github.com/linkedin/rest.li/pull/956), we removed publishing to the original cluster name (e.g: FooCluster-prod-ltx1) for a symlink cluster ($FooCluster). But there could be edge cases that the original cluster was subscribed by direct curli calls (like calling the colo-suffixed service: d2://FooService-prod-ltx1) or hard-coded custom code.
This change add this publish back.
Unit tests.
Tested with QEI d2-proxy, 
call d2 service "accountBalances" (which is under cluster "$OmsServiceMaster"):
`curli -v "d2://accountBalances" --d2-proxy-url "http://localhost:21360/d2/" -X OPTIONS --force-insecure-d2`
HTTP/1.1 200 OK
< Content-Type: application/json
< x-linkedin-processing-colo: ei-ltx1
< x-linkedin-processing-machine: ltx1-app6705.stg.linkedin.com
(was able to …
=> add back publish under original cluster name for symlink cluster

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadStateManager.java, gradle.properties
For gcn-39955
After [indis-dual-read lix](https://trex.corp.linkedin.com/trex/test/2081511207/iteration/4770044) switched to observer-only mode, job-postings-mt was not able to make downstream calls to d2 services under a symlink cluster(This issue has been fixed by #956 . Then D2 team tried to switch dual-read mode [lix](https://trex.corp.linkedin.com/trex/test/2081511207/iteration/4770044) from `Observer-only` to `DUAL_READ`, but it failed for partial downstream services.
- create a new test lix: https://trex.corp.linkedin.com/trex/test/2081519814/iteration/4770028
- change lix name from si.indis.client_read_mode to indis_automation_test  in container
- job-postings-mt bump up container snapshot and test in local ei.
- mint build && mint build-cfg -f dev && mint deploy -f dev in …
=> Fix indis dual-read lix switch issue

CHANGELOG.md, d2-test-api/src/main/java/com/linkedin/d2/balancer/util/TestLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/balancer/LastSeenBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/ZKFSLoadBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerMonitor.java, d2/src/main/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancer.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, d2/src/test/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancerTest.java, d2/src/test/java/com/linkedin/d2/util/TestDataHelper.java, d2/src/test/java/com/linkedin/d2/xds/XdsToD2SampleClient.java, gradle.properties
Current warmup starts for both ZK and xDS regardless of dual read mode, and the logic of fetching dual read mode (service data) blocks the warmup timeout which fails app startup.
This change: 
1. make warmup to respect the dual read mode per d2 service.
2. move the blocking service data fetching logic into a separate task and set a timeout, so that it won't blocks the warmup timeout callback to be called (so startup still has a chance to complete).
3. add separate configs for Indis warmup timeout and concurrent requests. We could tune them in the future as needed depending on how rate limiting on Indis observer will go. And wait for indis warmup (thus use the indis warmup timeout config) under observer-only mode during startup (instead of waiting for zk warmup). 
4. add checks to dual …
=> Make warmup to respect dual read mode, and separate warmup configs for indis

CHANGELOG.md, gradle.properties, r2-netty/src/main/java/com/linkedin/r2/netty/client/http/HttpChannelPoolFactory.java, r2-netty/src/main/java/com/linkedin/r2/netty/client/http2/Http2ChannelPoolFactory.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/common/ChannelPoolFactory.java
Epoll domain sockets arent supported on M1 mac. In these cases Kqueue should be used. This changes the factories to check if epoll or kqueue is available when creating the domain socket channel.
=> Add support for domain socket on m1 mac

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerMonitor.java, d2/src/main/java/com/linkedin/d2/balancer/properties/UriProperties.java, d2/src/main/java/com/linkedin/d2/balancer/properties/UriPropertiesMerger.java, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStore.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/test/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerMonitorTest.java, d2/src/test/java/com/linkedin/d2/util/TestDataHelper.java, gradle.properties
Dual read monitoring have been having tons of false-positive uri property mismatches. We used a rate limiter logger which was flooded by uri logs and starved critical logs from service and cluster properties.
1. Eliminate two kinds of mismatches: 1)  uriSpecificProperties from xDS flow having inner empty maps will be treated the same as an empty uriSpecificProperties. 2) data read from FS has a version of "-1". Allow data match if (at least) one data is read FS.
2. Use unlimited logger for service and cluster property warn logs, while keep using a rate limiter logger for uri warn logs.
3. adjust log messages to show the property type, name, data and version, in both LBs clearly.
Unit tests.
Manual test with QEI d2-proxy. 
Log snippet shows the data matches sequence for service …
=> Adjust dual read monitoring data match logic and remove log rate limiter

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/compatibility/CompatibilityChecker.java, data/src/main/java/com/linkedin/data/schema/compatibility/CompatibilityMessage.java, data/src/test/java/com/linkedin/data/schema/compatibility/TestCompatibilityChecker.java, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/compatibility/CompatibilityInfoMap.java, restli-tools/src/main/java/com/linkedin/restli/tools/compatibility/CompatibilityReport.java, restli-tools/src/main/java/com/linkedin/restli/tools/idlcheck/CompatibilityInfo.java, restli-tools/src/main/java/com/linkedin/restli/tools/idlcheck/CompatibilityLevel.java, restli-tools/src/test/java/com/linkedin/restli/tools/snapshot/check/TestPegasusSchemaSnapshotCompatibilityChecker.java, restli-tools/src/test/pegasus/com/linkedin/restli/tools/pegasusSchemaSnapshotTest/BirthInfo.pdl, restli-tools/src/test/pegasusSchemaSnapshot/BirthInfo.pdl, restli-tools/src/test/pegasusSchemaSnapshot/compatibleSchemaSnapshot/BirthInfo.pdl, restli-tools/src/test/pegasusSchemaSnapshot/compatibleSchemaSnapshot/Date.pdl, restli-tools/src/test/pegasusSchemaSnapshot/incompatibleSchemaSnapshot/BirthInfo.pdl
Adding new enumeration values has special consideration in the compatibility checker. Even though such changes are compatible on the wire level (don't break deserialization for old clients), they are still considered backwards incompatible by the checker. The documentation explains why: `However, it’s still not possible to guarantee backward compatibility, even with the “$UNKNOWN” symbol available. It’s possible that clients did not handle the “$UNKNOWN” symbol in the best possible way, and even if they did it may be that they cannot do anything other than fail if they encounter a enum symbol they do not recognize.`
This patch adds a new parameter to the compatibility checker to handle this special scenario. Adding new enumeration values will still fail under the BACKWARDS and EQUIVALENT …
=> Add a WIRE_COMPATIBLE compatibility checker level

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsChannelFactory.java, gradle.properties
Instead of using the default "pick_first" policy, which always picks the first IP address returned by DNS, "round_robin" will pick a random starting point in the list of IPs. This will fix the very lopsided load seen on the xDS servers.
Here is the current traffic distribution with using `pick_first`:
=> Introduce new config to randomly pick the xDS server host

CHANGELOG.md, gradle.properties, r2-netty/src/main/java/com/linkedin/r2/netty/common/ChannelPipelineEvent.java, r2-netty/src/main/java/com/linkedin/r2/netty/entitystream/StreamReader.java, r2-netty/src/main/java/com/linkedin/r2/netty/handler/common/ChannelLifecycleHandler.java, r2-netty/src/main/java/com/linkedin/r2/netty/handler/common/ClientEntityStreamHandler.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestPipelineV2NettyClient.java
Currently, the r2-netty client recycles connections once the response body has been fully received. However, it is possible for a server to return a response before fully consuming the request body. In this case, the channel will be recycled before the request body has made it through the pipeline. If a subsequent request comes in before the prior request is complete, an [illegal state exception](https://gist.github.com/TylerHorth/623489b9805f35803c710dcd80fd9eae) is thrown by the netty http object encoder.
I created a unit test to reproduce the issue and updated the lifecycle handler to recycle the channel only after both the request and response are complete.
=> Fix r2-netty illegal state exception due to premature channel recycling

CHANGELOG.md, gradle-plugins/src/integTest/groovy/com/linkedin/pegasus/gradle/IntegTestingUtil.groovy, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/ChangedFileReportTask.java, gradle.properties
This PR makes restli plugin compatible with Gradle 8. To do it, the following changes are introduced:
- all deprecated API usages are replaced with non-deprecated analogs
This PR also bumps the major version to make a new release. The major version bump is necessary because the previous PR dropped support of some Gradle versions which breaks backward compatiblity.
local build ok
=> Make restli plugin compatible with Gradle 8 and create a new release

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/properties/UriPropertiesJsonSerializer.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/main/proto/XdsD2.proto, d2/src/test/java/com/linkedin/d2/balancer/properties/UriPropertiesSerializerTest.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsToD2PropertiesAdaptor.java, gradle.properties
1. Use the new tracingId field in xDS d2 proto for SD tracking events (previously, we were hard-coding the tracing id to zookeeper node path, which is invalid for Kafka data). 
2. Correct the version field in the tracking event (previously hard-coding to 0 for ZK data).
3. fix uri specific properties formatting in xds data. Before this fix, xDS uri properties put an empty map inside merged uriSpecificProperties for uris that don't have such property, leading to uri mismatches as described [here](https://docs.google.com/document/d/1phtGwYaQ6yuuqumS8lMZ8_Y5EkY11_R9bXZHzp0BX9E/edit#bookmark=id.i8523geqptmk).
1. Existing tests cover the uri publish logic, updated to cover the tracking events.
2. Manual tested with d2-proxy. Was able to make calls to downstream apps for both symlink and …
=> Use tracingId in xDS flow for SD tracking events

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerMonitor.java, gradle.properties
1. fix [SI-37741](https://jira01.corp.linkedin.com:8443/browse/SI-37741) - set this log to debug level instead of warn: the log that reports uri data being the same but the version is different. 
2. fix [SI-37667](https://jira01.corp.linkedin.com:8443/browse/SI-37667) - rate limit dual read failure logs, since its volume can be huge on high QPS apps.
existing tests
=> Fix excessive logs in uri data/version mismatch and dual read failure

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancer.java
For `samza job`, the LoadBalancer will be shutdown during running.
2024-02-28 22:28:49.469 [main] DynamicClient [INFO] shutting down dynamic client
2024-02-28 22:28:49.469 [main] DualReadLoadBalancer [INFO] New load balancer successfully shut down
2024-02-28 22:28:49.470 [main] ZKFSLoadBalancer [INFO] Shutting down
2024-02-28 22:28:49.470 [Indis xDS client executor-4-1] XdsClientImpl [INFO] Shutting down
More context could check from :
https://linkedin-randd.slack.com/archives/C033U0SJFEX/p1709165894672129?thread_ts=1709075763.043899&cid=C033U0SJFEX
[SI-37856](https://jira01.corp.linkedin.com:8443/browse/SI-37856)
As the `newLb executor` in `DualReadLoadBalancer` is shut down, so DualReadLoadBalancer throws exceptions when it’s already shutdown but gets new tasks submitted to it.  Then …
=> [INDIS]-check whether new load balancer executor is shutdown before using in dual-read mode

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/QuarantineManager.java, gradle.properties
For [SI-37856](https://jira01.corp.linkedin.com:8443/browse/SI-37856), dual read LB is submitting new tasks to new LB (xDS LB) during shutdown because the newLbExecutor was not shutdown aware (not created with standard scheduled executor factory, [code link](https://jarvis.corp.linkedin.com/codesearch/result/?name=D2ClientFactory.java&path=container%2Fpegasus%2Fpegasus-d2-client-factory%2Fsrc%2Fmain%2Fjava%2Fcom%2Flinkedin%2Fd2%2Fclient%2Ffactory&reponame=linkedin-multiproduct%2Fcontainer#1362)). The tasks (its timeout callbacks) are then submitted to the inner executor in simple LB, which is already shutdown, thus throws rejected execution exceptions, with stacktrace:
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFuture …
```
=> Shut down dualread executor properly and guard for rejected execution exceptions

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancer.java, gradle.properties
As the title, made the messages clearer that dual read errors won't affect apps' traffic. Also changed the log level from error to warn.
build and test
=> Clarify dual read error messages

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/xds/GlobCollectionUtils.java, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsToD2PropertiesAdaptor.java, gradle.properties
Implement efficient URI updates by leveraging glob collections. Instead of receiving the entire URI map from the observer every time, this allows receiving only the added/removed URIs in teh cluster. Each cluster is represented as a glob collection named:
```
xdstp:///indis.D2URI/{clusterName}/*
```
And the URI resource names (AKA resource URN) look like this:
```
xdstp:///indis.D2URI/{clusterName}/{query-escaped URI}
```
For testing, I reproduced the same testing steps listed in https://github.com/linkedin/rest.li/pull/975. Here is the attached log for d2-proxy: https://paste.corp.linkedin.com/show/68966295/
The requests are routed correctly, and both symlink and non-symlink clusters seem to be working just fine!
Here are the results of the curli requests: …
=> Glob collections implementation

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerTest.java, gradle.properties, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestChannelPoolManagerFactorySharingConnection.java
As the title said
- Fix the multiple onError calls in dual-read null guard logic
- Fefactor and add more strict unit test to make each `onError` method and `onSuccess` method will only be called one time.
- Catch up more potential exception for dual-read
- Try to fix some legacy unit test flaky failed issue
- [✅] Add more unit test condition to make sure each `onError` and `onSuccess` method will only be called one time.
-  [✅] Add more unit test condition to make sure handleTime... method will be called when timeout
=> Address the multiple onError calls in dual read and enhance unit test

CHANGELOG.md, build.gradle, gradle.properties
We found that for some samza mps([sitespeed-samza-beam](https://github.com/linkedin-multiproduct/sitespeed-samza-beam)  and [samza-pem](https://github.com/linkedin-multiproduct/samza-pem)), they are excluding the io.envoy module which will casued the INDIS xds stream initialization to fail.
`exclude group: 'io.envoyproxy.controlplane', module: 'api'`
The problem is the low version  io.envoyproxy.controlplane is shading instead of depending on an old version of opentelemetry-proto that’s not compatible with the lib that the team is using now. The compatability issue will cause the build failed, showing that  there is no ScopeMetrics class.
```java
> Task :samza-yarn-jobs:samza-pem-degradation-tracking:compileJava
/Users/sying/products/samza-pem/samza-yarn-jobs/samza-pem-degradation-tracking …
```
=> upgrade io.envoyproxy.controlplane module to 0.1.35 to fix compatibility issue

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/properties/ServicePropertiesJsonSerializer.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerTest.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsToD2PropertiesAdaptor.java, d2/src/test/java/com/linkedin/d2/xds/XdsToD2SampleClient.java, gradle.properties
Client app could define [client side service config override](https://jarvis.corp.linkedin.com/codesearch/result/?name=prod.src&path=learning-api%2Fconfig%2Fapp%2Flearning-api-chat%2Fgroups&reponame=linkedin-multiproduct%2Flearning-api#22) to override transport client properties set in server side d2 config (if listed in allowedClientOverrideKeys). This functionality was implemented in ZK flow by applying the client side override to the d2 service properties when deserializing it after received from ZK. INDIS flow currently is broken since the client side override is not set to the d2 service (de-)serializer in INDIS flow.  
This change:
1. Fix applying client side service config override in INDIS flow
2. Clean up build time warning in SimpleLoadBalancer and XdsToD2SampleClient. 
(Note …
=> Fix applying client side service config override in INDIS flow

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties
In Gradle 8, the build might sometimes fail if two or more projects attempt to resolve the same configuration of the third project simultaneously. In fact, reading from the configuration of other projects is considered a bad practice and will be prohibited starting from Gradle 9. To fix the products that fail with this issue in Gradle 8 and make plugin compatible with Gradle 9, this PR introduces a local proxy configuration that serves as a medium for accessing the configuration of the other projects.
- local build ok
- confirmed that this change fixes the projects that were failing before
=> Fix the concurrent configuration resolution error in Gradle 8 and above

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsToD2PropertiesAdaptor.java, gradle.properties
We recently added emitting SD status update receipt event for receiving URI data updates (previously only add/remove URI will emit the event). Turns out that increased the event volume a lot ---- apps like seas do URI data updates very frequently (weight, uri specific properties, etc.) and have both large fleet size and large audience group (hence huge fanout). Considering that having the events for add/remove URI is good enough for analyzing SD end-to-end propagation latency, and including the URI data updates could cause unmanageable pressure on the data analysis pipeline, such as Kusto query, inlogs, etc, we could exclude the URI data updates from emitting events. 
Updated existing tests.
=> Remove emitting SD event for receiving URI data update

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerJmx.java, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerJmxMBean.java, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerMonitor.java, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadStateManager.java, d2/src/main/java/com/linkedin/d2/balancer/dualread/UriPropertiesDualReadMonitor.java, d2/src/test/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerMonitorTest.java, d2/src/test/java/com/linkedin/d2/balancer/dualread/UriPropertiesDualReadMonitorTest.java, d2/src/test/java/com/linkedin/d2/jmx/D2ClientJmxManagerTest.java, d2/src/test/java/com/linkedin/d2/xds/XdsToD2SampleClient.java, gradle.properties, pegasus-common/src/main/java/com/linkedin/util/RateLimitedLogger.java
Previous dual read matches URI properties only when the versions are the same (same ZK data served from ZK vs Observer), but with Kafka data served, the version will never be the same. And the OutOfSync metric was never useful since only one version of uri properties is cached for each cluster, when uri data changes frequently, the OutOfSync increases and never comes down.
This new URI matching now produces a similarity metric which represents the fraction of matching uris present in the ZK response and the observer response, just the same as how observer is monitoring the cluster uri similarity. The similarity metric may go up during downstream deployment/updates, but eventually it should be 1. The goal is to verify that client side response processing logic in INDIS is not causing uri …
=> Implement new DualReadMonitor for UriProperties

CHANGELOG.md, gradle.properties, r2-core/build.gradle, r2-core/src/main/java/com/linkedin/r2/transport/http/common/HttpBridge.java, r2-core/src/test/java/test/r2/transport/http/common/TestHttpBridge.java
This change adds logic in `HttpBridge` to return `RetriableRequestException` rather than `RemoteInvocationException` when StreamException from Netty is returned with cause of `Maximum active streams violated for this endpoint`. This allows the downstream client - `RetryClient` to retry the request with different hosts when stream hits the maximum of a given host.
[wc-test passed](https://crt.prod.linkedin.com/#/testing/executions/b4c75c5a-b5c9-4a4d-93da-2ebae16484e6)
=> Return RetriableRequestException for Netty Max Active Stream error

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/balancer/LastSeenBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/ZKFSLoadBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/clients/DegraderTrackerClientImpl.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClientFactory.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClientImpl.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancerState.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/RelativeLoadBalancerStrategyFactory.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/StateUpdater.java, d2/src/main/java/com/linkedin/d2/balancer/zkfs/ZKFSTogglingLoadBalancerFactoryImpl.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsFsTogglingLoadBalancerFactory.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, d2/src/test/java/com/linkedin/d2/balancer/clients/RetryClientTest.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/StateUpdaterTest.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/TrackerClientMockHelper.java, d2/src/test/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStoreChildrenDelayedWatcherTest.java, degrader/build.gradle, degrader/src/main/java/com/linkedin/util/degrader/DegraderImpl.java, degrader/src/main/java/com/linkedin/util/degrader/ErrorType.java, degrader/src/test/java/com/linkedin/util/degrader/DegraderImplTest.java
H/2 stream errors were seen in recent incidents and they aren't handled by the Tracker client currently. Handle `Http2Exception.StreamException` to fix this.
Added UTs
=> Handle HTTP/2 stream errors in tracker client and LB state updator

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/simple/UriLoadBalancerSubscriber.java, gradle.properties
Uri subscriber can receive duplicate uri properties during INDIS migration as both ZK data and Kafka data are input on INDIS Observer (using ZK data to cover server apps that don't emit or partially emit kafka data). Since Kafka data has higher precedence, when Kafka data arrives later than ZK data, it will be sent to the client although the uri properties inside is effectively the same as ZK data, which is still needed, since the metadata is different, like tracing ID, modified time, etc, the client will send tracking events of receipt to track the end-to-end propagation latency for Kafka announcements.
This change only prevents uri subscriber from processing the inner duplicate uri properties as an update, which will prevent all subsequent actions taken by the uri property listeners. …
=> Prevent duplicate uri property update

d2/src/main/java/com/linkedin/d2/balancer/simple/ClusterLoadBalancerSubscriber.java, d2/src/main/java/com/linkedin/d2/balancer/simple/ServiceLoadBalancerSubscriber.java, d2/src/main/java/com/linkedin/d2/balancer/simple/UriLoadBalancerSubscriber.java, d2/src/main/java/com/linkedin/d2/discovery/stores/file/FileStore.java
As the title. Add these logs for detecting potential issues and debugging. If the null guard in property event bus works as expected and xDS server sends valid data, these logs should NEVER appear (except the harmless one in FileStore).
unit tests
=> Add warn logs for receiving null properties

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/jmx/XdsClientJmx.java, d2/src/main/java/com/linkedin/d2/jmx/XdsClientJmxMBean.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java, gradle.properties
As the title, add a metric when the xds resource received is invalid.
Existing tests. QEI deploy d2-proxy, the metrics showed up on jmx console.
=> Add xds client metric for receiving invalid resource

d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java
Copied from the Slack context (thanks Bohan for the writeup):
Summary: we looked into the bad host's log and our xds client code. There is an issue in the reconnect logic. When a reconnect ads stream is closed/rejected for stream limit on an observer A, the stream ready timeout for this stream was not cancelled before it retries with another observer B. So that after the stream with observer B becomes ready, the ready timeout for observer A was executed which cleaned the stream with observer B. This leads to the client enables backup (FS) store and never tries to connect with the observer again.
```
2024/06/20 10:07:00.204 INFO [XdsClientImpl] [Indis xDS client executor-4-1] [followfeed-query] [AAYbT3nOcB56sIf0OjkOIg==] ADS stream started, connected to server: …
```
=> Better handling of stream retries on fast disconnects

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, gradle.properties
See context at [slack discussion](https://linkedin-randd.slack.com/archives/C02LGUWBLU8/p1718914811474299?thread_ts=1718903018.359899&cid=C02LGUWBLU8). 
This change:
1. cleans up xds stream ready timeout future when that stream is closed (instead of being ready). 
2. align xds connection status metric with what the connection listeners receive (in the previous edge case, the connected is indeed good, but the listeners are mis-notified that it's not connected).  
3. cleans up connection retry future when that reconnection stream is ready.
4. After all, if similar issues happen in future where xds stream is actually ready and taking in updates but the event bus is incorrectly enabled with backup store, updated XdsToD2PropertiesAdaptor will notify that xds is reconnected when it receives an …
=> Cancel xds stream ready timeout when the stream is closed. Correct xds connection status metric.

CHANGELOG.md, build.gradle, gradle.properties
Update grpc version to 1.59.1 and protobuf to 3.24.0 
gRPC changes with 1.59.0 https://groups.google.com/g/grpc-io/c/HdrAVplyw7U/m/ki4QQkwOAQAJ
ProtoBuf changes with 3.24.0 https://groups.google.com/g/protobuf/c/mbfAytlUapY/m/n6Ex9uscDAAJ
Tests: tested RC version in dataformats/grpc-infra wc-test.
=> Update grpc version to 1.59.1 and protobuf to 3.24.0

CHANGELOG.md, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/data/ExtensionSchemaValidationCmdLineApp.java, restli-tools/src/test/extensions/validCase/BazExtensions.pdl, restli-tools/src/test/pegasus/DummyKeyWithGrpc.pdl
To help bridge rest.li with gRpc as part of the gRpc migration, this PR allows @extension and @grpcExtension extensions to co-exist in the same schema. More information can be found in [SI-39662](https://jira01.corp.linkedin.com:8443/browse/SI-39662).
I added a unit test to check if @extension and @grpcExtension extensions can co-exist in the same schema. I depend on the previous existing tests to check for backwards compatibility.
=> Allow both @extension and @grpcExtension extensions in schema validation

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/ValidateExtensionSchemaTask.java, gradle.properties, restli-tools/src/test/java/com/linkedin/restli/tools/data/TestExtensionSchemaValidationCmdLineApp.java
When testExtensionSchemaValidation tests fail, the reason behind those failures are not logged. This PR replaces `Assert` with `SoftAssert` to always output the reason for failure in the unit tests. Below are some example outputs:
Before change:
```
Failure message for com.linkedin.restli.tools.data.TestExtensionSchemaValidationCmdLineApp > testExtensionSchemaValidation[0](validCase, true, null):
The following asserts failed:
expected [true] but found [false]
```
After change:
```
Failure message for com.linkedin.restli.tools.data.TestExtensionSchemaValidationCmdLineApp > testExtensionSchemaValidation[0](validCase, true, null):
The following asserts failed:
expected [true] but found [false],
expected [null] but found [versionSuffix value: 'V3' does not match the versionSuffix value which …
```
=> Increase verbosity of testExtensionSchemaValidation tests

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, gradle.properties
For the `_executorService` in the `xdsClientImpl`, there is no try/catch for the `xds stream initialization` so the runtime exception is swallowed and hard to find out the root cause for INDIS connect creation failed. Here we add the `try/catch` to the `startRpcStreamLocal` to get the error for debugging more convinient in the future.
📔: I have also tried to `setUncaughtExceptionHandler` to the `_executorService` in container, like
```java
final ScheduledExecutorServiceFactory.Cfg xdsExecutorServiceCfg = new ScheduledExecutorServiceFactory.Cfg();
xdsExecutorServiceCfg.traceContext = "xdsExecutor";
xdsExecutorServiceCfg.threadType = ServiceCallExecutorService.ThreadType.WORKER;
xdsExecutorServiceCfg.threadFactory = new NamedThreadFactory("Indis xDS client executor", new …
```
=> Add try/catch logic for xds stream initialization

d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancer.java, d2/src/main/java/com/linkedin/d2/xds/balancer/DualReadZkAndXdsLoadBalancerFactory.java, d2/src/test/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancerTest.java
1. Fixed a warm-up test about deleting files after shutdown. 
2. Some dual read related tests for WarmUpLoadBalancer has been flaky. Since dual read will be deprecated soon, disable these tests to smooth the release. 
3. As we get close to complete INDIS migration, marking dual read LB as deprecated to note that no new reference to it should be created anymore.
=> Remove some dual read related tests and deprecate dual read LB

CHANGELOG.md, build.gradle, d2/src/test/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancerTest.java, gradle-plugins/src/integTest/groovy/com/linkedin/pegasus/gradle/PegasusPluginCacheabilityTest.groovy, gradle-plugins/src/integTest/groovy/com/linkedin/pegasus/gradle/PegasusPluginIntegrationTest.groovy, gradle.properties
=> Disable the d2 warmup flaky test and deprecated  jcenter 

pegasus-common/src/main/java/com/linkedin/common/callback/CompletableFutureCallbackAdapter.java, pegasus-common/src/test/java/com/linkedin/common/callback/TestCompletableFutureCallbackAdapter.java, restli-client/src/main/java/com/linkedin/restli/client/Client.java
Add utility methods for bridging Rest client with CompletableFuture
=> Add utility methods for bridging Rest client with CompletableFuture

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsToD2PropertiesAdaptor.java, gradle.properties
When switching from the backup to the primary store (implemented in the XdsClientImpl), the data in the primary store is never replayed. This is different from the backup store behavior which respects the invocation of startPublishing and replays the contents of the store. This means that if the contents of the backup store are different from the contents of the primary store, and the client switches from the backup to the primary, the client will only see the backup values and not the primary values.
=> Respect `startPublishing` call by always re-notifying watcher in XdsClientImpl

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, gradle.properties
The RetryTask did not resubscribe to glob collections after a reconnect. Instead it goes back to map subscriptions. This change honors the glob collection config in the retry task.
=> Respect glob collection subscriptions on reconnect

CHANGELOG.md, d2-int-test/src/test/java/com/linkedin/d2/loadbalancer/TestDynamicClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/test/java/com/linkedin/d2/balancer/clients/TestBackupRequestsClient.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java, gradle.properties, test-util/src/main/java/com/linkedin/test/util/retry/TenRetries.java
As the title says, things weren't wired through correctly for glob collections, namely they were being ignored because they were triggering the check for whtehre the cluster is being watched at all. This fixes that (and the fact that the initial subscription did not respect the `useGlobCollections` flag). This change has been unit tested and tested through in restli-resource-explorer, and it works for both glob and non-glob.
=> Fix invalid handling of glob collections for wildcard subscribers

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerServer.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ConnectionManager.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperAnnouncer.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperConnectionManager.java, deprecate.sh, gradle.properties
add kafka announcement only logic
More context and test could be found here:
https://github.com/linkedin-multiproduct/container/pull/1162
=> add kafka announcement only logic

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperAnnouncer.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperConnectionManager.java, gradle.properties, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestHttpNettyClient.java, r2-netty/src/test/java/com/linkedin/r2/transport/http/client/TestHttpNettyStreamClient.java
=> Restore the old constructor to avoid incompatible issue

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperAnnouncer.java, darkcluster/src/main/java/com/linkedin/darkcluster/impl/DarkClusterManagerImpl.java, darkcluster/src/test/java/com/linkedin/darkcluster/TestDarkClusterManager.java, gradle.properties
Description
----
Sending dark traffic during dark warmup is risky since it can result in the calls being sent back to the same hosts, resulting in a cycle.
Changes:
- Use `ZookeeperAnnouncer` in dark cluster utils to ensure that no dark requests are sent while any of the announcers is in warmup mode (and the app is receiving some dark traffic).
Testing
-------
Added UT.
=> Disable dark traffic dispatching during dark warmup

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperAnnouncer.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperAnnouncerJmx.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperAnnouncerJmxMXBean.java, d2/src/test/java/com/linkedin/d2/balancer/servers/TestZooKeeperAnnouncer.java, gradle.properties
Announcer weight has been a double with no limit rules. Technically, a maximum of 100, and at most 2 digits after the decimal point should be sufficient to serve all load distribution needs in reality. With INDIS observer serving Envoy clients which require an integer uri weight, unlimited double number will cause conversion complexity that should never be encountered in real use case. In this PR, we add a max weight config which defines the max value and the number of decimal places allowed. We also added another config for the action to take when the weight rule is breached. It can be configured to ignore, log warn msg, throw exception, or rectify the value.
Note that this change will warn invalid weights set dynamically thru ZookeeperAnnouncerJmx as well.
Also added jmx methods to …
=> check and warn for invalid partition weight

CHANGELOG.md, data/src/main/java/com/linkedin/data/ByteString.java, gradle.properties
This PR is published on behalf of Misha Dmitriev.
These changes are aimed at improving the efficiency and accuracy of the byte iteration process within the ByteString class. By eliminating unnecessary  object allocation from `new object (ByteIterator)` for every byte in a string that it searches.
Unit test passed
=> Optimize in ByteString to prevent excessive object allocation

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerServer.java, d2/src/main/java/com/linkedin/d2/balancer/servers/AnnouncerStatusDelegate.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperAnnouncer.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperConnectionManager.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperServer.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperAnnouncerJmx.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperAnnouncerJmxMXBean.java, gradle.properties
1. Added announcer status delegate interface and implemented it in ZooKeeperAnnouncer to reflect its status.
2. Made LoadBalancerServer reports its announcing mode: statically announcing or dynamically announcing (could change at runtime) to the old or new service registry, or both. 
3. Added ZooKeeperAnnouncer's JMX method to report its server's announcing mode.
All changes are to support the container [PR](https://github.com/linkedin-multiproduct/container/pull/1253).
See container [PR](https://github.com/linkedin-multiproduct/container/pull/1253) for UT and qei deploy test.
=> Add announcer status delegate interface and support getting server announce mode

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsDirectory.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancer.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, d2/src/main/proto/XdsD2.proto, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java, d2/src/test/java/com/linkedin/d2/xds/balancer/TestXdsDirectory.java, gradle.properties
Support getting d2 service and cluster name lists from INDIS with Xds load balancer. This is needed by some apps (like d2-proxy) that need to read the names to migrate to INDIS read. 
Note that observer hasn't supported the resource D2ClusterOrServiceName yet, so build and test are failing.
UT. QEI test with d2-proxy. The names is fetched and served correctly.
=> Add XdsDirectory to get d2 service and cluster names from INDIS

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsDirectory.java, d2/src/test/java/com/linkedin/d2/xds/balancer/TestXdsDirectory.java, gradle.properties
We don't want all apps to subscribe to d2 cluster / service names at startup, which could be a bit waste. This change makes the subscription lazy to happen at when first real request comes in. INDIS Server response is very fast, so it should be ok to subscribe lazily.
UT.
=> Make xds directory lazy to subscribe names

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/GlobCollectionUtils.java, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java, gradle.properties
This new endpoint on `XdsClient` allows one to watch a single URI using the glob collection interface. The watcher will be notified whenever the URI changes or is deleted, which allows for lightweight watches of a singular URI instead of needing to watch the entire cluster.
I was able to test this against a local Observer deployment, and validated that the URI updates and deletions are correctly propagated.
=> Allow subscribing to a single D2URI

CHANGELOG.md, d2-test-api/src/main/java/com/linkedin/d2/balancer/util/TestLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancer.java, d2/src/test/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancerTest.java, gradle.properties
We recently observed a bug with some users of D2 where:
1. During warmUp all their calls to `WarmUpLoadBalancer.getClient` would time out due to [the call in ZKDeterministicSubsettingMetadataProvider timing out](https://github.com/linkedin/rest.li/blob/master/d2/src/main/java/com/linkedin/d2/balancer/subsetting/ZKDeterministicSubsettingMetadataProvider.java#L128). 
2. Because the `service` was added to the set of `_usedServices` **after** the getClient call, it would never be added
3. Upon shutdown, that service was considered unused and its warm up backup store was deleted (even though it was eventually populated after warmUp).
This is wrong, as we should consider a service used even if the `getClient` call fails. I fixed this by moving the logic to add the service to the used services …
=> Resiliency: mark a service as used even if the getClient call during warmUp fails

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, gradle.properties
As the title, so that users of the raw D2ClientBuilder and D2ClientConfig can be aware of the required migration.
Also log a warning when the d2 client being built is not INDIS-based. As we've migrated ~98% of Offspring standard d2 client usages, it's good to add this warning to help migrating the long-tailing non-standard clients.
N/A
=> deprecate ZK-related methods in D2ClientBuilder and D2ClientConfig

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancer.java, gradle.properties
There have been reports that somehow this map is failing to track the usage of all services (see LPS-33281 for an internal ticket). Make it concurrency safe to see if that fixes the issue.
Stacktrace (relevant sections) below. Notice `WarmUpLoadBalancer.getClient`:
```
2025/03/05 00:25:32.272 WARN [ZKDeterministicSubsettingMetadataProvider] [R2 Callback Executor-2-10] [games-mt] [AAYvjWxkeX4PfPf6iaMF6g==] Failed to fetch deterministic subsetting metadata from ZooKeeper for cluster GamesMt
java.util.concurrent.TimeoutException: null
at com.linkedin.common.callback.FutureCallback.get(FutureCallback.java:79) ~[com.linkedin.pegasus.pegasus-common-29.64.1.jar:?]
at com.linkedin.d2.balancer.subsetting.ZKDeterministicSubsettingMetadataProvider.getSubsettingMetadata(ZKDeterministicSubsettingMetada …
```
=> Use concurrent set for used service bookkeeping

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/main/java/com/linkedin/d2/balancer/util/D2ExecutorThreadFactory.java, gradle.properties
A deadlock can happen when Indis/ZK data isn't available for some downstream. In that case, the calls made to that downstream get buffered (the respective callbacks get added to the [ClosableQueue](https://github.com/linkedin/rest.li/blob/5602d2b880e93eb0e61e759fd4e0ebfd184527cf/r2-core/src/main/java/com/linkedin/r2/util/ClosableQueue.java)) until Indis/ZK executor thread finally gets the data and executes all the queued callbacks. However, since the callbacks are for active RPCs, some of them may require getting the cluster subsetting metadata, which is a [blocking call](https://github.com/linkedin/rest.li/blob/5602d2b880e93eb0e61e759fd4e0ebfd184527cf/d2/src/main/java/com/linkedin/d2/balancer/subsetting/ZKDeterministicSubsettingMetadataProvider.java#L128). Since fetching this data …
=> Fix deadlock in R2 calls due to cluster subsetting data fetching

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, gradle.properties
In #1047 the `ForkJoinPool` common pool was used to execute d2 callbacks. However, as it turns out, the fork join pool may already be busy making RPCs (https://github.com/linkedin/venice/pull/1478) and it may result in _yet another deadlock_. To fix that issue, this change:
1. Adds a dedicated executor for d2 callbacks which isn't called from anywhere else.
2. Uses `Executors.newCachedThreadPool` for creating the executor, making it deadlock resistant. Assuming that this executor's threads would still end up making RPCs somewhere in the app code, it could result in more deadlocks otherwise.
Example of deadlocked `ForkJoinPool` (it's being used to make RPCs which need the same threadpool to be free to execute callbacks):
```
"ForkJoinPool.commonPool-worker-2" #28 daemon prio=5 os_prio=0 …
```
=> Use dedicated executor service for d2 callbacks

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, gradle.properties
As the title, to avoid excessive error exception tickets created to the app owner, where nothing needs their attention or action, since the stream will be re-established with another indis observer.
N/A
=> SI-37780, Change log level of ads stream closure from err to warn

r2-core/src/main/java/com/linkedin/r2/message/QueryTunnelUtil.java, r2-core/src/test/java/test/r2/message/TestQueryTunnel.java
The Java Mail code that is used for query tunneling creates an invalid Content-Type header for multipart/mixed encoded requests, containing a newline, return, and tab character (e.g. multipart/mixed; \r\n\tboundary="----=_Part_0_1587908352.1744332411531"). This isn't compliant with HTTP RFCs and the Netty client has become more strict about validating header values. This change replaces any whitespace of two or more characters with a single space.
Tests for encoding a request have been updated to validate the Content-Type doesn't contain invalid characters, and existing tests decoding these encoded requests continue to pass.
=> Remove invalid characters from multipart/mixed encoded requests

CHANGELOG.md, d2-schemas/src/main/pegasus/com/linkedin/d2/ConnectionOptions.pdl, d2-schemas/src/main/pegasus/com/linkedin/d2/D2Cluster.pdl, d2/src/main/java/com/linkedin/d2/balancer/properties/ClusterProperties.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ClusterPropertiesJsonSerializer.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ClusterStoreProperties.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ConnectionOptions.java, d2/src/main/java/com/linkedin/d2/balancer/properties/PropertyKeys.java, d2/src/test/java/com/linkedin/d2/balancer/properties/ClusterPropertiesSerializerTest.java, gradle.properties
Add options to d2 config for connection jittering. Will be used by the gRPC client to add random delay when establishing new connections to avoid a thundering herd problem.
=> Add options for connection jitter

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/xds/GlobCollectionUtils.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java, d2/src/test/java/com/linkedin/d2/xds/XdsToD2SampleClient.java, gradle.properties
Adding support for [Intial_resource_version](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/discovery/v3/discovery.proto#envoy-v3-api-field-service-discovery-v3-deltadiscoveryrequest-initial-resource-versions) in xdsClient implementation. 
if Intial_resource_version is used. This will help to enable same logical xDS session even in stream reconnection. xds server will only reply back with the resources which has changed and skipping the resource which xDS client already aware of (based on the resource version being send in request).
More Details: https://docs.google.com/document/d/1fKNQBqbQDmZcYaSCnaXBnyEApN-WReNSfay5-6dVoV4/edit?tab=t.0#heading=h.psi98t855m9r
1. unit tests. 
2. tested with INDIS-canary against the observer in ei fabric. 
```
2025/04/14 12:44:25.490 WARN …
```
=> Adding IRV support for reconnect scenario

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java, gradle.properties
Add support for updating D2 URIs in glob collections. Clients subscribed with glob collection enabled can now receive updated and removed URIs.
[✅]unit test
```
./gradlew :d2:test --tests  TestXdsClientImpl
```
will update/test the feature in restli-resource-explorer, and used by `indis-zk-writeback` services.
=> check uris change for glob collections update

CHANGELOG.md, gradle.properties, restli-client/src/main/java/com/linkedin/restli/client/ProjectionDataMapSerializer.java, restli-client/src/main/java/com/linkedin/restli/internal/client/QueryParamsUtil.java, restli-client/src/test/java/com/linkedin/restli/internal/client/TestQueryParamsUtil.java
This is so we can intercept String & DataMap projections before they're sent downstream
Added unit tests to cover the new functionality
=> Enhanced ProjectionDataMapSerializer interface to expose serialization functionality for String & DataMap projections

d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java
We discovered an edge case where the `AdsStream`'s onError callback can be called **after** the `_executorService` has been shut down, which leads to a `RejectedExecutionException` being thrown, which the caller might not expect or be able to handle.
To avoid this, let's protect calls to the `_executorService` with a check on whether it's already been shut down.
1. Added a test `testExecutorServiceNotUsedAfterShutdown` which passes
2. Checked out the current version of `XdsClientImpl` from master and verified `testExecutorServiceNotUsedAfterShutdown` **fails** with `java.util.concurrent.RejectedExecutionException` (confirms that the test is in fact verifying the new behavior)
=> Don't call _executorService.execute on new tasks once the XdsClient has been shut down

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancer.java, gradle.properties
During the shutdown of xdsLoadBalancer, several important resources are not being properly released:
- **R2 Transport Layer**: The R2 transport client is not explicitly shut down. This may leave threads and network resources lingering.
- **gRPC Resources**: The gRPC ManagedChannel and its associated event loop groups are not properly terminated. As a result, gRPC worker threads remain alive.
**These omissions can lead to a situation where non-daemon threads continue running, preventing the JVM from exiting cleanly.** In Hadoop-based environments, this can cause job hangs, as the process appears to be stuck with active runnables.
Below is a thread dump captured during such a hang, highlighting the lingering threads:
```
"main@1" prio=5 tid=0x1 nid=NA runnable
java.lang.Thread.State: …
```
=> fix shutdown issue for xdsLoadBalancer

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStore.java, d2/src/main/java/com/linkedin/d2/discovery/util/D2Utils.java, gradle.properties
To explicitly catch more dev/testing app paths to be excluded from creating znode for raw d2 client builder users, and only check once at startup instead of every zk uri queries.
QEI deploy indis-canary, verified that the log about creating znode "setting up node for rawClientTracking with name: xxx" no longer shows up:
=> detect more dev/testing app paths for raw d2 cient builder

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/discovery/util/D2Utils.java, gradle.properties
updating AppIdentityName logic
for avoiding multiple node creation for samza/yarn jobs, updating AppIdentityName to use app.name as node identifier, if it present, if not then it will fall back to use user.dir property.
=> updating AppIdentityName logic

d2/src/main/proto/XdsD2.proto
This adds fields to the proto definition of D2Uri which specify the hostnames, IP addresses, and whether these IPs are in an app's cert. 
We are doing this for a couple of reasons:
1. These fields can be used by either the service discovery server (which we are implementing presently) or the service discovery client (which is not currently planned or implemented, but could be in the future) to decouple service discovery from DNS by making routing decisions directly on the IP address instead of the hostname or nodeUri. 
2. This D2URI schema is duplicated internally and we are adding these new fields to the internal version, so we must keep it in sync here or risk proto deserialization issues
=> Add fields to D2Uri which support IP-for-hostname substitution in nodeUri

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, gradle.properties
The d2 client configs from container for xds channel load balancing policy were never passed into the xds channel factory. This bug was introduced in https://github.com/linkedin/rest.li/pull/979. This change fixes this bug.
QEI deploy indis-canary. See the connected INDIS observer:
```
2025/06/20 08:56:48.422 INFO [XdsClientImpl] [Indis xDS client executor-15-1] [indis-canary] [AAY4AujhIIuaxXGX/yNpXA==] Successfully received response from ADS server: ltx1-app10343.stg.linkedin.com
```
, restart indis-canary, See the client connected to another observer: 
```
2025/06/20 09:42:49.354 INFO [XdsClientImpl] [Indis xDS client executor-15-1] [indis-canary] [AAY4A41xk8DBnEbVjp7QGQ==] Successfully received response from ADS server: ltx1-app10448.stg.linkedin.com
```
=> fix passing in xds channel load balancing policy

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/simple/SafeCustomAffinityRoutingURIProviderDecorator.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, d2/src/test/java/com/linkedin/d2/balancer/simple/SafeCustomAffinityRoutingURIProviderDecoratorTest.java, gradle.properties
Summary
---------
Add `SafeCustomAffinityRoutingURIProviderDecorator` to safely call user-supplied `CustomAffinityRoutingURIProvider` implementations. This is needed to avoid deadlocked requests since any exceptions thrown from here aren't caught and they result in the executor thread being killed.
Testing Done
---------
Added UTs
=> Handle exceptions thrown from CustomAffinityRoutingURIProvider

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperAnnouncer.java, d2/src/main/java/com/linkedin/d2/discovery/util/D2Utils.java, gradle.properties
1. log full announcement data so that app users can observe announcement changes in weight/partition, uri specific properties, etc.
2. For raw d2 client tracking, 
1) use samza container name if present, for apps like: samza.container.name = waterloo-member-company-standardizer.
2) remove random string parts in the user.dir, such as:
`/export/content/lid/apps/seas-cloud-searcher/11ed246acf2e0be26bd44b29fb620df45ca14481` 
and
`/grid/g/tmp/yarn/usercache/seascloud/appcache/application_1747631859816_3737754/container_e42_1747631859816_3737754_01_000011`
=> log full announcement data at markup. Use samza container name and process user dir for tracking raw d2 client

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/LastSeenBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/ZKFSLoadBalancerWithFacilitiesFactory.java, gradle.properties
To solve the issue that consumer app owners doesn't know which library is creating zk-reading raw d2 client in their app,
log an error with the call stack, so that consumer app owner and us will see exactly which code is creating zk-reading raw d2 client.
QEI deploy indis-canary, see the error log shows the call stack.
2025/08/01 11:03:53.085 ERROR [D2ClientBuilder] [main] [indis-canary] [] [ACTION REQUIRED] Using Zookeeper-reading raw D2 Client. WILL CRASH in OCTOBER 2025. See instructions at go/onboardindis.
Using in stack: java.base/java.lang.Thread.getStackTrace(Thread.java:1607)
com.linkedin.d2.balancer.D2ClientBuilder.build(D2ClientBuilder.java:108)
com.linkedin.indis.canary.grpc.RawD2Client.createRawD2Client(RawD2Client.java:40) …
=> add error log for raw D2 client call stack

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, gradle.properties
As a followup to previous PR https://github.com/linkedin/rest.li/pull/1085, use isIndisOnly in LoadBalancerWithFacilitiesFactory to check if the load balancer is indis-only read, instead of checking if it's an instance of XdsLoadBalancerWithFacilitiesFactory. Since some [user app code](https://jarvis.corp.linkedin.com/codesearch/result/?name=RestClientFactoryUtils.java&path=nuage-sdk%2Fnuage-sdk%2Fsrc%2Fmain%2Fjava%2Fcom%2Flinkedin%2Fnuagesdk%2Futil&reponame=linkedin-multiproduct%2Fnuage-sdk#118) is wrapping a XdsLoadBalancerWithFacilitiesFactory inside a CallTrackingLoadBalancerFactory. 
Created a [container PR](https://github.com/linkedin-multiproduct/container/pull/1847) to let CallTrackingLoadBalancerFactory returns isIndisOnly from its inner wrapped factory.
QEI deploy indis-canary
=> Add isIndisOnly to LoadBalancerWithFacilitiesFactory

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/IPv6AwarePickFirstLoadBalancer.java, d2/src/main/java/com/linkedin/d2/xds/XdsChannelFactory.java, d2/src/test/java/com/linkedin/d2/xds/IPv6AwarePickFirstLoadBalancerTest.java, d2/src/test/java/com/linkedin/d2/xds/XdsToD2SampleClient.java, gradle.properties
This new policy, registered under `ipv6_aware_random_pick_first`, is smart enough to only shuffle the addresses within their group. In other words, instead of shuffling IPv4 addresses in between IPv6 addresses, it shuffles the IPv6 and IPv4 addresses independently, and an additional property determines whether IPv4 addresses should appear before IPv6 addresses (defaults to IPv6 first).
=> Introduce new IPv6 aware Pick First policy

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java, gradle.properties
As the title, add null guards for critical params. Also add a setter to disable detecting raw d2 client, so test apps like indis-canary can use it to disable the detection as needed.
N/A
=> null guards for xds server and channel
