linkedin/rest.li

README.md
Minor cosmetic change on README file.
=> [docs] Editorial changes on README.md

guide_restli_server.md, reference_return_entity.md
This adds documentation for the BATCH_PARTIAL_UPDATE return entity scenario.
=> [docs] Add documentation for BATCH_PARTIAL_UPDATE return entity

guide_restli_client.md
Forgot to add an entry for this feature in the request builders functionality table in the client user guide.
=> [docs] Edit documentation for BATCH_PARTIAL_UPDATE return entity

DATA-Data-Schema-and-Templates_converted.md
The format of the tables and code blocks are disordered. Standardized the their formats.
=> Fix the format issue of all tables and code blocks

Attachment-Streaming_converted.md, _data/user_guide_navigation.yml, unstructured_gudie.md
- Add Unstructured data user guide
- Fix Unstructured data step by step tutorial
=> Unstructured data guide

guide_restli_server.md
Clarifying this because of ask ticket caused by inaccurate documentation.
=> Clarify section on collection pagination link generation

step_by_step.md
=> Fixing a broken link on rest.li's step by step guide

protocol.md
=> Fix broken link about online documentation

Compression.md, How-to-use-projections-in-Java_converted.md, Rest_li-Filters.md, Writing-unit-tests-for-Rest_li-clients-and-servers.md, _config.yml, _data/api_reference_navigation.yml, batch_finder_resource_method.md, guide_restli_client.md, guide_restli_server.md, modeling.md, protocol.md, testsuite_overview.md
- Add batch_finder resource method
-  Fix broken link and typo
=> Add documentation for BATCH_FINDER

Dynamic-Discovery.md, Rest_li-with-Servlet-Containers_converted.md
=> Fix a couple broken links that I missed

Asynchronous-Servers-and-Clients-in-Rest_li.md, guide_restli_server.md, modeling.md
**Modeling docs:** 
-Add information about async templates available for use.
**Async docs:**
-Refactor documentation to recommend Task/Async templates, since Promise template is deprecated.
**Testing:**
-jekyll serve to check formatting & links.
=> Edit modeling & asynchronous documentation to recommend Async.

guide_service_errors_java.md, reference_service_errors.md
Make a few edits to pages related to the Service Errors feature.
=> [docs] Make edits to the service errors documentation

gradle.md
Update generateAvroSchema task documentation to include a required configuration that enables the task.
=> Update generateAvroSchema task documentation

protocol.md
This PR is to fix a layout issue in example responses on Rest.li Protocol page.
=> Fix the layout issue in example respones on Rest.li Protocol page

_data/user_guide_navigation.yml
=> Fix PDSC and PDL URIs

_plugins/pdl_highlighter.rb
Implemented a custom Rouge lexer to support PDL syntax highlighting.
**Note:** Split this up from the other PR (#161) for clarity, though the highlighting changes won't actually show up until both are merged.
=> Support syntax highlighting for PDL code snippets

data/src/main/java/com/linkedin/data/schema/PdlBuilder.java, data/src/test/java/com/linkedin/data/schema/TestPdlBuilder.java, data/src/test/java/com/linkedin/data/schema/TestSchemaToPdlEncoder.java
Change pdl property encoding logic to not flatten if nested branches > 1
=> Change pdl property encoding logic to not flatten if nested branches > 1

data/src/main/java/com/linkedin/data/schema/SchemaToPdlEncoder.java, generator-test/src/test/java/com/linkedin/pegasus/generator/test/pdl/PdlEncoderTest.java, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/enums/EscapedSymbols.pdl, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/imports/Includes.pdl, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/imports/InlineTypeConflict.pdl
Also improves how imports for includes are handled.
=> Fix bug that would cause pdl encoder to import types conflicting with inline types.

data/src/main/java/com/linkedin/data/schema/SchemaToPdlEncoder.java, generator-test/src/test/java/com/linkedin/pegasus/generator/test/pdl/PdlEncoderTest.java, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/imports/ConflictResolution.pdl, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/imports/Fruits.pdl, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/imports/NamespaceOverrides.pdl, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/imports/ReferenceTypeConflict.pdl, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/imports/dummy/EscapedSymbols.pdl
Unit tests added for coverage.
=> Fix bug in PDL encoding logic for imports when there are conflicting types in use.

build.gradle, data-avro-1_6/build.gradle, data-avro-1_6/src/main/java/com/linkedin/data/avro/AvroAdapter_1_6.java, data-avro/build.gradle, data-avro/src/main/java/com/linkedin/data/avro/AvroAdapter.java, data-avro/src/main/java/com/linkedin/data/avro/AvroAdapterChooser.java, data-avro/src/main/java/com/linkedin/data/avro/AvroAdapterFinder.java, data-avro/src/main/java/com/linkedin/data/avro/AvroAdapter_1_4.java, data-avro/src/main/java/com/linkedin/data/avro/DataTranslator.java, data-avro/src/main/java/com/linkedin/data/avro/SchemaTranslator.java, data-avro/src/main/java/com/linkedin/data/avro/util/AvroUtil.java, defaultEnvironment.gradle
With avro-util 0.1.8 released and ELRed, this PR is ready to merge
=> Update AVRO compat layer in pegasus to use adapters from avro-util

gradle.properties
Bumping gradle.properties to create a new  version.
=> bump gradle.properties

gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateRestClientTask.java
Use PathingJarUtil to prepare manifest-only JAR for invocations of GenerateRestClientTask
- Avoids `"error=7, Argument list too long"` runtime errors
=> Use manifest-only JAR for GenerateRestClientTask

README.md
This PR should also trigger the PR test workflow.
=> Add Jekyll build status badge to README.md

src/assets/main.scss, src/pdl_migration.md
Forgot to add this back when I fixed the highlighting.
=> Add highlighting to side-by-side PDSC/PDL code blocks

src/step_by_step.md
Also add the config needed to enable PDL.
=> Fix pegasus version number in step-by-step guide

data/src/main/java/com/linkedin/data/schema/CompactPdlBuilder.java, data/src/main/java/com/linkedin/data/schema/IndentedPdlBuilder.java, data/src/main/java/com/linkedin/data/schema/PdlBuilder.java, data/src/test/java/com/linkedin/data/schema/TestPdlBuilder.java, generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/escaping/PropertyKeyEscaping.pdl
Manually tested JSON indent, can not add those test cases till we have the deterministic ordering of properties.
=> pretty print json in pdl builder

restli-common/src/main/java/com/linkedin/restli/common/ComplexResourceKey.java, restli-common/src/test/java/com/linkedin/restli/common/TestComplexResourceKey.java, restli-int-test-api/src/main/pegasus/com/linkedin/restli/examples/typeref/api/CustomDoubleRef.pdsc, restli-int-test-api/src/main/snapshot/com.linkedin.restli.examples.greetings.client.typerefCustomDoubleAssociationKeyResource.snapshot.json, restli-int-test-server/src/main/java/com/linkedin/restli/examples/RestLiIntTestServer.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestTyperefCustomDoubleAssociationKeyResource.java, restli-server/src/main/java/com/linkedin/restli/internal/server/RestLiMethodInvoker.java, restli-server/src/main/java/com/linkedin/restli/internal/server/RestLiRouter.java, restli-server/src/main/java/com/linkedin/restli/internal/server/RoutingResult.java, restli-server/src/main/java/com/linkedin/restli/internal/server/methods/arguments/ArgumentBuilder.java, restli-server/src/main/java/com/linkedin/restli/internal/server/util/ArgumentUtils.java, restli-server/src/main/java/com/linkedin/restli/server/BaseRestLiServer.java, restli-server/src/main/java/com/linkedin/restli/server/RestLiConfig.java, restli-server/src/main/java/com/linkedin/restli/server/config/ResourceMethodConfig.java, restli-server/src/main/java/com/linkedin/restli/server/config/ResourceMethodConfigImpl.java, restli-server/src/main/java/com/linkedin/restli/server/config/ResourceMethodConfigProvider.java, restli-server/src/main/java/com/linkedin/restli/server/config/ResourceMethodConfigProviderImpl.java, restli-server/src/main/java/com/linkedin/restli/server/config/RestLiMethodConfig.java, restli-server/src/main/java/com/linkedin/restli/server/config/RestLiMethodConfigBuilder.java, restli-server/src/main/java/com/linkedin/restli/server/config/RestLiMethodConfigImpl.java, restli-server/src/test/java/com/linkedin/restli/internal/server/methods/arguments/RestLiArgumentBuilderTestHelper.java, restli-server/src/test/java/com/linkedin/restli/internal/server/methods/arguments/TestArgumentBuilder.java, restli-server/src/test/java/com/linkedin/restli/internal/server/methods/arguments/TestCollectionArgumentBuilder.java, restli-server/src/test/java/com/linkedin/restli/server/test/TestRestLiMethodInvocation.java, restli-server/src/test/java/com/linkedin/restli/server/test/TestRestLiRouting.java
I had deleted the fork, raising the PR again. 
Refer https://github.com/linkedin/rest.li/pull/176 for initial comments.
=> Add resource key validation while parsing

gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, restli-tools/src/main/java/com/linkedin/restli/tools/data/SchemaFormatTranslator.java
- Add option to skip verification.
- Don't failfast on errors while loading schemas.
- Write schemas failing verification to temp location to diff them
easily.
- Strip trailing whitespaces in PDL.
=> Improvements to the PDL translation task.

r2-core/src/main/java/com/linkedin/r2/transport/http/client/AsyncPoolImpl.java, r2-core/src/test/java/test/r2/transport/http/client/TestAsyncPool.java
Update the default connection creation timeout to 10s from 2s
This will be made configurable in a subsequent release
=> Update the default connection creation timeout to 10s from 2s

gradle.properties
Bump version in preparation for release
=> Bump version in preparation for release

build.gradle, d2-int-test/src/test/java/com/linkedin/d2/quorum/ZKPeer.java, d2-int-test/src/test/java/com/linkedin/d2/quorum/ZKQuorum.java, d2/src/main/java/com/linkedin/d2/balancer/util/RateLimitedLogger.java, gradle.properties
Bump Zookeeper Client from 3.4.6 to 3.4.13
=> Bump ZK Client from 3.4.6 to 3.4.13

README.md, src/Projections_converted.md, src/README.md
A fix on the projection wiki for URL format needed for projection
http://juncwang-ubuntu-vm:4000/rest.li/Projections#array-1
=> Fix an error in Projection page. Also edit server launch instruction.

gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/data/SchemaFormatTranslator.java
Also adds a gradle task for re-formatting PDL, so MP owners can get improvements we make to PDL formatting.
=> Fix the issue introduced when trim whitespace started clobbering newlines between elements.

gradle.properties
Releasing Kyle's RestRequestBuilderGenerator fix
=> Release 28.2.2

data/src/main/java/com/linkedin/data/schema/annotation/PathSpecBasedSchemaAnnotationVisitor.java, data/src/main/java/com/linkedin/data/schema/util/CopySchemaUtil.java, data/src/test/java/com/linkedin/data/schema/util/TestCopySchemaUtil.java
CopySchemaUtil will be moved to util package and become a public class. Currently it is only used by annotation package.
=> Move CopySchemaUtil and its test to util package and make CopySchemaUtil public

data/src/main/java/com/linkedin/data/schema/resolver/AbstractMultiFormatDataSchemaResolver.java
Look for PDL schemas first as it is now the recommended schema format to use.
=> Switch the order of resolving schemas, look for PDL first.

gradle.properties
didn't realized someone had already bumped, so I need to rebump in order to publish.
=> bump to 28.3.3

.travis.yml
Iterative fix for setting up automated releases.
=> Dequote secure strings in Travis config

src/guide_restli_server.md
Fix documentation about Finders with @ActionParam arguments.
=> Remove ActionParam on the finder section

d2/src/main/java/com/linkedin/d2/balancer/util/TogglingLoadBalancer.java, gradle.properties
Forgot to implement getDarkClusterConfigMap in TogglingLoadBalancer.TogglingLoadBalancer delegates to SimpleLoadBalancer.
=> Implement ClusterInfoProvider.getDarkClusterConfigMap in TogglingLoadBalancer

d2/src/main/java/com/linkedin/d2/balancer/LastSeenBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/zkfs/LastSeenLoadBalancerWithFacilities.java, gradle.properties
Enabling warmup in LastSeen Loadbalancer
=> Enabling warmup in LastSeen Loadbalancer

gradle.properties
The classloading issue has already been fix in https://github.com/linkedin/rest.li/pull/329. This PR is to release a new version.
=> [pegasus] Release 29.3.2

CHANGELOG.md, gradle.properties
=> Release 29.4.2

d2-benchmark/build.gradle, d2-benchmark/src/jmh/java/com/linkedin/d2/balancer/strategies/BaseTransportTestClient.java, d2-benchmark/src/jmh/java/com/linkedin/d2/balancer/strategies/LoadBalancerStrategyBenchmark.java, d2-benchmark/src/jmh/java/com/linkedin/d2/balancer/strategies/NoLatencyTransportClient.java
Re-created a PR with cleaner commits, reference: https://github.com/linkedin/rest.li/pull/348
=> D2 relative strategy benchmark

CHANGELOG.md, gradle.properties
=> Release 29.5.2

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/resolver/ExtensionsDataSchemaResolver.java, generator/src/test/java/com/linkedin/pegasus/generator/TestDataSchemaParser.java, generator/src/test/resources/generator/extensionSchemas/extensions/FuzzExtension.pdl, generator/src/test/resources/generator/extensionSchemas/pegasus/Fuzz.pdsc, gradle.properties, restli-server/src/main/java/com/linkedin/restli/server/ResourceContext.java
In the extension schema resolver, since we are multi format resolver, we should be able to read / parse pdsc files as well.
=> Add pdsc support for extension schema resolver

CHANGELOG.md, restli-common/src/main/pegasus/com/linkedin/restli/common/ExtensionSchemaAnnotation.pdl
Update ExtensionSchemaAnnotation schema: 
Remove resource field.
Add versionSuffix as an optional field.
=> Update ExtensionSchemaAnnotation schema

src/pdl_schema.md
=> Clarify that array items may be any valid PDL type

CHANGELOG.md, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java, gradle.properties
Check whether schemas exist or not before running pegasusSchemaSnapshotCheck task
=> Check whether schemas exist or not before running pegasusSchemaSnapshotCheck task

CHANGELOG.md, gradle.properties
=> Release last commit as minor version bump

src/Validation-in-Rest_li_converted.md
To make the note more noticable
=> Minor change on the validation wiki page

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/StateUpdater.java, gradle.properties
I just realized that one of my previous change changed log level from info to debug, it should be info level when the state has been changed under relative load balancer. Hence updating it to the correct behavior.
=> Fix log issue in relative load balancer

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/validation/ValidateDataAgainstSchema.java, data/src/test/java/com/linkedin/data/schema/validation/TestValidation.java, gradle.properties
Remove the empty union as invalid map.
=> remove empty map as invalid union

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/EnumDataSchema.java, data/src/main/java/com/linkedin/data/schema/grammar/PdlSchemaParser.java, generator-test/src/test/java/com/linkedin/pegasus/generator/test/TestEnum.java, generator/src/main/java/com/linkedin/pegasus/generator/JavaDataTemplateGenerator.java
Add support for accessing schema statically from generated template classes and for getting symbol properties from enum schema properties.
=> Improve support for accessing schema and enum symbol properties.

CHANGELOG.md, data-avro/src/main/java/com/linkedin/data/avro/PegasusUnionToAvroRecordConvertCallback.java, data-avro/src/main/java/com/linkedin/data/avro/SchemaToAvroJsonEncoder.java, data-avro/src/test/java/com/linkedin/data/avro/TestSchemaTranslator.java, gradle.properties
Add more tests for UnionWithAlias translation
=> Fix for "pegasus to avro translation of UnionWithAlias RecordFields does not have field properties". 

CHANGELOG.md, gradle.properties, restli-common/src/main/pegasus/com/linkedin/restli/restspec/BatchFinderSchema.pdl, restli-common/src/main/pegasus/com/linkedin/restli/restspec/MaxBatchSizeSchema.pdl, restli-common/src/main/pegasus/com/linkedin/restli/restspec/RestMethodSchema.pdl, restli-int-test-api/src/main/idl/com.linkedin.restli.examples.greetings.client.batchGreeting.restspec.json, restli-int-test-api/src/main/snapshot/com.linkedin.restli.examples.greetings.client.batchGreeting.snapshot.json, restli-int-test-server/src/main/java/com/linkedin/restli/examples/greetings/server/BatchGreetingResource.java, restli-int-test-server/src/test/java/com/linkedin/restli/docgen/TestResourceSchemaCollection.java, restli-int-test/src/test/java/com/linkedin/restli/examples/TestMaxBatchSize.java, restli-server/src/main/java/com/linkedin/restli/internal/server/RestLiMethodInvoker.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceMethodDescriptor.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceModelEncoder.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/RestLiAnnotationReader.java, restli-server/src/main/java/com/linkedin/restli/server/annotations/MaxBatchSize.java, restli-tools/src/main/java/com/linkedin/restli/tools/compatibility/ResourceCompatibilityChecker.java, restli-tools/src/main/java/com/linkedin/restli/tools/idlcheck/CompatibilityInfo.java, restli-tools/src/test/java/com/linkedin/restli/tools/compatibility/TestResourceCompatibilityChecker.java, restli-tools/src/test/resources/idls/curr-greetings-coll-fail.restspec.json, restli-tools/src/test/resources/idls/curr-greetings-coll-pass.restspec.json, restli-tools/src/test/resources/idls/prev-greetings-coll.restspec.json
This PR is adding max batch size support:
1. Add MaxBatchSize annotation and expose it in the IDL.
2. Add validation based on the max batch size 
3. Add resource compatibility check rules for MaxBatchSize
4. Add related tests
=> Add MaxBatchSize support

d2/src/test/java/com/linkedin/d2/balancer/clients/RetryClientTest.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/StateUpdaterTest.java, darkcluster/build.gradle, darkcluster/src/test/java/com/linkedin/darkcluster/TestDarkResponseValidationMetricsCollectorImpl.java, r2-int-test/src/test/java/test/r2/integ/TestJetty404.java, restli-int-test/src/test/java/com/linkedin/restli/client/TestRestLiScatterGather.java
Tests were chosen based on recent flaky failures in CI.
=> Add retries for various flaky tests

gradle-plugins/src/integTest/groovy/com/linkedin/pegasus/gradle/publishing/PegasusPluginLegacyIvyPublishIntegrationTest.groovy, gradle-plugins/src/integTest/resources/ivy/legacy/expectedChildIvyDescriptorContents.txt, gradle-plugins/src/integTest/resources/ivy/legacy/expectedGrandparentIvyDescriptorContents.txt, gradle-plugins/src/integTest/resources/ivy/legacy/expectedParentIvyDescriptorContents.txt
Regression test to certify legacy Ivy publication behavior
- Grandparent -> parent -> child pattern certifies that child project can transitively resolve references to schemas contained in grandparent's data-template jar
=> Regression test to certify legacy Ivy publication behavior

src/guide_restli_client.md, src/guide_restli_server.md, src/protocol.md
the info about  action method on entity level is incomplete, adding som examples.
=> Add some missing description for action method on entity level

CHANGELOG.md, generator-test/src/test/java/com/linkedin/pegasus/generator/test/TestMaskMap.java, generator-test/src/test/java/com/linkedin/pegasus/generator/test/pdl/fixtures/CustomRecord.java, generator/src/main/java/com/linkedin/pegasus/generator/JavaDataTemplateGenerator.java, generator/src/main/java/com/linkedin/pegasus/generator/PegasusDataTemplateGenerator.java, generator/src/main/java/com/linkedin/pegasus/generator/ProjectionMaskApiChecker.java, generator/src/test/java/com/linkedin/pegasus/generator/TestProjectionMaskApiChecker.java
Updated projection mask builder APIs to support updating the mask objects. Added support for checking if a nested type supports new ProjectionMask API before generating new typesafe APIs for them.
=> Update projection mask builder APIs to support updating masks.

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/test/java/com/linkedin/d2/balancer/clients/RetryClientTest.java, gradle.properties
DEAULT_RETRY_LIMIT -> DEFAULT_RETRY_LIMIT
=> Fix a typo in D2ClientConfig

CHANGELOG.md, gradle.properties
Testing how the JFrog Artifactory plugin release process works in CI.
=> Release 29.17.3

CHANGELOG.md, gradle.properties
The first release that's exclusively on JFrog Artifactory.
Testing the end-to-end JFrog release flow.
=> Release 29.17.4

restli-int-test/src/test/java/com/linkedin/restli/examples/TestParseqBasedFluentClientApi.java, restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/fluentspec/BaseResourceSpec.java, restli-tools/src/main/resources/apiVmTemplates/action.vm, restli-tools/src/main/resources/apiVmTemplates/resource.vm, restli-tools/src/main/resources/apiVmTemplates/resource_interface.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_create_id.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_create_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_delete.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_get.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_partial_update_no_return.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_partial_update_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.batch_update.vm, restli-tools/src/main/resources/apiVmTemplates/rest.create_id.vm, restli-tools/src/main/resources/apiVmTemplates/rest.create_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.delete.vm, restli-tools/src/main/resources/apiVmTemplates/rest.get.vm, restli-tools/src/main/resources/apiVmTemplates/rest.get_all.vm, restli-tools/src/main/resources/apiVmTemplates/rest.partial_update_no_return.vm, restli-tools/src/main/resources/apiVmTemplates/rest.partial_update_return_entity.vm, restli-tools/src/main/resources/apiVmTemplates/rest.update.vm, restli-tools/src/main/resources/macros/library.vm
- Moved parameters class, associate keys to the interface
- Change all tests to use interface instead
- Tested subresource generation from parent resource interface
=> Add fluentAPI interfaces

src/Request-Response-API-R2.md
=> ben --> been

src/batch_finder_resource_method.md, src/guide_restli_server.md, src/protocol.md
reference:
https://github.com/linkedin/rest.li/pull/651/files
=> Add a bit explanation for construting url using  both "q" and "bq" query parameter names

CHANGELOG.md, gradle.properties, restli-common/src/main/java/com/linkedin/restli/common/OptionsResponse.java, restli-docgen/src/main/java/com/linkedin/restli/docgen/DefaultDocumentationRequestHandler.java, restli-docgen/src/main/java/com/linkedin/restli/docgen/RenderContext.java, restli-docgen/src/main/java/com/linkedin/restli/docgen/ResourceSchemaCollection.java, restli-docgen/src/main/java/com/linkedin/restli/docgen/RestLiDocumentationRenderer.java, restli-docgen/src/main/java/com/linkedin/restli/docgen/RestLiHTMLDocumentationRenderer.java, restli-docgen/src/main/java/com/linkedin/restli/docgen/RestLiJSONDocumentationRenderer.java, restli-int-test-server/src/main/java/com/linkedin/restli/examples/RestLiIntTestServer.java, restli-int-test-server/src/test/java/com/linkedin/restli/docgen/TestResourceSchemaCollection.java, restli-int-test/src/test/java/com/linkedin/restli/examples/RestLiIntegrationTest.java, restli-int-test/src/test/java/com/linkedin/restli/examples/documentation/TestCustomDocumentationHandler.java, restli-int-test/src/test/java/com/linkedin/restli/examples/documentation/TestDocumentationHandler.java, restli-server/src/main/java/com/linkedin/restli/internal/server/model/ResourceModel.java
The changes in this PR would allow a rest.li service to use custom renderers for HTML or JSON documentation handler.
=> Add hooks for customizing documentation (OPTIONS) response.

CHANGELOG.md, generator/build.gradle, generator/src/main/java/com/linkedin/pegasus/generator/DataTemplateGeneratorCmdLineApp.java, generator/src/main/java/com/linkedin/pegasus/generator/DataTemplatePersistentClassChecker.java, generator/src/main/java/com/linkedin/pegasus/generator/PegasusDataTemplateGenerator.java, generator/src/test/java/com/linkedin/pegasus/generator/TestDataTemplateGeneratorCmdLineApp.java, generator/src/test/resources/generator/NeedsCustomResolver.pdl, generator/src/test/resources/generator/NeedsCustomResolvers.pdl, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateDataTemplateTask.java, gradle.properties, restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java, restli-tools/src/test/java/com/linkedin/restli/tools/clientgen/TestRestRequestBuilderGeneratorEntryPoint.java
Update datatemplate generator command line app to accept a list of resolver directories to use for resolving schema referenfes. Refactored the app to use CLI library instead of passing arguments using system properties.
=> Update data template generation task to accept custom resolver directories.

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerServer.java, d2/src/main/java/com/linkedin/d2/balancer/clients/DegraderTrackerClient.java, d2/src/main/java/com/linkedin/d2/balancer/clients/DegraderTrackerClientImpl.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClient.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClientFactory.java, d2/src/main/java/com/linkedin/d2/balancer/clients/TrackerClientImpl.java, d2/src/main/java/com/linkedin/d2/balancer/properties/PropertyKeys.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperAnnouncer.java, d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperServer.java, d2/src/main/java/com/linkedin/d2/balancer/simple/UriLoadBalancerSubscriber.java, d2/src/main/java/com/linkedin/d2/balancer/strategies/relative/StateUpdater.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperAnnouncerJmx.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperAnnouncerJmxMXBean.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperServerJmx.java, d2/src/main/java/com/linkedin/d2/jmx/ZooKeeperServerJmxMXBean.java, d2/src/test/java/com/linkedin/d2/balancer/clients/DegraderTrackerClientTest.java, d2/src/test/java/com/linkedin/d2/balancer/clients/DynamicClientTest.java, d2/src/test/java/com/linkedin/d2/balancer/clients/RequestTimeoutClientTest.java, d2/src/test/java/com/linkedin/d2/balancer/clients/RetryClientTest.java, d2/src/test/java/com/linkedin/d2/balancer/clients/RewriteLoadBalancerClientTest.java, d2/src/test/java/com/linkedin/d2/balancer/clients/RewriteLoadBalancerClientTestStreamRequest.java, d2/src/test/java/com/linkedin/d2/balancer/clients/TrackerClientImplTest.java, d2/src/test/java/com/linkedin/d2/balancer/clients/stub/LoadBalancerMock.java, d2/src/test/java/com/linkedin/d2/balancer/servers/TestZooKeeperAnnouncer.java, d2/src/test/java/com/linkedin/d2/balancer/servers/ZooKeeperServerTest.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/degrader/DegraderLoadBalancerTest.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/StateUpdaterTest.java, d2/src/test/java/com/linkedin/d2/balancer/strategies/relative/TrackerClientMockHelper.java, gradle.properties
Allow disabling of load balancing for a specific host. Verified by JMX with local deploy of client, server, and zk that it's working as expected. 
Will update changelog and gradle.properties at the end when ready to merge.
=> Allow disabling of load balancing for a specific host.

CHANGELOG.md, gradle.properties, restli-server/src/main/java/com/linkedin/restli/internal/server/util/RestUtils.java, restli-server/src/test/java/com/linkedin/restli/internal/server/util/TestRestUtils.java
Fix bug introduced in https://github.com/linkedin/rest.li/pull/695
=> Fix Supported mime type config for response payload

contribute/howto.html
=> a small typo in contribute/howto.html

generator/src/test/java/com/linkedin/pegasus/generator/TestDataTemplateGeneratorCmdLineApp.java
Some users have reported flakiness on this test depending on their local build environment. Adding logging so that users can actually compare the actual vs expected value.
=> Add better logging to error-prone generator unit test

restli-server/src/test/java/com/linkedin/restli/internal/server/model/TestResourceModelAnnotation.java
Backfilling missing unit tests for ResourceModelAnnotation
=> Add unit tests for ResourceModelAnnotation

src/_data/user_guide_navigation.yml, src/guide_restli_server.md, src/max_batch_size.md
Introduce a new page for max batch size support.
=> Max batch size documentation

CHANGELOG.md, gradle-plugins/src/integTest/groovy/com/linkedin/pegasus/gradle/PegasusPluginCacheabilityTest.groovy, gradle-plugins/src/integTest/groovy/com/linkedin/pegasus/gradle/PegasusPluginIntegrationTest.groovy, gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java
We'll bundle this with the next major release.
=> Require Gradle 5.2.1 (5.3 suggested) in the plugin

CHANGELOG.md, generator-test/src/test/java/com/linkedin/pegasus/generator/test/pdl/UnionGeneratorTest.java, generator/src/main/java/com/linkedin/pegasus/generator/JavaDataTemplateGenerator.java, gradle.properties
This is useful if if people want to write build time switch case to check for things based on member
=> Generate compile time constants for union members

pathspec.html
=> typo in pathspec.html

d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/LastSeenBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/balancer/clusterfailout/ZKFailoutConfigProvider.java, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java
* Fix passing down FailoutConfigProvider from LastSeenBalancerWithFacilitiesFactory
* Added more logging
=> Fix passing down FailoutConfigProvider from LastSeenBalancerWithFacilitiesFactory

gradle.properties
I missed the version number bump after a rebase for commit 85b9d87, need to bump this version number for release.
=> Bump version to 29.33.7.

CHANGELOG.md, gradle.properties
I forgot to bump the version when committing the slf-models branch. This PR simply updates the version.
=> Version bump

CHANGELOG.md, data/src/main/java/com/linkedin/data/template/DynamicRecordTemplate.java, data/src/main/java/com/linkedin/data/template/RecordTemplate.java, gradle.properties, restli-client/src/main/java/com/linkedin/restli/client/ActionRequestBuilder.java, restli-client/src/test/java/com/linkedin/restli/client/TestClientBuilders.java, restli-tools/src/main/java/com/linkedin/restli/tools/symbol/RestLiSymbolTableProvider.java, restli-tools/src/test/java/com/linkedin/restli/tools/symbol/TestRestLiSymbolTableProvider.java
Experimental optimization of action request building
Revert "Provide a mechanism to set a routing hint for the d2 request to get request symbol table
=> Experimental optimization of action request building

CHANGELOG.md, build.gradle, gradle.properties
This is to get some confidence with ZK 3.6.3 before moving to 3.7.1.
=> Use ZooKeeper 3.6.3

build.gradle, d2/build.gradle, d2/src/main/java/com/linkedin/d2/balancer/D2ClientBuilder.java, d2/src/main/java/com/linkedin/d2/balancer/D2ClientConfig.java, d2/src/main/java/com/linkedin/d2/xds/Node.java, d2/src/main/java/com/linkedin/d2/xds/XdsChannelFactory.java, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/main/java/com/linkedin/d2/xds/XdsD2ClientCli.java, d2/src/main/java/com/linkedin/d2/xds/XdsToClusterPropertiesPublisher.java, d2/src/main/java/com/linkedin/d2/xds/XdsToD2PropertiesAdaptor.java, d2/src/main/java/com/linkedin/d2/xds/XdsToServicePropertiesPublisher.java, d2/src/main/java/com/linkedin/d2/xds/XdsToUriPropertiesPublisher.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancer.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsLoadBalancerWithFacilitiesFactory.java, d2/src/main/java/com/linkedin/d2/xds/balancer/XdsTogglingLoadBalancerFactory.java, d2/src/main/java/com/linkedin/d2/xds/example/XdsD2GreeterClient.java, d2/src/main/java/com/linkedin/d2/xds/example/XdsD2GreeterServer.java
Steps to run locally:
1. Locally deploy ZK instance
2. In indis-mcp-server, run `./gradlew runWriter` and `./gradlew runMcp`
3. Start local istiod instance: `export ENABLE_CA_SERVER=false ; ~/tmp/pilot-discovery discovery --meshConfig /Users/riczhou/go/src/istio.io/istio_configs/mesh_config.yaml --registries "" --vklog=9 --log_output_level all:debug 2>&1 | tee /tmp/2`
4. Run `./gradlew runXdsGreeterServer`
5. Run `./gradlew runXdsGreeterClient`
=> [xds] Implement Java XdsClient and XdsToD2PropertiesPublisher, Add an example Greeter xDS D2 client and server

CHANGELOG.md, gradle.properties
=> release 29.40.4

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/RecordDataSchema.java, gradle.properties
add a getter for a private field.
=> Add getter for IncludesDeclaredInline in RecordDataSchema

CHANGELOG.md, data/src/main/java/com/linkedin/util/DataComplexUtil.java, data/src/test/java/com/linkedin/util/TestDataComplexUtil.java, gradle.properties
Currently, there are some internal implementations of this, but logic is pretty standard conversion between java and restli objects.
=> [rest.li] Add util class to convert generic List/Map to DataList/DataMap or vice versa

data-avro/src/test/java/com/linkedin/data/avro/TestDataTranslator.java
Some feedback was missed in #886 . This PR is a follow-up to fix any additional feedback 
https://github.com/linkedin/rest.li/pull/886#discussion_r1107672875
=> add float test check - follow-up from #886

CHANGELOG.md, gradle.properties, r2-netty/src/main/java/com/linkedin/r2/netty/client/http/HttpChannelInitializer.java, r2-netty/src/main/java/com/linkedin/r2/netty/client/http/HttpChannelPoolFactory.java, r2-netty/src/main/java/com/linkedin/r2/netty/client/http2/Http2ChannelPoolFactory.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/HttpClientFactory.java, r2-netty/src/main/java/com/linkedin/r2/transport/http/client/common/ChannelPoolManagerFactoryImpl.java
Extrapolating the code from HTTP/2 support
=> Support Unix sockets for HTTP/1

CHANGELOG.md, gradle.properties, restli-client/src/main/java/com/linkedin/restli/client/RestClient.java
Add log message in RestClient for ScatterGatherStrategy map URIs empty case.
Based on the code path this situation should not happen. 
Adding log message for debugging purpose if such rare case occurs.
=> Add log message in RestClient for ScatterGatherStrategy map URIs empty case

CHANGELOG.md, gradle.properties
Update CHANGELOG and trigger build
=> Update CHANGELOG and trigger build

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/LoadBalancerWithFacilitiesDelegator.java, gradle.properties
Remove a delegated method in LoadBalancerWithFacilitiesDelegator
=> Remove a delegated method in LoadBalancerWithFacilitiesDelegator

CHANGELOG.md, data/src/main/java/com/linkedin/data/schema/annotation/GrpcExtensionAnnotationHandler.java, gradle.properties, restli-common/src/main/pegasus/com/linkedin/restli/common/GrpcExtensionAnnotation.pdl, restli-common/src/main/resources/legacyPegasusSchemas/com/linkedin/restli/common/GrpcExtensionAnnotation.pdsc, restli-tools/src/main/java/com/linkedin/restli/tools/data/ExtensionSchemaValidationCmdLineApp.java, restli-tools/src/test/java/com/linkedin/restli/tools/data/TestExtensionSchemaValidationCmdLineApp.java
Adds new gRPC annotation schemas, updates compatibility and validation logic.
=> Add support for ER with gRPC downstreams

CHANGELOG.md, gradle.properties
update the changelog and version for previous commit: https://github.com/linkedin/rest.li/pull/939
=> update changelog and version

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerMonitor.java, d2/src/test/java/com/linkedin/d2/balancer/dualread/DualReadLoadBalancerMonitorTest.java, d2/src/test/java/com/linkedin/d2/balancer/util/WarmUpLoadBalancerTest.java, d2/src/test/java/com/linkedin/d2/util/TestDataHelper.java, gradle.properties
As in the title, fix a string formatting in dualread monitoring log to show the properties being compared.
Added unit tests.
=> Fix Dualread monitoring log

CHANGELOG.md, gradle.properties
=> Minor version bump due to internal LinkedIn tooling requirement. No functional changes.

CHANGELOG.md, gradle.properties
Just to fix the change log and gradle.properties for the previous commit.
N/A
=> Bump version for the previous commit

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/balancer/simple/SimpleLoadBalancer.java, gradle.properties
As the title said, fix indis null guard log issue for `dual-read` mode.
create a Depex ticket to bump up this version for all services.
=> fix indis null guard log

CHANGELOG.md, gradle.properties
=> fix changelog and version

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java, gradle.properties
As the title.
[unit test] Added
[manual test]Test has been finished in restli-resource-explorer #337
=> Add watchAllResource subscriber

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/xds/XdsClient.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, d2/src/test/java/com/linkedin/d2/xds/TestXdsClientImpl.java, gradle.properties
This reverts commit 4f561f845d37c4cf24f4596eacf9afbd6ccac2f3.
=> Revert "Add watchAllResource subscriber (#1020)"

d2/src/main/java/com/linkedin/d2/balancer/servers/ZooKeeperAnnouncer.java
This is needed for https://github.com/linkedin-multiproduct/container/pull/1158.
Please see test done in that PR.
=> Add getters in ZookeeperAnnouncer

CHANGELOG.md, gradle.properties
Bump the version for change https://github.com/linkedin/rest.li/pull/1025.
=> bump version for previous change

CHANGELOG.md, d2-schemas/src/main/pegasus/com/linkedin/d2/D2Cluster.pdl, d2-schemas/src/main/pegasus/com/linkedin/d2/SlowStartProperties.pdl, d2/src/main/java/com/linkedin/d2/balancer/properties/ClusterProperties.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ClusterPropertiesJsonSerializer.java, d2/src/main/java/com/linkedin/d2/balancer/properties/ClusterStoreProperties.java, d2/src/main/java/com/linkedin/d2/balancer/properties/PropertyKeys.java, d2/src/main/java/com/linkedin/d2/balancer/properties/SlowStartProperties.java, d2/src/test/java/com/linkedin/d2/balancer/properties/ClusterPropertiesSerializerTest.java, gradle.properties
Added `SlowStartProperties` class and support for ser/deser for the same. The values would be received from Indis/ZK via the LPS D2 flow.
Added UTs.
=> Add d2 slow start configuration support

CHANGELOG.md, gradle.properties
Releasing new version with fix from #1056
=> Release 29.65.7 with query tunnel fix

CHANGELOG.md, gradle.properties
This releases the changes from #1065
=> Release rest.li version 29.69.1

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStore.java, gradle.properties
Skip node creation for post commit
=> Skip node creation for post commit

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStore.java, d2/src/main/java/com/linkedin/d2/xds/XdsClientImpl.java, gradle.properties
=> Fix the shutdown issue for XdsClientImpl and add more comments for Raw D2 Client usages tracking

CHANGELOG.md, d2/src/main/java/com/linkedin/d2/discovery/stores/zk/ZooKeeperEphemeralStore.java, gradle.properties
Skipping node creation for local execution
=> Skipping node creation for local execution

CHANGELOG.md, d2-schemas/src/main/pegasus/com/linkedin/d2/D2Cluster.pdl, d2-schemas/src/main/pegasus/com/linkedin/d2/OutlierDetectionConfig.pdl, gradle.properties
Outlier detection is a load-balancing feature provided by Envoy clusters. In this PR, we add a PDL for outlier detection based on Envoy’s protocol and integrate it into D2Cluster. For more details, please see [config.cluster.v3.OutlierDetection](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/outlier_detection.proto).
=> Add outlier detection config into D2Cluster
